{
  "name": "Collections",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "en-US",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Accounts",
        "columns": [
          {
            "name": "account_id",
            "dataType": "int64",
            "sourceColumn": "account_id",
            "summarizeBy": "none"
          },
          {
            "name": "customer_id",
            "dataType": "int64",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "collector_id",
            "dataType": "int64",
            "sourceColumn": "collector_id",
            "summarizeBy": "none"
          },
          {
            "name": "portfolio",
            "dataType": "string",
            "sourceColumn": "portfolio",
            "summarizeBy": "none"
          },
          {
            "name": "placed_date",
            "dataType": "dateTime",
            "sourceColumn": "placed_date",
            "summarizeBy": "none",
            "formatString": "yyyy-MM-dd"
          },
          {
            "name": "days_past_due",
            "dataType": "int64",
            "sourceColumn": "days_past_due",
            "summarizeBy": "none"
          },
          {
            "name": "region",
            "dataType": "string",
            "sourceColumn": "region",
            "summarizeBy": "none"
          },
          {
            "name": "credit_score",
            "dataType": "int64",
            "sourceColumn": "credit_score",
            "summarizeBy": "none"
          },
          {
            "name": "collector_name",
            "dataType": "string",
            "sourceColumn": "collector_name",
            "summarizeBy": "none"
          },
          {
            "name": "payment_count",
            "dataType": "int64",
            "sourceColumn": "payment_count",
            "summarizeBy": "none"
          },
          {
            "name": "attempts",
            "dataType": "int64",
            "sourceColumn": "attempts",
            "summarizeBy": "none"
          },
          {
            "name": "rpc_count",
            "dataType": "int64",
            "sourceColumn": "rpc_count",
            "summarizeBy": "none"
          },
          {
            "name": "ptp_count",
            "dataType": "int64",
            "sourceColumn": "ptp_count",
            "summarizeBy": "none"
          },
          {
            "name": "aging_bucket",
            "dataType": "string",
            "sourceColumn": "aging_bucket",
            "summarizeBy": "none"
          },
          {
            "name": "original_balance",
            "dataType": "double",
            "sourceColumn": "original_balance",
            "summarizeBy": "none"
          },
          {
            "name": "collected",
            "dataType": "double",
            "sourceColumn": "collected",
            "summarizeBy": "none"
          },
          {
            "name": "outstanding",
            "dataType": "double",
            "sourceColumn": "outstanding",
            "summarizeBy": "none"
          },
          {
            "name": "score_band",
            "dataType": "string",
            "sourceColumn": "score_band",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Accounts",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                " Source = Json.Document(Binary.Decompress(Binary.FromText(\"hH1bqzVHkt1fEd+rtzZ5vzza/WZsY2xDPwx+aNzCM9C0QKNmPP/esSKzKiMis0rQhfZu6Zw8VZUZ17VW/NM/+Y//pM+P//rLX//l//zlbz8+P4IL5WcXfvb5x8e38vnx33797fd//uUv//r7j0+Kgf7TX3/7v3/5+w/+Of9xnx/5Jx/8f/jxCdHF9A35E9o3eHx15evol/+nX/7267/9lJv78b8//xQ+gX7sx3/8x++/ytUa/cJc6bf/y1//7ReslVOm/+pvv/y/H7RGpEuslEOM+M3u6+7PepVIP3K4Lf+zD7RQbJ8f//PXf/z+z3RL3ctbmn/dtZCvsYZviB/fW/3S3+dzbOlbilku0WL05/73X37711///pe//fRffsWvm4vmnwPdXXHqUVb8jv/xL3/75d/pwdFP87Lhp+h/Lo7/wpq/tX96Td/ePz505770V5fq/gMWzLRcNE8x/ezwFPEs5EKB3tl//vW3v143yE8y/dTxLGipEFKft9boVusnuO7zN661yqcc3pgrWItu4s+/jK1RrteVPpUutYjvPbhvaZ/Ym/9W+n25x/btwTzHSj/q99cWfw4V+6vr3VjqtaSnn4tyh/gYfPmW8Imebo7eX2i9f10367VP+5TtMUb+i9O9RzIW/l9/+fe//frbj/kAxVKpxIw7ibl9ff+kUOu3RrMQvUksZG+MtkbGA1MvzFW5WhyHzP/k+e/qtbkvbQi6wa9Pn1ZSw/O8X5Z39FbwG9U9Rd6C3tf7niqOttz3MATyjdGWo3NVPp2OF/1bF3P/NrkQ/YDHpv/Tb3RTv//0p7/89ldxX77TH09/4NweGZZjbndnn2DoJX7HaZ4f9cPztD4O5uE4Oxzneq1Syez8+NNf/hWreHq1MFD3k/O19vLttAfjtxd8paVcEHdEjzpu24HWoFcUsNNv25TIItyvCAspoxF8LumbyidX/3V8oOhRRrv36OH4tL0pWo6eHP1994uqdb2oRH9e0i8qpeC/BSaCDJMju+djZQN131am0/b0ouLPPtLvyPd7wra/zVLh3b7MUoihlm/Mn0Z7nZ4I2Q5Ptp7ujO7p51I6r0fPFibjwRr6n4PH+ZSPs4vz5ehHs3xv9Dhd+tJT4P1xfTHPsmIXhKc1088B1ir5+6k2OiTXThknTO5H7+gMk0VvdLITvdtM94mds55pI994sBwwwM3LW6tBHuY6DnP8qfifO91b6ZXMOr3RUr70Ekqjm9s3Cr3cjidyvrnINsS7rKxIwdkbxjHyBtX2uBS8Qdp+xZFZpM3jUmcvKl5koMfNpuR8wh2Z5KhNV3Fx7dVw7dV7+7Tq/LfRsaTjEenYhMiOR61JpsjDs+0BCW8bJx9uxc67XFugXRP00Qgud/8l0xEjeR/a2b4Get5evEhyjgHu93njsB0L8pUmEQQ59o1i73SYTfq7sFmvzyYAinSOcB7N3sFB9Hj54yQWcRIdnwi5Q0P3AYEBn4nry7oriifS05sbKwWzW6K8pzTOw205U3Lk28YJvL+o10bPngOSh61CD9HDZio3J+ISxztF2NDSQviOBefHdXNkd8rzK6ONAp8Q1EZJXt5eNfY6xFzhTMfDnF/WevSfs20x72ucI7WMz8L9mI2BCLJ/eyZr17707yj+8TClax06pe3ppY1DXqT/duuW4LVgxZZhabXkbyOrUchytUx/Wkh8vu/VOvnaU6xFkV3Cr9ehVoorGA/GiPnIEVAZ2+P6YuJxiuH3sCSwb01VmOUs72qutPwPmysKO1oMEZbEl9Ay4vP7vsiuxGNGkzhWSF2e5KKeYR27/l6tk7XqyGbit5BtJk9nozoKamJ4tsyerYfvItuofkXJcVjlexumTJ6cwmgyUvlL5pysVSowlGZR8vHx9OZouYhI6/blJazF7KP0DVE+ha3FI/ynRxkq7nBLpBKMfD6Frp4cQAt37IUg4o4c/DjOa48ECsC/mfZ9olNA+9w7csH4sN4cGZB8Mv1ksOC9q3x1GZ5mZTVZR/+hNwr+I9I35ACheYr0tudIZ6Y8Z230NBMHjWLVgl9y36OJYmkxii/p4FCsSAfdI1cM5du0pYyUqNTX6CjB4YiDXqIMjpreNPTyKNuueZy968t6phTtPtoUyrrxZpx8rpWfssjwbeBAeWjDPXk6ql+6x0qGjOOxe8lOSd6beeYMvOlopUaVhdt4rFASjnwjO5zEgHOSRISbyLK40x71w0gj95hPs/R4v8Fok8biYDQjUuiCzCA7TzmPFwvRE/Hnw8AxmF8L8Qa9t0q0z7HljICPjgV8QKWUxG5PijLSMekZnqe6O1CAs5peB5WSaI0zxUBkIadxHl/kjiTTnuLppiIncb5rT1rN8xOOtFOCiXNG8XKH3aq5Vem5E8UkHBE+RAkev3PlPe6yXogkVUASc6EdQB6MLDTdciwO39Y6GRnN8Y4QROpcrvn1ovwVsl53RD6aMjmyE/6b6S2ShYbXWQvRf16eUqvxp1Zds8ixitVmMWa9rJ49l33g3rDhu+8BZROzNSp85sFSxlEBwhuTa2ILrzC5aAtSs6PgkTaoR55fYaar2SBkQdpTcJdGegxDPr0OIvprtXQ51Xs1R9EPfFuIBc4mN3q0ddv7HY66PD5XP1JWeY/4A1ZG7m3g4DOiOjpPZELo+dLNOlrf+vNMVsRtta65a6T3wWrX3py1uxUsh1ARjdMPJ1gROuMufrtNWTMZEuyAh8PA+Uu8n2pBFe/OV63ncbVx5OBdyMhzes2cuMq3SPs3h1PYkDiT8/GuAaQeV13NLhUjhQv0H3hP7jvz3dEhT/YNUhSS49NRH8XDgBVFDcCvRbNOBmgN2i2USXtUY+mpUfBAKWTYFqX9hLDq0fW4qH1rc/6QQK7HmqJDiES7h4vALdSGUsuqwpKVya+ZeWAXLc2NC7JoqZ05vTb3JQvhfU9fCvY9xdJZWlAKoPKjwUmzGnYHgBWZ7u2DbIW00iq4m0rxbUIoTXaUn+m9WP3gfy+hSsBbvGt8xeWXGl/qdBzS8EP3F7VBG1mDQ/kNYWZwVVTsnT3q4qVRksU9CDrgX3o3rZT43Y5e/+B/+0q8PW7HmkSJPtpoveaUcag9smG6k4KyW7bRMyUY5VSNRYoVgjZhqYqKbPo07Vs9HbP6RciKEI+OeEiN67F6PfJgxwDF8yEXUWXyKjxRNWZ0HxLXFNnPFlhreAfZEyA/Ek6PMCNvEsFrE+4uD+d6u7teyfUgYE4OYVZPtFoXu50i3xJPfm4Un3zIq/CbZTHBxo/kThviLN5715e1TPqUtN1L4JqhM2WSKp5aGDvC/fSnf/z22y9//52tY0Y5DwafbDcX6RGoil2OTDI/9DiQb2Sn7klaRJXgwArT9g54TQGpXBABMW3c8lKCTXxy0zq48kSl676W83Q90nagR4QeQEQ5OVOGGoQhJFtVXuqvmZ+lNvgVAfL0aIlNrzROKDDTfsOOQJg8M6u1HhmKtjlqP7scwXTa2qqElmEEVyCec0S8Qz+EBRLtxC63BkUh/bQD/ehIhWqWEgXJaM07RZEBHaJKb4ssBkVaRbVuKOCt7ikioGAc2yPYyNXGBPcZDr1yiSR0epS4Q+eQsYmbo7Cr+kMXkR+LLmJXebqcqZMk8luoWuN0XZ9NWw+B5fN+HCW74GSmnUTd/C7QXzdXCyVqAfFAiog9SqSMEFGuOGh0yzUeynYcIa9GQMkrsNpjuYzOTQtohLP984n9im54kDWu6dAhxWYMTsf/tfVVkymmahEpmYZtrzkUOC9fkFx7cc4ot6/5lBQG3h5Rbo+CvXXnhcV0mGv2/npp1+e1TKFH/FyK9Py2xDOURYO0Wd9AW/FLb6NTVghnkmKpsJJruUrZ3mugUbhPrZ8kpfzLOwdTbKUIo8NbBnRwyFkiXBQLNhQ4X6r+XIuvxSa+ujCiWn70xlCaKDhhFEPQJhHLdaSB9qCNDaKqg/i8wlHzHCnCKGhlU06I3hTFsV9vE5jmKMB8fpKJ/TOHOMKKOBG1magjuOY5H2TPeX25b4yOXPPPfQauftYkii8iwtlAHcGXxjc4+nzzy1oroNh4DAbYengLeyg66U1qf2SPGh25zkxWkoJLiiXQHBZ7pFG8Hx+aztgdOaqz5lQNRhd2XWwZi4yHOL+shSjWS2+bEbFOtrGi2I1xs8h0e2FgEnpraFxStkabp9vwtKGT+wZc8R7GVma+tYrdUk3XAQaL02ouNl1fzJqFgvITFiIND9fWfklJ9YWrrs1QUDC6paOy1U+t01YpITjXlB1vmrxCVZyDVbfIdnNWyv1Q7/eRW8HkERJXMNZ7bJ/WnlLeUbTwwRkEi8i0i60R0k+S9YLrhntDrtE6heHVBv3kUtp7xbXMTtXMa3KWpswkarE1si8VzwbPk2x1+jpbgaKAsbuH4iR32kW61mRTzNpplKzhTxltQst5V9AfsMtRcuBfCofcOb2hSNX55/pFyWjtk2/tdEKQaieKAPgGr/dIx6aH5zBsdAVWnTLnrI6+6dNWsi+zc3p/MTdHJv2xVBJHsfe+N1V5aub41ewyDhw9zI5ctATH1USzHvnD9HR/nkszXZRhW96jCLFHgSRAHjqN9viynmX+9BcDM6Mx1astIYmU0by+XFrknhxtElQPEx36ouM+8jG9PNUOZ0m7dBVqJpn92AZLQ/GHct3UaKdSrEmHsTmuk8hFKyWzD7CFyFnkPHqyFOuuMqXIIIMrBbHDcBXjs3l97dMfzcxMjFsW2DUBozSAzYIyYZ5d9vnZLNY/vT8H7nGYFhPj5q46VvMmRQ8pF9RMpuG+vigIkQOKzZ28xPC+zTp7L1E2M5lcKJuIbULPLbFJ4zRWZq9AleB6OBOjZUWbex0KhTMzad4AC1G8W9EGp0AjqqKGR0nYhdO9zXphXZG1ApqF61GuAqVvKPMiFCTnQ0FnsZbTO2R+cQs+I5ftYzPJSdCl+6hShuAquR9UznKMHMlnT0fBR3lziQGoO6qNS+hh74WsIMbkeJ6L2Aj5UinsBQt6ExuEE8Anvh4r6ZFdqQEyK7SqDtdiphyvoccyEJC+1Vg5vTQLFwbAnkvqOBdBYQZzWV7JvMjUM/vcnAANScnz+na5ikL/A1jboDu59b9c/Ga2MyMU6T1l7v1Q/udRV7crcpv+VE5MA41V6/JL/bba6UKjrAAYrxKlvOY5TycDnDivtgt2NiaHuGIE+R6Z93UGuxOJu4krevEFxqU5/yV/UtHGUyhZwGQPONnETUhfb1RDhnNYqe1W1HbkjyjDSRReYWsC5xyQCJobY7DsEdc2SqarZl+CygGjwdq01hJ3QLjVSnllpVzadHpQAPMDMPtYjrugDZedQY1MeHldei54bbQRRlQ/v9g7RA0tPmCcOTbRpibXQ31HwJeS49tM1X89krnOPab1/sjO+HTugTKi1a+uhJdGzaZKIbbE5bhUw4DBcxe7FfNIycD4l0hmBharXxedqBTPQG0hWulAoK7jYWnQ5+m0z9BN02uSbXlH0nLgu0DWVTpef+0dceojvbra6JEEQDZSBfZTPdXKVuSxoTVg3T56U/VMy5iadgz6vEDvRU9pBNoWZEwZHbbWRHb6EtDAtGUNHUxZBPgT8LBeaODeYAWSLw34Nb2MLaXwePz+NW1iIPZ6tgr1aZ1VolQ3XADJ8XndYmCA7bnoPzqhCg1dswQ+JO2buqtscPJAjgBGeCi4IqTG9QhNwHsUlZmsOoXFxE8+ZxeBLacnOrr30efEgGizKveDzw4DNxpFzVDBW+2p7GTVynic86N4mpGxpI/MAxTma1vNbC/SiWhhadWFUSDpZGgKQ4xyRV5o7yx9+Hp6hRy0TZfh4zoOSTuMVgBhogeZggPsoYTQdxYMGlv+GU8bR+0iqnp5LhIPV/W2SYW2pAfsoaFPlFLlHr6yNqFwwHKslYSrr3y5i6ycVDKdZbJviVEWiUwrGYdeKLzxm1MMKLvVp1QtDOxW02n9SitsYk870l2J6P1F7BogHNvW5csDA9cNz01gGdOF0lkZISUsFDmXELkHQdnW19uajA9c03ipoZeJZreEpgWf36haxaMmQ3lM918EbeFQmfERxbBj6jRBaq0JkFqWXtjy+Sj78AARp1BHcaajl7S9x+jZJbzAYFFGDH7FOKVJC6eDjeR6YLCVo8WBS6AY21tqAiB9uB4f72iBNRWernjYVp4d2GkoCiFZg9ul3KPuyH2P2kqMzz5jVvlaWqU291HAc5u/ob8Zxp69vtg1E9pcWyNr4ijzOpQSB7iBiyk2i9x8DDVHJIsZ5UyTdcOfxBeqEOr5uZmOeBddmGZBxj37AYUF3hHxXC1IPMyyhat3O5gAsTjchLByQfUqLDi15d6AKebneX3Ra1WAiJ5tDidSSWF+kSqu8pBpylT0tOBGKMDImSuXarnGZFObfeeLVrG8lGKyNNOtoLfXvsyCq1xR74ya27dnZwKJ3Sp5JGtFgFOrF+H+hralnCbMEtT8bJlriHLc84kfHiMXXck3J170j8k7kVXKqWKtWFKHj7RreiZwHe0a7Auzh8XOZKDVFgyvwiwdKjxCD1ooBTwUSGXV2/IgfqXwQCXwE1YsWEH9EB8usJUjEzpR2vOzvT90l+Mzem0kbcGZko1XG2cHXSXmnMTcmX5Ld41NKsMpIHLTI1loIkrTst2y84QzmKX1ri35q7J3fRZL0X+bHu1LGv3QEPWuuY97Mo6iN/g/P5Hv84t9qGg3l9eEJuKI67qUz7LGrmNhCthKQWgBeju3fF0pZcciwojgeuwjcP3NcMKDRHLPGG5hERJZ8DZzjOuLeLhkatJuakb3JxeTsWWZE0/yr0DLgpzNIFzKMjLbN5BFslyuI9F5rtD2VVwoQVnQaMMaiipQnAGgjZ58JStgSvoAReF6A5DE0bVQR8PrEoMtQzdHPhBZTU0DMphjjApm5OGy8pFONOqKUSDqvCFUm5ZsA3APBJiAI8nKAs3wdJlp+mwBZnk4mduMBm+tgQmue8c9oTSJ8GQRwlfdY+Qw4pC0zRC86/J+iUmhSg2JqdDbdOgxVuRVwQEX6YxbxJZCf+rlTrnFLn1/zlG+TkM9IM8YGDobEbMi50it7TR8nxm99tI+uQC7N4AxLPCYKTKGyND5inSoY83Rn43SieCF55cazgSBKDp0TspzhW3jukZhAP3WSEk46m4OxYC032tlp/gYrU7icFJ5ZBBlju0pB4d6HJ5yTAOQzbxCWBP1etuHr0f0NxeRRI9RtsG3Ln+IXK3q3qNETv4BLDn5iDvXhc/NaOYaKaRGXjY2cmFOu2nQBEAYa1zOpQxolMgUvx1VUPfc6b84jQLznbYe3G0YSmu0YSfTlT+uW0NBouwQvRGJdwMJgfNY2ENnraxvwCiR609QdICmSAS5JGwJJO14vrZFkSmnlY7HJrELugjnCzoaETDUzEavoL8vrQ7YeSVuBfg8QCA1mYKfSoxNlNMpUYVFpWCVS+LQTNm7NTifJb2FAhwli/CDYW1XHOBt/BjJjAfOBxMKmoHyt6QjK+B8S34uw1/nT1FS4dNFId7UOAb2ZJQ4xmd7l3jWLwHPFAIpinqRBdDY2LiIFiOdPmZAUTqAtHgrjjFToZ47mghdVje6uK6NuFdwywbKLYfdmYtxFAtki7b0AP6WF/Re5ognKFpjdk5uoMZPVpCS3BD5ibSuA8Wi1h2nAdSALyccH9uzIuDU7SUmpx02wNPopIBB6UpPCuRJVujD15GcjW6mNC41xuWhJsfjxsn2zt0oT3/dYNI3NtZrJWZwPqXDaXAvvIlSi9cJsa5p5F5ZKCYAfMJmBqgXFaqy4zhyGwepGPUOcYPYAAJApOsaFHwzS5t1QfBUKXo3+ieVicAbs2TIMnlD0EutyR0aTDsjZz+bCr19kdwnQO93OZLENuwgw8P4Sw2u7nJrmjyVHE3n6lfEP1GaCp0y1rYd/Aq+eH55kwH5hcmQFex/sp/uTCe7BkIg9zUTBXFedoog4VTLK9eqT3z8jZPqMk4126ZExxQGCpaYlJRqPMBR0LLE9Vy+YQqFzMtZI0RCQ3Q/xWG3TsJlYep2LuZO6S3XN/rjlHy58VIqHN/Sx4pSUf80sjSeo/FRPF7Ldd6Sew0HlCEtf5KDLPgVGyZS6IJqLdm61OLQE2BzusWJjRvlpyjDzZa7wLk22WbYOFEopoDGVQGVpKTR6647Wv/tgZ/kmRIlGu9v3LVhM+mtJBCMvUM4mrYzwcD9B8wwy9vlvfy+2e27aYstgjSV8grInbiYD5AJsMdb3IKnqSlW7nZiLn7FFqbu3hIrJfSCHVkn5dgsk7jK/FypDSMEVfGhbIQ1QwcIDr6Bi+qBJY86sIR1XzgzuuyhWuRHWyNplkr6qKaG5lj66CoESsh+86bpgDFJ3Dc6QLiOpAe24E6AQlLZQSEq5YeXoH9TG8rQZCrA8JcaYCxt8ATlQ4CowPNZitgMGQqFs6GwNyALreB1gixKkWrcH2rjrswbzK4PsNbVCTMJouZr+e6aG8olnTVgWoUPUQcR/29/UDJAvWj1vV1VMkRmKcfdr7uDMb6sdTpKc0eg8JB+aTuq/c7NpnG5Y5k4PINPZEE7jAx54I05Du47rh3Yc5MtZChTlexRsfzflldL8foibg7H5LEHNbpeqYmOt3L01YhjhdjoLZEJip0SXLjCDnEwhXoBTrifkiaWlDCSTq5/dnTdwkSCqEUxLhYDTDHkaEGtkEDk69HbcrNrsT0LSgmLaaceZka0O5hUDDmLSLGbCe0Rx/V8JgeEWS+9a8NenoFpQhf7DVw7ioxzGnKTwdGz3OMJ6AD2cnigbiOkOcPOVRp19FdTOkaPk/6RuFOTAMp0pjACDH9/UX+ZqqumWsuqajpOUx2owt0T8nQFLjGDw1jNuo23/rFEwhZbtGqYwyh6QybthVu4mkPXF7FBuaHyR7mZstisoHU/1005NPlaR5Gr8X7lOFgCiIIDUvpRp26Uho3cDGPC1lFMVjOlUiLKIgcZ2S8KFUMFVqvjeSbBPSLNh3LcIuPHKjdstpWnCcHEisjhMzmO7uVtBkaxPgb493JXvJ28rrobYVucQ/R9eq5DpaK7vLefA+rjLj4XFAIHwEKvMnu34C8b8NSHUCKg++Qq2N97lxyL7dh1waLeWZVpdMHiIrNEIXK1CXFWimZAQHCuo0DqCyOY98UQzz3wKrF9BPSl9vqRfFEj4MIxd2FeGRtzdG6rUhmF+gyuN28Pu5qUSE1wB2t3J09Iz+g5APCGngz9HsgYiSUrKyjsD5MrF+6mJ4hqt7/sjEgoamZKXqRf78Haz0kL2LnG/ckXKtvQYRXshFykkzKmLWVKzvIHhCTIkBU6lBvQBnUeXAfEeTegfS1tZVE9GSoE9PRqYkSWT6kPj3HfnndcCzmIHvBTtIqKEkLkt2pspBMPqa4MCDa0ksD9TUaA03suFrzwZ4aWqmnQFCcifasx0mpxcEypDOJ7C2DpBbNwYNHLI/uRq2sysRfSNMkSYxO4vwwLLAlFoOgi4xbNS/SsP/QUacw6fl4sqC5Y1LYAlXrErgkNEDAA6VCqMS0KsEVx2ZrQgNb5omJ8CQAJW5DYCiUudFgDZUyzgoEi6XaHmdmGzz2RMMuyV3yz7NqtuCiYwIH8L7cMxke7WOGdv+vTcnVNgOiZbLXsipGGotAozLfnRvGpJQoyXDHPsrKozqP6J/d45QMtimaSdJwfKA1ngWayatzl8qwTu8nIwwL59soad3ss1cSx3FVVIwB2kxB1fxEGAAjKFzqUH2BCWVvPXRW8rUhDRNhNb52iYSYhdgprN0lc6PA+wYc5XgwrW1uS6Bvbi0xzZFMzudzji1DC9UDFnDNf+Pii2CwxycR3hsNCyCzMJlNAkRsltI5Chk3XAuvvhq3cNR+PsancAr7zw6kYK/0T2rENiC0cRAAz0KO0K0Y0b972zUArCschVF/itV2XjwIDBGYG4h6Q5oTjl/4eYrwhPQCXEsqw6rn2A9psPddUMuu5RoqKIzcoK0uN25vMLC90rmIUm3dv6jm6K0OZabhJ3dcXcX+o9T8yLsMoea+6XldgkKSZEUwGpIfVIjfXEiUjtv0aGNr/AqxBgFhV6pbiR1NY1SNl6nGauJrri16xscDd7vhRUzDMfCkRlK49upq9GSEaJIAKahcZmk7VOH0o84b+UtsrPwYF446hnIJgGu4OIAmZgrLYmELjAwU6e3MLaHJcNkScDZlu+JYtrOql7W8l6OpjU3gcfYD1MVhCsgQRvuM6DLDgpsFtzhLC3rUxDSe/QbZk5qLXZ3tXCIrDqyAG73ABVnJFxW26G0rn7evBykSAUTlVU+8uRiZzPJ51FN0kC38dBAt76HQoEQ8G2GkgOUrrYWcFQn4N13HWyWj1ql6hCoGL9ryZ+ZWJy4bAVqPRVKUlo7iNr5dc8JLZf+jebZK5UC5HvZyCEo66C+rdKu+NgNrtscyQqbbYpCq7d5uObCqd08HgYGMSVGWrWqpCg+eUSrAcjEIF7zq5Co2UUMUuOJucd3oUD/URaCzv+BhL5NFYUtq8svG6V/SS7x4bBJE2vYLYQ1UquRifEo7w4CHzuricAoOw9Xgo0mtgG/s0gKSBAvrGBXt5DhI0/l4Ae/7uR864pRZdHNGtyFDJlSO77Ilby0AhBbkz6X75OocRSsxK647ZA55oT5AFqKkB5hQq2oJKWD98QnpUh5gtguBENaR9pMqZbUgUCJKSS4ypsXICEN550wIOkAtLe+F3JLkLnFuloHnYcZ3ODVkYvMQB32qpftWDxOSAnW0wrJeY58Lji1SpXtVdIJyMpLxAkCKzCj3zZMVCGQWE5+kSYHH59RxrVMLwVYcNFfMPmEXANd/K4t9iLWyZ3YSMBicieol/q7rWatD+ECVCTs4uNPs6YiG19Sv254Oesp/CWTKordk0WOSTpASBAXdTuXB8sZsDtZj2QC72Fu2TQ9V9eFMGaZEpMAktVWa9plZ3ZHWA+vIZ/5t5UwpheK/yZ1sy6xAriQzfClinORSz5IgOim9w7SSKkc02he4zClqmes2tVZzrwoKGdCBasky4AFne7J/zLSG9nYpM0vWNRRCKx1CJ+VGvAjHiI73AT/UAQZZsql5tuT0Bg40Q26FWPuA+Xk+FojTzg+sRrzH7AEFwicsBIr5gvpW2Ph2yim6DYzhzZKi4WJJ+6k2Od+iteploSelov/N7yGFzN6cFruxkzERTsUKGOPw+GC1eqqb64EkQ/BYr0O/kwRLgSIOzwCB127kN5OJxvfQ74MWjHjphCBS6DVhyZ3E8Lu7Mz3bRivLyszw2i3Y10WFJkjc5cSJCHIVcQBvZ3fVZPFF6CflxgsCQAOZkRJTLlKXeSiwOmqXQEu1Dh6mWxlx4e5OoofeDHDDHYm2VsFJXHEYj4N4zmbHOB7rC41UX+mG1AqqTeyP28bLO0kTjZ68or/1aK1MZ6P6AsUPfaluXfmoAfB/3zyUkcpmCEg/FM6E3xR4CsFuWTHFMwFWGBwMxysvUkqFOzGvKvDaLCTC2ecVx9eyTz896SbI+T0q+nKSkhW1IaiyQrdJDEa31qxTBn8VgoITgdzv+A1sk+W8KpLUJLXrfI88ORHICkrKHkrvqdLDU43HEwFRbE3OcqhwEYYVfUIXvdL4cw8HoHw2WTSyEYUevU0rwsvqa35aSKgZki0dJDF8EgArpcoYsw6bDEqDlW16YA4lhqCkJy50/O3N5GbUInQtEuR23mTEEUmJ8AqB3pT2bNA6ru0EvKrNWdS7rGwY/lskOu76IBcm8lP6WysKyGUahiOXd5RGvBRu6VGWY0euzGCHlUJ181izgusd6iWJY4g41cCUxIQJIW5i27lLalcDJEKBC8RxgM31YDLmsUn58E9TxDqugZgOhU1q0ejXaIwDPW8Pp7CHmXVWPlCVLwQiPR9AVkZc4Si7hAdCH30ROA3R9h7bvC4mnruOemhyesEW8YJYU1Jo8N8J9xWSDzdVT9oLrLFwZR6HlEnlrumGkcpWEXBbhWOPBFym10wmEym89FnAzA6dYseDPqyywHqklKXnuS4GkBFkbRGqgDqoAG6jGWk6YU57KK8HYzUmAnW29FYCJ8PrwQH0GI0smlxWR96tMOKvXLZQkY9ufyDoUvEOBk34fWAPo9FU/VXTWig1QvwMOmwF1K9jV9IBqwJEVM3+hcM7krlL9yMLWKqDV96fe3lTuzksgZOlTbq09chx0ul24RE3HF7M5Gv1Ye0S8DKl/xthMD5TdZ0eYiyJEaoO25nnEQGIxzsx1D+nEG/Oink7d1dDaeE/3ZrFcqwRVEBz2loabpd/OIaGYiIfZXS/l28FmkWqVqeytGhGQgRTIENbAhL2MP0GOvAiQ/G0v3aGR3Cr9yOYPogSrKpcqS5SzOPr8LJZDtXWfPTBoyXntT6V1bcVyWhzc5+AwoxqiMmicylXQDd/TolHUERTWXJzMiJIBe/LEOJ5vxk3hVh0TWu3mBES6nPLayBtT+IJsRDk0hM9B3BNxuWcKskPtfe90oeDZXmzK6MkqQknG07z9eDIJWIMirRsh5vXZrolJje01s+Wel0qLupdxrVE9SS4weIB3yfysDx87wxdvnseE8VUJkVrbaYvIhqoKvYAIEilgL9WB+SjmQ2IY80tKNN7mRp/pTma3NvuD1loZBLbrs3m2yNX6G6rOadnmHJsMAy19JkIvdkaB87NdkGxM3zvQYaiPLFdUtQ6umcIc2GTWdg1kHV/E0yS70k8cpKH/Jed6ehk8WG0OR0kxj1nojVlPxQ00j1gpoUz+mt4xaF6I/2UBoasWwh7AVP+y8PVgkbRC53JTcwroq/TdyAzGml8NYCVw6G3B01cUXDB1I3LhuDrPoxDUYQDdsh9NzGAEFNWp6Uq43w5KZY0jel5piPz60fsSjxPxRT1z1XAAVuZaopwkYedtZsDWgUR2YPxgEB44jgZ2BYxub2fbyUGE033YHJSS9+bvWho2EywZDE3tiadDmheHATJ7pWU22OqdlbDUj8Ygat2mzOmIh1QES0I5PFN1g9FhDOxeyp3tIJtubXGtfHGVnB45td5RiS9h2JJ7CCW5Q1wvCjUjS7yDsiJFDC2+0vF8Ro+xHBjgmx2XxvWdQbFqz3/ibGkb1STntFqbZtkHj5Fc4DZy2SE4qCg5uyCAmI9MI6fCsJvfe8tgrDy5OS6/xRKZNU1xKm3UqJ4l2IfpCd8VxnyCdb4lMihcah/rHGCuQ4qfHlhKmLKhwCVOdWtkRtzbOOk2eod3SawfXKuIwDJ30kcENj7r5egnho6v1Z8KCK40g3FBjY2SYEKNARi5SKarswh7GDOzzCBkgCCPZOmB5uxiSyrXtuFxfcRGzNcAhPlF3xpFKW4fqhYGsTca5IqatmDLDg0BQp2JyfVFL9Y/fD3GKGkDBxRV7LPogIbmwmx+3V/EpGcyJAc87ixtuDUcrDszs0I9xgzi/hRhuz6LRTBP+gRVGbgYoRYg+a3RCj/SbqAcMrCUjuPqjcdcaYM0iphV718kYOaMjCp6JrHpgooZPdLphkoYnWxQ3BtQAnLWTwRozcezN+WA3QCbg+pFWUSjKxih1blDhNfVIKln/FyEcq/fu8wX3syIPxRZvTH1/QpxcLR+HSY+07GKze3CfZGsdRzyvTb8ypLsllrfUzmhLAtJwtJnjDe/2JXImPhykmHqciUWCV1l/MKdZtmpB3iKHl/mgj5Azd7x1BizGivrvvYtykgMLIxym/+xUoPa0ygDpMm4K6wXagOHCP6tP/ad56z1pBAlkhRdTDKSIhOHfQe1oHx6jmMYj9o0ZFr8Iy7uwvsLNlqWVVTTskg9sdgiHUOuMMYG0p2xnoEMTHCn1CDPZpBI74JIDzaJq1wypseziRkf9UKoqx617YadWdRPxk5LfIKW0vP075kJHaFdD/C0B35sU5iNAZPrd5GXsMrCVz+hy1qVgb5XVy5A8f3FLhTBrX+bRciSi2agA1MYVhZki2QVciT48wt05aFy5LZgOpIZiWGH+A8GkWWCNsmx23FqqTcmf4KczIJ5GHyg/ATQtiGflcL4DqMRmZNs0F1jNmGENgPDweYD/a1gkpO9RUw4OwFbRs4lWHY5SN++DfWF9tpEUt5fxL1BVuuFtrjEnVX4rsIJvxUgkI30C3Y7v4g1aQ+HB1DLIGcaYL8rL31RFMEL6xG5PhpgMaG5J/1ggArES0soL7yCfI+CcX63K0X2nHpges019nZwbfQZiZhhvtuZQbXJYh5WdKocrn0GTvqUCilzemvIZSfbRHRx4qM2+EzYxXAA1iN7mshDfpASMQAv0NBHYNNhgjaoRMTsrBies4hBnRDD4mRsGO0BodUSSxEFKPVGxmS1vh2QCED+cYrbcP0gjir8qJNwPaOl59EAwOx1cvw8Mg7JtdhA4KjF0yBZfqCi1cYoJTVYWKxSIjw9tAnQIIJKP4QZTJxIN4zruV8af1gGoQ+6ruR1GIVWSuOBlzgmGbhAyVqM9H/iOoCiLvyoFH3IMuXcRElZIpDsCcBXEORtxbttSHNkmbm6nYo5ftIamwPM8opJO3OkAGTJPGe44MlKpa4Iid7Yno/+5NlIlmvtey/4foVgnYcJqZmf7c2h8vrSMgJpohrRTl/WM7VJbsM49oYyLuv1VPrlUm4tJjIx6bFlNEc1moQwS4zzAA4paGLpfZGl5hdzm8Ahp5cmNA/2XJ3TEuJHkew1Jr7mwgxQuhOu2ZEbxphgc+YTRgYdJ91PoWAJHspNpvRFg7iBTEQdohSmLjUmFlk4VoRobzpi/idXQ7L6atCgBU3W8IUnHg2XOD7bxcjGpB3iMmnRSliqVic9olkrl1o4AI6dB6WnAACyPBSJ7jzlQ/TLA5UMg8h1VfvU03rpMbL8Phd2KadQ1aWE9/mCcBmbJNkRY1UlakZ90HFzY8Yz1xe9SSqw3s/1wVGR5InVs4iwdkq8BpnfILPueVo1h6M8lbsMYcV1k5AqelTEHPtEFq2FJN8GkvAR2RFS6NxZ+qz3lHZMW6RHhsu6o0lx7UoBMBRTIRF3FzMdshHkz49mIWBz86Me5uQoSwVpt1IKU2mNaG/MWt31eT3FTNYkP/aGRq5r47NiZRAsETtB/Rc4VbDnUbf2mUypEXuI0OXNR0L0PHpOSdYl2Swy/q+F3vC6uME4P4t7pPc91HhtEHEhLed+bOFFHytmCFYwK7F+M0PlRul/rYP989ImGlQGKV+ThBKuFTFtSKeB6Aecmt5QynstEsDc/ICZ467NwjvXnkWAVEyplYK2Mmbr8djvwu+wyOZlZHHc8rQlh/x+ljXyusYk3pQXkVXnnocYFz9Fn5CV9SgXpDeQHznQA9G9Oim5aeSxQpLV1ni4OTKWUj6sE51NH4V+Aa43aVF+UHXVQCUUY+d5097HM0OPr7Ehc06p4Ue0ivNRMWrgRcHFFvFfyzsLcgWAsWI1cG2gANIxzN3U5Cn/x3WAJPkZa96Ty9JzxB4pO0Fa2Rvj4gNIyXv6BQBu2SWjwpRnlVG0gtL4a97FOnYQgyUz0aG2D0oD5tM3Y0oor4nlGJ9M5Q8h4iKUg+99ItlDmZ4kpouP0gvIGzwzZb02oG7L47CkOPoAblkVRBC3VTFyHIHSs8xYjBZZsd13NGurWg86HS/K3mPChmADq6zEFJNLaAG301mFh7zeUGdXDxPh2R6kjH1iZ5XUhSbbDzltFTemLCOUBq3SsSCXPASAsJbjjKQh9+O16Kys8careialjdwYr9NY0Yj2YGejYnYnxHdfii9zIOrSxgjNSjoo4+kBOUbxHTAeFoQPmdV27bpkYsqxF32Rs5RIRg4fxWqwvarSUOFJ1wzB8cUuiTbkg5K3mwPLhIqE5PFNpeTVjgtAD7EyBfj5QDzDFmxLVpBz3Fv0yX5X+wqXlL6KzqTBZK0QvgY5uKSh2rq2UKWdNxR3La8hAUSsN2xL8nREy1wPuTIC/ta+9a4qAfEIRG59FI3ybOGE3+V55LLFb8a7V/K8LGcY6pdlmDGH2W0FJvovcL0030cBXYCPW9vqBWvzRCByuSnM47MjFKOatDq0MeKQ232M5rlE4VQMuonjidEidchyUPLKYlVkaLVaRgQ4tz7yFy85LoGuVplt0oZuqHGgxIr+Y+YIY/BVxIJkIepjSJOG61hzRGu+o+yNMEZ5NHfBIaiEMQytpq+MQaH3XV+6SrOVKwZ66eE32wtMmBmaJrxtflZmHAK79ShQN1hiVuu+SIbyLnVfIlg+/gO1BR7sUfsBIh+h+ztwu2+9iaAVP5fc9jbG15fBHo6OReOwd7Y1IbTbHpkAM+10iw5T5bANM7fM1w7QBipbrnEXNKdB8F3vsnmIy2yNnjnHvogqby3PG4ayDeBkIW5IUS5F29wgtLcWPrHtEJipAKLCKK0ANEWZ7wSXbpply1P2rPkHUdrKcY3cMw1duxcrM4aIqPFhscpqT9RHEFpx0PODzgLPuARI2DCZIllkXI/8bxbKUThM5z5SHcsMSCsB+D34hByZ0wQZXKN4EoHdbS/DZ4emyxrNkE/1ZbEmgnuEFT521qqMcVZIzPuknTyEdx+Kd36LeFITDYqtGdIdzkfkMRt4rzWOUUp2XfrTWn0RdARKRrI7vLTlZQs9uKtcuH4dsGzLQ+nNLks7ou1cgSEqLviUWa9XrZP0oTOyNnQAcj4NA1qdyYXJaeN6MObDXW0dSrc2b7Yymb5Szo1UIAFnCN8cWeBVuixyf7gOpQUG8p6nwW4TITwFkB6FbbDsgSNlJWXzLDv0J17mCowJMIKQ103Qagq/ZOkYDur90C1g2KsKzWlD8HUKzYd8t+ihK2ChJf6yEkNkiZ4CiR6yAmHLGaFge8DzjnZ9kgNnUvXy1qwmA514TEYpH4xq4MHdFAOwVIJZMIEd9VCAQnHBC0vu95bkynO40pvL7EjOL3Y1sjg9v5VHQ1PxTVmJ6lawZHcBa+2Z+EQRsrcACKQ//TG4GR1f0RvMVYA17ThBdFn7WMiP4YzNH1hksUNq+aj2gjKiUYzlcttK/O2eCVzUhgIYBKB07Ze2duwnDhIHwVLIqaig1GTflFfARYAPOjRMUW3oTLk390W2pR8FMVkLwkhuJ8VGnziktSZyYT8nzlxf9HoJ2rvuVKoJk/knOhJS39uM0Kb0uzI7NOA+0RasdDaUikEix4hrhw8zpF2055gH9EjwrUgFUccDyApBd+wKQ59cAAvjefsP6QnIyF3AsaqEU5X1Ch6jJoFGSUNeiUxm3gQikwP991ECcwwMbtV0BOM6Bs5kwCycjOkPoJ8jaYI6kJc3SeGIS+eKXrgk8ETI5lRMYaYEdeaZ4xwUFlvJPJtIHPEEyVGXT1S8OkhIVyqRZaK0DwYHdRjFTxYdKhgW3KtZidyHKy8CatEIxGWfFFIsaYceARpG4Ic2dUM1MQ2winmBZEvccXLAhBka3EjXAEDd4ykY0gX3kzB5HVOQc3T77I4EuV13rNJM1nuqa482TRYwtUtIUWLYCZkIPn4BitvJ1oUSZH2G3u4DXDRWgxfN0sIY4MEcDDYxzNcX9To96C4vw2Yv0XS/eGV1+SJLoAH8lt5locebeN5L3ZO0RGETrh1XNcoIxoT2eiCir9QpMgCXJ6LOz3Y18E4ekTGj2gYN7tu4ufai4EO35HmUfYAgPFK/ihBNeKQEtK/fe0xTd0bJfJYoTkYwm7Q6zygR2ssZpsZjnga37MwNkqXx6VzxHiMtBRmpuWVJjZhhJiOE7RF4AmAGaDTbMD55Or/+CMQbpkaciBqVw7VTwQevGJji2LjsTSGhHu+YIJTkj7NJ4kD9ibCs+apaMOocdHBLOGwfypfNN82FTYD5+tfZAfwoyyJiZKdjanV3EfptkEzDOHBg7Vy2Km6JfD2u491hUy4hpFwl/NVbbgS5Zh5AMoAN84t9bx2stif/N1PchUtd1YpTVg0UOMVAOUH/vSNLzW2TSYa6JK69Qz5g6Br3XpUog4WjBSBDI1QEypBiahkCuPIFBs8zePaUgePA5gygyUlVG6sv6HriAb0BHUnams13uxoZlXDsMvkpoS+CJSdLWioqi5ADA4oHImAAugycmFgnfvh64sfxY7wJNEoayI5xTNznDKMMU0PZSxKYcZkOmN45t91wUbOeb2ZeGXhPHBdxExJNkbQvB1zMHrMM15oEM8gJ1xousyWQmYGcNw+N6mXQNtFo3Zx54P2z1eoGndggpPMqB9yAm3XgaOPzkBwctYDB6TjtdQtZIAsRjlp1c/SvM+K2oSuciBESoPgu3Vz3+VkZFMqLcD22rdMALi4KVBV2ZdswNUCJEu6nUDhdatLCy4n+WL5e5Er5ICwrVlQZ287+qw6H7h7iPr6YJ0q/jK/jcSiDTibfYmyHE7GadTFjdmIGDWRUQhkwsrGmE2WRaQjqvqjLdyUF27zEIBQNIKkukD2h/wgPFjPqBDAMyvS4DqjzblEVVamfbyR0h85D5QEO3HptqDPLcVyJvC1fj6hhBGR5xbhynsTm80qJgTXHhgYYOUgWKrbPMrG6+Qu2IvqpUiztmgKDKhYbJsVN9ez52a5IJibmt406LLagPMYqsyTbh4CGPpcKWHQ9U3SB2bTmMMJbxZcRjnlOTzbDJfRwU4Ozz8ByQDuRsnnW2IWaaVCbB/jp+mDBIfS7KAv+wB9Y2s9jDNDQfjYjgVJkvevzeDM+CqLokouodU4I6C3qBP0HYCALA4YblF/2AkjsLNv+JmuDXSpKyLxNH0WRMak9IWhhLJWPPuxyRAlg3mdA73icycjnu6TDXRM1VT/ULsh0Z55tSqngzqXD4C1cLy3zi8wthnDKjvk2NKcXxxrXtZUxr655TedOdCe4HuxbnAJMqteTksVYSUvgKmuYoPpJ5yLXHmzXBeJ+uP6oi22ZS4skvMtCU1IZUZP3GNAHHhGPQymmfoGpTCk9N+3vZYWdbTpatJqLlFRURjlxv8V3xMVSZw6yXCk90JeYvuCXPLSWbdm6PPSiOt5eBq4SkeMY3GV3UYH43blej+gKIwXukpB6ldG4ZQwkQN0iTdp1HBJ66olWLnQ+ShdxxTcbjfsgiT1m6ksIuadFBZ1fxONsEPZ6A+2M+nl7xqpuWiaBiVklX1rAaZtqkxL6P/1FGA1vUqmR8njcOyk1lqiA9YY6qXM8+jT3WpBOrfskb5+GNO/Dg+VpzjIkgDcXzZdi7xGIOfQ66LV+ebQTEtO2xVm0sXA9GgSumQSTD8T6Ii2ZWYpxvNHrs100sFbKG5eRwxEjVOiVooshohYkjnRagNzDpLJemgJeJkrKcdmkYL7MpmI6n7ec4M73Mb4WdCjkVdDYoUxERVq0/XG9IaESwOB7miq8p/UoGDKH6iXT6nnkeapcs1nLZga7v3SaGPGZpNyDW+U9Ay3tDkMQCxAu+EcLFa9TnREAT3M50TUGr3cJ6ymu7S2cK0i9cNRhCgfMz3bHVK5GHvlnbHSEVHz1clJC2kAttWMYCqMuPTuR3HvVST+UevMx7vFDh2QJimWlk6b7dRXeiYujLBWQ61BzF+t0Fu+yLZ8hhCgqzkIk/mZlrT5dgwWrEJ4cQxkwEG17glDlHUDgBwvDnZ+4AKVN2DPjKugIsGdCMoUxQL3wMBa1PQAELi/CMXkmjWtBkYdPL7FGWXnug4TC7HZAL7+muA3NobLzsGfIGCSnrhbR7TG+oVwcGyDzyBlmPEy5M+hncb2Nm+jc2zcRY5AlxGylM0LwmbHqPBQCcwNcLHUnfwKkncqpbsO7UmN0nDx0hkoUUkBXK13N6/FFP1GMtnsZUpLYNyS/Tnn9SDU4056PTNe/FMTmF3t3hbf6LsXDGKu7vNBcX1ulasxTAQ2LnlsnN4DQidbpMgCGGm95jGDyGHpkI1FZO5kMkUUYhKQRQ+O4xI0TYRp2AP+WXTtmEmeNa9WqZVVrx/TkubTnIQMcwKJvVgIhFUyL6GcxCT+xlJpeIIsXui/hMVsYuL/OsCbvmZGs16v0rqt7pXxeMml2fJzQIjGI7pqmhiw0XjHfqQxO0XqPUHyt+6CS0ZQMQjW6Say6xaei3erip4+JyojOglokcEP6rEWQZpNAhrp6CqcB/5XMtQPvmGoJCoAKASvGdL0OiOXMfkEaCx7IdQzshAbaA4nFQCsqFqgGIwa1qRmwvm9433HGuy6pZ68UEZtt81KwwhIyrISVeIRzDPtMqQTUb32JWKaas+LDsErPgsfoXCK1yvyGHCYfJmZTZK8gyxyTpTQEO8QEQBTzpfyW8oA4GBgGjYcLHLsibyRmm/+hzkPLyqAt9zDDv1W9DDyaGv26wl2K4JwLSkgdPWlcuw4Jazx40zMPSe4c3YEBrJFp+Z0eIxpJHb6wba4IGLn6KCMzPJIm/VTnDZxSYX4Lqx0gHUOkm5irsm4QOr3tOLzxkqV3AgAkpjfaM49BS/cw+uuLuTeywmlI9D5WvP2QR7zK6xJHbZGMqYO8gH1CLil1o+YMUW1cb462iJBTinDvnLdAfgjQzJoA6yvI6TdkUyKbmAbi91CkwLM0Git1URa33DbEFDx4MJi8iRJfwOhBlcQ3sjDtCLkbUiBB4vuFvb4HLwkN7sJT4RHqog7h/SCkibXIqLSnrrVT7TpFyw92FJKnfd++oPdAtTN/Otoim1pngkJv2yW/B/LHe205qwvvXo+SOnRZIcXRoarctSZpApq31YM4IhryIl045ed36EdRO3D1o+IyPtubaqy9/uLTr2EJNx2/7XVYwTtBZwlK7L7AskSeYrAZFGZwvUyFHb59iTkzwmEr1i2EUx4jdymAp7SGoWJbIQK6vN29ysS10Yq5cuaateCkgYQ3wM8bFBUY4QdFjggk13qFnUxL3wOXQXRRE7SaBLybEYPQTGGVxMjqJuHToAIsSd5kZ2BrXubc1+kYRMpwIhEK+F2fqPMZ8nZE181Eu/SscR3kawHdWvA0iR2+1WvvB0lvhSuthflRCcrmzgS60JrtD3MEnOmB8NAViR3WrsdjEBLXPP3gY7mCUNBktFAs7Y9aMXPwUxRChnJe15ZpYrJv/yKbbCMsTDlv+PYEdd7+OBN2TpgR8lShyCNhJiZ0D7opUGeoSjQgA+TwP+CvcB3cwvDmuYjGS96y9VWQ8MAXcWxJOwWJQ8EMxU1ZIQHN29tT8TGNmoRKWDhvWJAtgzRqEaVyDJemfRMYQqxHoCXgeXs/ZJijF7Bq8z3J2pieVMxdFgCt65eBL9nSyoEp4OuFR5cGYVBIR/hdiUO0dnq5g5b5WT9MDEPAtYtfuUurZQVi3Qsna4d7pjFgGsNmQdKhqEVK7aOUkd1eaUmTzKqL4ju2QszQSRTqDfw/4N7cLItyofjB9ah5wyC7BVaUOu3OluIo6YIO5OweX1/sE0zc2ntRah9l+JVc9qwjCK1706HigIGaIcKW+QqyhZQMhbpTdiet76ljcm3GYiEG4lQX6LnmgJHlCBbyFNfS+7FABeEPQ8wYVbQuZbhtK4yiPM4SIjRTWA+1DHCvuLmK8tkzEHv4seUR1mAsbwM/kDuYMOuRSrLcZCyjIqBuszGC6KX/P8Y4KsiymtZjt03k2VgeBXcOJiJwrhtWMtOuz+5YdBl+T2C3qg+6768XzFBfC1Mjm8kJEE2S4XSGVK/feQITVLuYqzketISEsgnZ5gBN7Aa0j4f2x94ezyB/nhG8TR0FdJUVSFIrcadQxkRFTKxi0jxPALUVwEwPh69XeS2Fv2kmqTRE0sKRZgCHnX1sYXGt9Swjqws8g1zdIgJLutoNTxY13IoIbNKB5mexUGJ0/ONh4CZGXZbF13UYpoL0IgkMMErEbF1McHJjWI88CdDoHTq9z8l5EaGKmK12x++388kYBMtkambG5RSdopPgDOF6Hqrhdjh7aknba6OkgtJKn4SZ64vdLDw59oVD6kcTRVPI7jTFThYgEwZ+Cab6ZoY0Qq/3gE0Dqy/7x7BlNhTzXa7mVR9pcj5AnR5CzxhUXqF5EnkgtF2UHrx/51h3BS8AIPEugszzKEeADoI8S+vNz2ZFIHoHqvcwm8+NmdrX/hF4xnsEu0BRkpNDOZeDCYgfejzpYoIm4EfCS9ElT36CE1GoVCvcpg9GzCXHdFjKPjEQFzj+upkc1GLDUZFqYJwWfqIFJ7aPzciSQ+0fTX6AQ8B7hmmVDpHcJK69RodgUBm13IUv3KW2KPLkQIK8EuP4fcCo+WweZ+I634PFySNdKQshuoaXbIiJxjoHdYLExmdxW5nnZxxUV/sQvlL9DVkosMLg5IO6g930eQxTIP/bshXtJM/4yeFFQjOsVlFuYYtAF4ooVlbd8Uw15JHhAyGmFmPt8C1EmyK2eVXjuyq6NCv5wyOrJs7l+iKeYWO9mcdJZHhZVqm3RlWH33obXPsDy547iyxxJPmUmc4srofccqitmuGlPPHpeVakx1qXNs31xRy3SBYlvs1cy2NakBCKUE2VDSxNeT7myUH3B1Umro6HstODMqR6o386EGMAqOnbCq22W8VlpRSdH7CHUE1JH/o2Ssly98TAQygfnvF0FXYeZ9diNUpeIQN6S2kSSoRo9bXKU3DWW8Xc9vgyoHrWDKpFTJlh5rruGjAiMyVMq89o7fiE/mo15xKavTGdiXswcYKiW2UdLVwbSQCaPeQtoTY0hoF0iodVbw7TkXEdjMBgxWfZ8gcO2crirMW6xwwVCHwllvD0OdGb3eMN6PkO6d5HB9Vn3UmZvCJLJUkd0oxRc51DDabT+YgasI/mwVbGXO3M4CGkbVrIVXqpZIvMFEo5JizFzKMJvXfgK+6npTGo/mUfDYUViUkrctLQrsVOqSkPBI3RBYyuocdOaZUZAISsBdeZicl7Y1WAu4ohvTUNFHjABs2yyfXF3GhybNZ25AhQ20nUELtot26YXzJCrKRPmYYf6pfg8Mqh6hlY33RSrOK7EpObtQHYVC/D0EjFeCjy7zX4oBrJUBnP6X0uNeduQonDVen7TRgFpsQ1SPP6Yp8hswhfhVW4DSnlBp1I27LR702+cDLqmT4BwAMK6rtJJ5PE1xGnVafLvDiKVSnyKQOX+jgMDWk+iMBVu2cMrk/72JMwC0JVJFJpH3wismC/wK7XF7FKYRX8swAyo+1F8yoqpPIMuQWmLg5lTe8gfww+VM373JNMZh/Xm7doyDhXV7zIKGfrSuThnUZvdX4RN9hY2eZMeGFVMSEQmQ/wpdV0rKgw+wnhnV+UGYFib9qhdWHqEcvSKw/+vdtyZi/GXLivWX2DIwrgrMtxB5TbfHAd7FWaxA/D486KPr5RTsCorpCtx4StoUXXbC8iZ7Il2b8BN7ig7TXuTXF6dmBkZ+AEfFBkUH2jKIEjmnWvgQUKD6rZLJ0uErOqkeabqGDhjBOSPqz3wZIV2+6Efm+OJ6kD1UvKvRyeqJiQ0VtB+whgosCjanxnCQf1RMmM5GOTOnClWdEwUv1IPKY6BImSIdYuJVvCQst5CFGth5iZ6LSTIaPBFMSPItFp/UmKWmK/jMn9RaxSmJLzrFjoB4lOnDijWZjUO+vQ76HsrQBZ4BGQ7YlZBvjmXQzcjZRwRffh9qrpkiuSFZnKcIaE1UYFKviDHwBWNz+mT4P25ddc+FIU68tw9lCb8IGn8wKiFHg2tr7PzuSNN4h3mdVRlTx5hRU2MzEwXhzy5pH2CwJByBm5LQYtjuVt9iBizJZbhtqHF9I6xZ0QQ0bKy+wACgacafNAM6PsEjEzeDBwecUrsX3j2llLF5V7IPYgfV5l/YBeJ65jDXYoi6vF6qv57IxJDjzSgGWgasOsA7lcZMnTR348p71OqbovoF20UgqBxd9we9CHIQdLAeAk7JoXBzxH2sLMoRUR3FLylah8O4UuZBhM7rZA5W5o7e2NrII2UH6/RUOZqQtTe+tMi7w+sKw1pYEONqBD/1nyyjK5FlwvSpfcy3XdVDCcNHFboYt+tt7sxPuLWLUy1Gs/DFxEyOuRqkZ83ioI5PHql0fbIWYHcS6MtNM+14axmw+4qTK7Bfc8Qbce6D5y0mGMYWKeehxAhyGlJG6uM4/65ZEOlRFVN4xKXcvOQ42Y3Fy4Hz9n/WCI6LZ9oONbH+cQDEY708ruWxU6MYbg5Vuj48AzizBsAZNxMiIpWbIAwLe+ECEHXJIpHiKYqcKYbogj9JcS60iwGcUA5NK9ghBDagPXWZUj/tCckrRCxIMuKzglHl5+UNrnF7EU2ZwanzoVEyxmGiRyyWjJ0C1WltT2nofgURKoBVUg7IbrjXztxvBXVTqQspMbvRQaUdBB9x65WW1+lyzOtIVzPZZl5gRfkb1LFVHL0UseKgQf2p+M6AAfY4RRZrnCCibPNT0/qFYC+pC2RUX9GUydiraS42UbQGReGjr8y1qfGmt5US7vPLeozogZLwE9XYCSveNaacdwum1YDV4LrjfrmhB4KmR/PZjWNWcCszmmBMP1WYU46PM9o3tnepGXiXXdTNGQNgBzKdEzaIGplmQmKfXdbxNyvu1FoCqz5ZESR2IDGb2V1DDODKKFftT28Ce0bf8wzuWFpTQr7wqDLgpBfqtcRLRkAJKDCH1m9a/idCsYShvtaHfGajq4YrL5EwwjhgDR0IiqLDjY7bsFjBTj5zd137F3uIgoNOrK9mBlVS24hr5JBAreMRijj46w3EEtYfrZGbA9PJfMPpoLW3XtFtEA4Io2aEd9n9w9D6uUhxLCHmfQbx6ayV4LiaoIcgNGQFysorA2AsjoXD+kHK1wZfcPcoC2ABJCS/gujYoWaewQX6FtG5lY4HIKOw8Spzq313oNUmMBcjbjHJtBBEJegjmDibOc6vMAgaxH27hn99zrDqPHfvnJovQitxZ7yoNVzgsWnv0HuVa1IlmdAQO29dgLDXiVSfOBU7fijgoCNOIqTJxv4PHJVaDf2x/lw8diasS2NuT7rN/omITJWmeZlYLcKYQk25H7S5Pbz+Oo2/jCJ9sSN4WuLK6GUSkIXUNqbmdrYD4IrkOVG0xTVXlbHvLWLxeKYJ5CR9wfz8FGRg7cUJD2rUfuX7/B6OJOKi9y8MUGSizeuaHlQdsFsY0b2bmyOIDM95dqsBHuKVJLI+uwtdfeUMRJ0FEMnx5B8ZH3CIb549SCUXAwObIgG8SLtSi0MVHxRse7YpwqujTZ67I+5jT1Vwwf99iCKtUK/LgprThap7IQGV5nGfg2sVrl2XAH8dvO0bWyp0qYcpMHczzlkyON+dnuzcZ042f4ENe+xQSt4j8KdmnPRM/IcyJ4gMMJV0/ZgDMOCrp2/bH/PUZH+mzF65RGZbbF2w6R2NkAv77cDxUS9rgO5VOeOaH2S1TK/lbahn6QtdEjJHEj4P+tKn2gAgV+9zgxckiMNqMSJHGQhsIE9gtmbSL2L0OaRJb2yUN/+Hp8h30bPsHc+ZWW70mVqwM4m8IYhFsSVN/UqlCufR+KHWHRVk21aSUCPQimeQjcjyzu+iwWS6zO/dJX4x2jj/1C1SSbGnfMGGU5b1T8ArZ1UjW4Qh6uuJfZKH4o3C6gmRqFnbdGXmCgYAB6qGK6Yo67ll1xGO780uW+5hCKXl6KK/+3MJQKGiFEf+Hx0dKjqL3samGF59geVX8vm+NNrpoPoOiVP6bIMSpEo5noFIGus26xuIbpuW99FE7oBMy8Kjtuwv/gQ4ZEbOiFKZO+Aea6TY0vlC3hOrA1D/rGAkNvWg2B3PHA+LjRLq0U5xyW8w4O9I3OGCYu+qauNFHuiFqNgbLkyP0UtnLXF2lagQPA9RYc8ytdg29E/rgVdbMvYXCZHY+NBp2ymQXp+Piwuas0IIOrtR6c9sJ6dEmIjrvMAcr6HBb7Ia2xjiRlEnwdUw3YOAGqlXSqG5osWrS+DTlch5YK1Hb9JtpMJuGD61yGt5JZclBt3HOMxFVjMGAgbNwoZKTbVAbHk8Hx+Y0Phw1axQSIKA9hMvY0JMqHeaY5d+AKDlI+jAwBUwrXuWrEWsOmcFyjPhQyBXcus9dnrdA6GlfSaUD819c/2pwajxm9mqMZbRBeAAXDxNEyBgg6lnzbD2Ljo/Vo0G+y9iXYpfpUTQ8VCB7ipJBehQZFZd4orI09GmRr/KOW1RgZypWcewJF/kjlF/1wewltrOUKIzXZvkdz/umY4XoucWzv038egbydES4ex5MpEQXqWZJGU0D1Cv6hBQ/7rViOvX0UbFIRMCK0gDDQGPm4h2IhhaySrl2ApQwv8JqppdlVySGLDlK1LSuMw4ZkR6V9G3hgfa077BwzvcuTQjB4LUk0PBRVoZgsnH4oppuqcH2xq2EKQTpoOnN5XRQ41fxcwzWmpxgY6hX9ALtAsK/uU1mgbY/rjDWPo1P950MePgsMt8Wh7Inb0xhxjgOZgTDbuqiF/n5cu1UdKupinl5qWmVNz9PpPAkJ87xcHLpcYdBpxHYhaxNOiRQH4Jpnn/TMBm8NOG1OFlxN0BChu+oYrOltUZNOKCZ+HnJ97vupNAPoKRG66Rq8QwscoRtuCmei9MSoTLteZwLAgZUejBSp63qaiEaZRpRKUfyiD3z2PFS5VZoRHQsbvSXBZXaMJVNVSDMoKk1pQEchVYYfLJhzEzfnRPacryPSNOryV3Baos5UT7rvmN0eMAgDzeCCmdmyeIKYAddbQXoMY7txYP2xBg7ZkIAssUfA6UFOzvXgfSOEIuJZ5ZVLNWomd/PyABrsRA4ILcpoUENImUlKWd4gZkakZ87vgNVLSnOWJ9DAJkKiXAV1qJgTC3cF7+jkdxmy0fK4ztpxbSCFZcAt0GDhgt3cr7B0DHSmgCbgIBRoXWz9d7LnH1xv8fYsL95GtOy9vqVkgPPngCmNnMM0yuR4sLpZtbKc8dELwth0CWHiho1ksxn8oOdIZmp0z892vfbh6w8a1Ja1kJvWutkWzlBwRKedxz5SqFCdNqm05fl6FLFtsy+u6GZVBuO2cONobWZmZNaxrdAZqdtBoVSMr/dukSlzoECh0AeGidWRdGAWWybrRxu/1uQsAhyCpriex6I3FvYQp0ZxzgwQFfOtuZqTuZrjQ/TazKIakfZ0avRTg9YhDUqy36b/DJ8ETr/yRF3vwfCp216iEAHX+YwyxnYdlqwsuqUqVYBO68C9UlRZSzmU4aGEW9LLeO04ujdppyxusyRW9SigxfjhWeXYv41s/dbkxFgmvh7fJDfJV2Lculau0I+3FHhk9I3qEFrwo4EtXiWGJ5dTHMeYuGi4J960cWUcTsFGGCxQVBwBpld7pnK+8lKL4xdpT0dRp8OEBCknHpBKCZZjdwK9H5tsAFGc2pvYAhLzVRhvYirjvWFvY5sht9w83S1ThslTu696np2n9J7FjFBF6apXLMSanIVzNRCX6iyNz89roex48swb26RMGL9qo6jmtCHtAz3JVNMeWeWyV2RzGgmL34BrL06hSFSzgP0ojQwL8YX2BqqbCZixDGh9UVKMaPjg2lktLAzqdLmvdql6ZYb+VAwyopfSyPVj4iS0AaToDqCtJR9TpzFp1lfZ0Cg5SZPW9FPsGDkCIJOLrFHIhWJfzDNM/FsOIVWaoZkxLdm/0CFaLGxSAhJDzhApYDhkUWQBcL11h+OPocU4rYsMrk6dFMoA3CC3NaYnUeKx1d6AMs6PY+KGGI+YKsa5/k2R2JhmhVWqhzjV+CxeI5mXXA+2bGA2zUmo8pFa5E1GHQONbeBDeIRhB2BUGjTM/MvtlCSWiRC9OvuK+Vl1hJrIzwDuxrNc5mf72jqr3R863mxPTHiqZ9nb4ZbJjZnE1bHwto+h8zws9cYAIC6v9WAeyyiEhaCcvQ0kXl4oZx5XNijQYNKmeip/Fc+9uzNBcDQl9RBPOdrahE2B7pTJ+bHRGwxQOCffcnD1JfCY7OOirLqgwCFFCgzdRGghZYbpSoMMNT/qJxvZo+2sE16pqDpUlhZtG0zFcRImkHoGaDu0MqtZjIxMSQ+wF4YtiZmFTlYWkunR5lEYjnm4g+zQVdyqJvTn4zoOumSVEyP8n7NIFJtuIlAQCblq9MXb4FxCvFNlimTBS3mlW3I9Q3QtZKvEyPnRb2UlxEb/ABYCwVmxL68yM+AFh8rgmrDY5bEIU2ZF/5GR5uHdr8/2gTY03p/Qi6Mc7OMq6y1VgG2GE51Apme0AZVKFbNPTKBUyMYMaeAHLE8d7/DyDUmmEFnXSWm9oQ5aOg9WYixY1BLS6Efw9VZ6bouh16MMr5tpJviMgn5iPYcxjCuUoZWztgwDqf3DvBosZtUInHh/tpbYuJbYZjd4fNa3h2FZewAz5mgudpLS8QsaWo8oqdExiLENpeUGKJ0ZRwF1Fr52T9SOFFyZ55ryfSZ/Tv9JgFA18oXWuV6ql0vMY3ypQd1qUTedW7B4jHFBV41BNBXhGZgZoDirhJ78L663LixXz8R4KkX8NZwMzwKToU6t8fnFnL1aPnwdWxRIjZDlyghNJio7xLUVSEkXViNADOpLDPVQpAF+8U0aeIzoTiZJSl53Ei1bHlpt6Hi5ITTbMKM42U0E7lZ7qZr4vVjD+aDOeA3unbwd7jKC1QPUACOZvcxjKkB4LzITrEMp0adcDNOD3mWDJvEESrxUyF/6wCVq85TpyOF6s+RhQ79z8fb2VwfOImW85I+iC+FbPh2qbk4mGZQ0liEa/KDh4Wb6qycRPGWHvkDldjqQ+4tYLnB2ee6xseSf2UTRibqmIUAHXzDWJGC0A/fafOjdjh2EljpfpzQKr7Hpm3PWnOtqCWY61E8vLNJTAUYJ0v1juHA7Eaaw0uK5NVH/nmu4n/70j99+++XvvzMjZwAHA+W8ZGfJPTo1N6XQ34zrpaMwogwzb1AMO9j0RClZYvAgXDKFkz2WU9ekMbthq7ENtqlvEntanIreTIbBVBekMmUgT3uIlrFYMJqg7ZlTuoV81TT0rOojG7quY/Ze/4CwGKAs2VirRzxSDEs/0qRGbVY0myHGeYds+9gbqPaCno7IHs3mBALaxgJBjQzXsfLN+P2w6HVReI67/CzA30MFz0N3CMSAkFo7gKS6Qyfg9DzjBCnLzdIlOWJfMkZmDITK0+1pycwtdvUC6Uzieqb0Yfi7bNMwyv0KFmf2JBtRhYvqiaeh48mSediHCRcICPcXbXI/B8Yq4Ugvc0UTDdQ+sQp9jPXNaGlK2UiKJz+4Hm13nORaCbTR01TV8205pwusdH3WTzYx5PmhfDGI0lYPXcBB7haYALlj6hVgRGh+oXoZLv26dZOZxUOPqdRUUrDyNepEKnYNEOB4pHQScfA7Zp2mLfmGjHB/Us3yUyvjLrHfx3ITA8sY4pjnfK/52S5VWQ7rmXvOXGVFA+8mulLvsLs02N+sIg7pIxOJ07MtQ0j4AB70P4yIMOYsC9SSnTNaeN4BQrqCjgWFI/67P00yOf0RVXMJdgk7Fz+b8uCNkujMEWIJMEYPNShnbHIIlbwArjfugPshhzjp3rfhDjXo7mK8PfCZHVPV3S4DhJEN1T0GNfMsippw7yKima9xyYMARn/Lg8wv96GA4CyuNx7oNapNBeZF9SwMQaqwVjmsG7rDZXSH7E1G1MtOodRUHG0CfO6lhv+WXyVQsVDOyFxfQLtrg0dWlzAz5NmYD+XRO8YpC0R8D/oT/UNGKPGJg4nDWTHeH0yZepAZ9gv7JfrCTo89UZFNBDID42hzYFlVsJWydRqVDAmuY/F7wOXUilVTB9XJz8Vz/blEFpBMndLWjYtVHeqd9Y3sOkq2MlFuXmp4VNuZoRvkecpDoKpkCrFKknu1fXAdQ2E/caAK2VO0cJ7tegeHKOoaSsKf7U12xs88GtXo9UZVU9tvbOZiEKAChjYGZAKBOPHZH2TFq6e/1p8EJ4a+kvaLJUsrbqa4kYFh7lf0XGRk0qDkgVdPtsY/xjijY8mhnIytsgggNzoGxgwzVpGHxbvEs5TtDQYWy3jw/9sQ1ap4fLbdnVzn5j0l0oWfaoSCVfPyLiNHSG+SS0GWxVAh3CWXFjMj5nuczfVZHX56xLie8Z9xpqV/XkMgngaZkm/xbGxqGbFqy7tcHfIHXM/6AXXMEhDwWrealhb9ElyunOOH7LiQAzJf3aupFeMq/Qsj8xrxZOT5uqzhWp2U6Lj/PApJ47O+VXAmj3Mph9AUk/qvEnwRrtE4Y19B5J9TU+8v9gYbVKie0MOTfqL0IKoUuhmph2KEJJCUEaiOISnkO/RUUbDW6lAdPmPf/AKdliZO4rZvMEAdOLPMRGHaR6BJinIGii+4jhLqfGNBKTmneIC6L84Zqqkw343nRhYel7VZVAB9gn8++UO5XfQXQngu90cOS0e1+PqstkpAkeNx9PbA9VWjkR3UXUZToAYwCjq4FK5SBoQZKXtoEyAOEV/gdnUCeu6hSElaG7tNE7Sp5y6dn+2CiaeUH+uqHEuJhk2TIkU3KVpMwPZ+dr9cHGw3OoJZbprM+EBbQxnFfgHj5dHBq168sXcbpZAwMXxf1xexTOHJKm+4L0RsapQ4hGJ2gb7lmqC8hMTbo2/C/yxuSzMoE/nU8ML3zjOXUtli87JzahCaNdbLdPtrWN42IaxSrIzrzUldDU3VclctI9sQCxWDPjyY7ZgdF/l+10PuPET7rH7I46DXZAOtkGlQ2cHTPbKoam5D5saBdbKHjbTt67MU8WxPyXk+ChZSDEWSTGFiffEA0jB2bYCyqmkyonSA61GZn+sp0ujUIphRZgwhpOaAz0TJlh6KGi4MBmkdUOLnlaraOLnIrN/ozSVUxK6jPz7b50nbPO5tqjl3dLX5+oH2uQZgpJ5HR8HzNE6o9wWWHF03lhh79AfKSM3wy5OS07NUJUg+3Uqx87N+b2Rqht6w6cEh7rZU9rzytahz/cDARLodlmyHTHyrdXRM1GqF5b1fzv2Y5u33fqb0ioZokljjLUCCgdl03g79Bb0Z17lINKTAlsJclKVbA8/wHYqtUCACxB6doQJlNinbgVmeuA4cczemU1wlfvXmpj1bjQQYsjYgGddnsQZZlWescFgymX8+We1N+6SA7QjpYvQRoOcPsf/NsCTH40N3nBLDr4wcaKgGDiVPQ8M86jh7QNcX9cboheI6o76Zf2HxQ0os0wqrOshW4PiFOuSM3T42FuMgcb0w6EZOK6beKKTEhh9CvOum+72+rHdIzxvXOTRkiJQAl0WNe9bTvQvQa5RBUbiL5D15pwa3Vkicp5dciQEZWvyg5I9UWVC+NkD97IuR3ZGnAHoKVvyO2wMRvg5M8Lk0u6Y0YFqvMJ72LPgKJBZyBEwuqUylqRjjZRcsLA/xUmNnynUUrMAUVQ+j6DQphI62SeB2AiithbaqM8YlVVZOfTFq/tqwV0rRZKHWEtodqB444Dj0bYh0ZJlqp8YErhec2xj7FsyJDOKVmv6FD42iGAxQdZhpQhanNK5iqhulvym9SPeNZnuUCQ132nWmJhs2IcXIlXbv8gBwxNBYVnPdbSarM4SIbTBctpEKUS62qRNmB4hr4XmdUDlpMHJb+kSPuubHcs3t9UXFra3wIuvaUHdDaAUW4Pos7iywkMIRc81OVbQuUu6iPmthGrHOkWyNJc+8BzalWDpCzRiw8FAQZoC+iXvFPL2bbrmq+xDny1NA/foibo5sTt6JllMY1MskphoSsgp6MZWpY8ZOSiyZXqEVKuUygcer+VFOYg51VfukK0GJbWBt5JthVXgex+va1l7DSHRcOxmRqTJC0HyB9w6wy4baYR3h2fXZvrOKztAf9g3NKGweIXCH1xuzO0L5FEOJgPGmh0u2gYNss3TjsuAuD8/qA27TOxbhvNU8CbnxTJrCpHUKfkdnyC4Io3ecNzcaFlHy59pBSGYZlgjBoQYEWmcCQnARsAW5Q4tjMMeBT9pH0/nWGusvZbwxi62iB4NefsAUI4Xegww7rjOetc7SgRpE7w6hjHyY2J9A6GFoQZwY77K9voLhieEUruUfcqAesOcaUa5aPxgvBUlRB0lVCs09ACfqLJTIkJ83cqdTAgC1tBVjm+Cig2AB5IxnulxD50mqDUHfCtdR35RHM8lCoRAb9RY765lVDR0l1CiA7MgdHW6ZbJINxbVLtXNbQsG7uhI1sJxVB2WvAOHWMd8CCWHYR05AaA7Xq6TqUvxmwKAdUC1AmAAfYaxNYOOMqfB9Z6mhmlrLC3hvRmtLvqFoLKZSG+mQpkMTLYx56RWogW53TOM98CxT58dhF2UnJ/aoJTeFBH2ahNm1jqWU6E5R8rUwxYq/p/QX3+63YiWDlC4DbrVHOkoyaXR+r8/qRivZmPqC2AtzprOGmLNg7W1Nbb7bkmMP6DlQArQ2HWwpSIJ1n5s7IPthTWTMXnW2s4LxOg+5ximoMD7r28PM+hcczSje2wlfKXUViW5DmTxcRUbnFzkpg3k3ni5SolqPwcyADQWFNWGx7PukmP4WeQvAlSv0lTjWJgN7Uo+o0M+sLyWagcuqlhrsPkqz1pRoahiNvNEjmV+WCQI0pO4maOhVGW3lqEp5VYOyC/SbAdxzPJSiuOwVeqfS341rn3gXrgbTtWdky8c2KSh5cf2aqWcnf1c6XfUNKBwH/a86U3pylk6peb+NUZ4ek5igip3gIc0YB4ik1brXZUZjW5CMc1NP0YyyJZdaucJdHDRqCxqhhiZXK+jOxzhmEGF9XVS1WqwSh+qfgfcEJQ5EL0x8ghCvCmMaHdu2hzGjcx6FnJmmUGrkHP3lTOHyjkXMCkrMm9omRsXiesY8xxH7Xkl90EqmVp/eMZAMVScctsRt2LTPU68Msg9ve4atjMIJ1pY1PV2DyxqmFAFaXgHB5Oo9wkOZVmAaXXsR4ZvIZ5tlSym+YHdqa+yeyDHj5FVvjjptPFzHhBD7pgmEaXKqQOM1CrkPdeYAQiWYvfUEaKFfV9vJsgyxXUG7b0LEdBscH/3APKI7yHVYQLplxNbIrrTdroxOxCoCgbkuAZa6DxGg6YukkuXuAeRmGoI8do1sSzsqRcyJG0KzBVqAz6KCgZ7YF21dXsSDJuqMNWmQin8vwnBV1CsnJEWvbbkQpMYvz5CuuMUOAu6elFFOU9tj5TdPlabFdlI8+6gj4MDdCPQ2Eks1YXp12cAAnQzMARQ8aDpeqSbI8QUbZDVjZsEsGFyf1ybpkKfwZ9w/7IoZN4XKqVRL0F2diIiejjeAI1DcaeBUqtUCU693oDOcalaA4yxnSNshTAllCWiYROYbpYohhPaV0YmvfZ/3NJhpTZddleqEva0QG6pj0JfOrK0XQqHsbFNjwDQAXLsi6yDArraAEptsOpJvnttFY3wzHeADyAinvucHgCojqGWRALtIgPBsqac57owxCK9jbzqzQwoETJ55fn5yNS83rlczEl4JlVzUxaHKQhsIypbZ2BMKCHE9Q6h4UqTZl74ZDLWq02UIsGD0LrTfyqdBqkTBqOAWnkWD/SzVC2CDrGWFi4cnsAa9Mf6VVmbdhxI2Yhw6l/VZMXgolfFIZaH/mjXuT8MMyXxemJHr832HzbFg8quKUBqUxj8v3pSQSDDt6ULn+Mtqk8yi9LkGvw85RR0a15ukLthxJnTP0ptvaUPDyBcewMb6RRSlB+b6mJUDTwF4hlQzwHHNRxPJkds2kKN4A2txrnB9Ec82ftoQDn5o9FysEYGqUNhGA4wpGIzrQQpj1TmMZdoAas2BfvwqIIyD4vacyHB+Jb+ptcTaULFCHBE6C96rJkijML+5o+lJcyiTgHA5Df7Zpuqk1rFnhjzD/CKWKjxv4Ajh4DqQV3AD7XI3YDO5efQfYHp4zjKtx9Gvfar109xLV2kkucwXEZjjJk2eeZkZwT00vDLjq1KCSdiWBde6PYum+SJsT+iqcm+mgmbM1cEQ9Vmm7AGkXOurUF3F9WjWEdsrjS+GV62UqW6vM3m6M8q/yJNwTwtSlEH1DJpnJezT0FrGxS9Ijm86flIGILUpRzG8cWLVou1NktnF9VjS8zO6uTkVbq9UiPmIYOJm5LqjCEy5ZI7bfBQ8I1yH/kSbZk42lh4mlNCG8RUtZQxDyDycF5ZgM3GezI6Ph8X2GCAtSvUOpwygwlDKCoFdNLQ7jshWhWmUp+J6I3JnPMddoO1Kf7d2QUq1w960yF2DwEPXZZrd6IzjOkNi8+BS6S0qxGZ10NiqZxk2Dz4zgIwhqrm8kCLE9WDGR5AaxNRcFhNcu9QC1DoI6pXJIp11GLNSpEADDtcBHTN9f10F5y7odxvDKLg+hski3UzMUT/wGtAwxfXoi+cwW4EWyxJRufcofBlsW4qqPLZnh5TCRjRqHnSgF8lgjq2SeKxN9lztKK/KtH/AusCxAWNM8sNbQOzzOIllaPssNHxKQYSNVrIhMEIUYnkYUwoNg5Joo5btDil8xvUOCxJABFd0eKMVoWrihiTGW3UMDfOdKaMidGwUS+B6aR2M4exilHSquiq0tSYL90XgnTCTF8XubBYlcxPiGc01CVkKgpBXAb/q+lqE7OVkUV6fxStMEL97A+SN2T1LySSqxrIhbdFbJP+AwnYc/MmaQeTYzFvgGQYvIy5QNZHQ5iaLM/sInzTcbihucH8TeNzbzDAK1BGsb1WawaX2a6tmLwPUTaMiS2rB/GJXwsi0+gIZr7P8pOsKkiyi5G55BsPswlyfxVts2MEPRbUwFNH3uvbNLJLzNJNjYE4currQZO1Wl7xRTNQG3vexmYbnabRnVdEwbJXSlCD3CPvG1YbAYowSFdsivYronp/paDS3VXY2D9TiHCOi0j45jdcXsRxc5WNMM6l+dRUanNQLtOY7MBphNkCuL2bPQJoxhnMMPgbpSGyAguLu8h4pjTJ3zKHyMDTXMKg7yRskGxMfM6kp3y91vdIpU5QPtEKIjYdaDJpYjKewn8LHNkDAD66fg34T2iRhAZwNUkOAOE6fyc34LO4zowhxwP8yK01sGC/aoIaq3VE8CSN9uj6rMxFR6dh1yQf21sprtRPYfvW0ARiD2hMEUBF6s1SLdLxkOHDtrFDutBqlJFkASxYgkPrQJWyJ+1gUlHL/zL4xsi/xVafz6i9JBRrvjL8X6+ZSymCE1SEPiiaFSl/Ai4lH/tKFZ16dAkUl9LY+xAJi3INxTD7LU/DH3GQi83KG/rK41uL0Ctn8Gw13J6AUlyHu5QLw/LzuiSwqrvM9sb5j17DNazduE5Z4VH0frNPrs9qPCVpC4UGWHyxXgy2OUYEPzCMkixW5tkbRL3rHSF72B0j25KwEPOpdRcihNZE7tOHqFi+yDNhIbYN02ikDNSj7lrBlX4bkjprTNqlOMCSThRjnmCEK6IGm8pDvA/rdPtUM9dxzMXi49L4DUqXAZNZeAfMjJrxwftbLFRzMN14kbKUKIxiMZ0muq5YfoMbbWOiCswkoMJb9TZJ9SfVBjK0PftY100GD4rTkOrxqZvY+xWeon0UPJeLNIySAoB6xMn6guZKs6WWhq7HRlchgDikrMqSROb0Jqu9uXxfcuyNxaUwfqd0A8JXisd23FSOBMTEHxac8+ibBxPUZkIEXHfKJ6zCiJbrRa3k3DR0ZmOdamanpQ4+VBzzfhofOLK7HOX2sKK2UdBldqdV2FNmAh/NWlu4cwhform+zwRqlNy0/VoYn03YVamJX5zNpfFkePiO5wMxlXygZ2UVZWyY7lPde1NTN1iLPctyKv+psK/+tjWeDUDITIUGRGKigXyj9nTkdmFPMfO1ZQCzbS35fIJONUhdiJ1Sj0NOQsgWNcv6Wj6ZntGGXTC9ErtWsDpMtxQICI4wj2wBPazIaSd9XAbbloWCy1bpTEbXuiYIQte5UEcA0hvsDXY8Jlhv/tNF2am8w4EG09VZFQBqgpsFdNUMrMbA6C4Q0Ut3hiC2T8clPyVMbnea7bqlRQZofFhh7X2cUOr/YxSB1/RTVIOld5ZJ6U/ru6eNC4JJsDHQzMIUEivUoIWyN9FagTr7zCtLQtHWqrp4Uz7bamoVP0NKZdKb52a5Gz78cp62MrkyS/HYePiRrJNpzJBehFZjGhKpYgP7dFyTjUo4xzphY701DPScZuTWjK12RAfqLxz+/2BXJtJT4MkMeztGtPlcVe3OrWgSUtwHpAv0TXZLskpoE2sgAtPJSnZkjwBbUMelRvOYWQwyDYRASZisnmHH6sPXWW4Ho+4mcfZPDFBwoSxu6+WKUElinLAwmVcZgKRkV0/+J6zkfZKGiAzZi264rsHLRXdLd9xexYoVq/0t1hqU5BQeuVQki2KLxQHFUZ45PyBnmO3h0wVUzrzQI6b+iAi8JqFtHu0uPsT1YKKJ9UH6Cvl5IZSeDk1P+4HoJkwc2996yKUjMlXmsucbMrxKKlh0hMkXMe7O0MtHjmSeN99l0zCqTj2zlJsE+qHyLPOukJt+4UmNW9Wg6PFAQmlYS9GrHGuBcBUkFII2C3VNDajuDqpHfxPUozsDmJ+tOu+LEbZ0hSh3QwUsQJwfAxvfeogKZtRoxJOUFxMCTOTWyR5EOrU5pRNRB/0lswzH3PEyRvVkyQ/Vx8NPARJp5aJhbqMSodLXfsy+G5Co41eAlUMDDQiYqCMGo25rP3pIZsi6p7sIaaaH7tKw/48nE+DDygRZr5UK4uVGyREd0MI5mF4UiLw7JTl6h5MTjTRZHERYGkoSUrdROq2SD6ussS46NneLhuaCCHUPqAq6ckSiQwQN7kqLy+lU7iIxQfSnkTMCb8ZvFyc5NsqVNgPmAsXS0b9EHBn/VpD2USOE6vEg/X6TmdrG0z+rYGr4c0FMJ3I8xCQWaphqd3Brone6FYhIHKu3WvsuiHlEs0i451t0otQwKMsCLEjxBrxjX0fSMQVrNVMaE/Ym7OynQ2UBTP1MMmSAH1nW9v2Fs+ENxhwdqKJm21OTUnGhcZca8N9osPVfEq3QQXdkVdxr9ObjOS4Yf21gU5pTcsZYVMGz9qnvMj/rtkb1p72FPYLKOIEGZrpSuqMZCphSqxBDaZUBBDEH3vjHnpj0Od8qDH+CcoHSqeeT7MDSHAc9uopjGZ7FaAU76NDekTFbHRYovNkqW3Ut09MnOALFA5qXHWBXSrtE5bu1YxxmU0bbY98IF7+kG4sWCcIa2wJiOndFgK2pPNoyyPzEpC2eL97w8OS56ouokLKrDzaMynB1TmCnYwEiLLUaF8OUzSHi0EKOtuxfdgzJi7IWcAuruofPAU0D35UvrrNG43eHSLJmeKEpmUzZUmOBc4Jazb4EnOtI/3Smb6h7t6DcEyMXkEgzVuPAf3rjc1isn3XmoFrWU4yGK6mRZ+glTw00Zk06FsOFcxPhYstKIFfsQt6JD4frO4Gz0J+B6w5jzTEBbiZOULkt1YojybHnfX5SFoUOD6xmvFGb4JsaBSTC2BYJ5DJRpAGPD9dFX1B2leaGNjMs+16nht8KYIsEnW4etMl4e9itzHZ4CjaCzDABu+yO3cvRIV7SfFUst6leYexzGEvrruUEvIxyqbb1iaz0baz+a6924QJelwTaJagMlqE/JBOh1Z/4qbpOMTW+HqhsPIBPMe+bELTNtc6jsgYmaFfjri71B4EL6/2/sS5YlyJGtfgWr9aVM87DmI1ixZMsCg//Hz1FEhrtLEY1hNzuT112qGOTy4Qxf/Eb0FbPVS5hm9OWRWEi75V+ythSxJSXfysP4Zc0AMYWwTfgWDagPB/syEHdvbpgykPtQ57ygQymh/1abXk6S1HBiUjLGGH5HnX8bMU5Ftxbyv/3aevcPe0On3OIZXuwPEEqd7E0Leli06aGz6w63AUyNELYbXd1sAjoDJBK/+dvNCpiksm1EVQez+8YQHq4JVUhuxQJRxsMTzNEQxWFor56etxiXq6HWU6uVY/yKyU3xa4HxWN92/eWsbBC8LIF/uK+9oZG7HIKwHgDnnyV/aYe0UHLFvxleHeRWwyg9rnVglj6pqN+N2O0NXHWazEBmPpg90f/w965NPiz+I5gMbRdsKFLUYr1LF239sPdV0uLw6vKULhMfg/1s6kzcJBgp9EG676BbduooFH29PcMEgfWrSluQbDWFCzt13LSnAlsouUs9CG0heWHTziCYMYCSdcjhOHJ++pppfDDVB3YDslJ0hyLMD6T61WrhM4L5tUebRW95YncziuQ+wQiQ27jAO9d3tYK8PnF3wV09NkuatkxYp2kgrz30RwdidrjwrH3p5uv3BMl3PMnnIVrnuI9KniTUA2fldWpzCViDBwWXDszBNxOSKU9/vosDr3G0ca0jOtgM1wzJJPfVgKEdWIKLaiP4Wt1UiTLxJBSxxrNGFri3PyNTZCt4SKyDutaXjH285G7cBUpoiR8mcuvulmTeyjtiXwnFc0zQxwGZGcbAkopRbPm5tA5RjrebeUkVKaiXDp7DSeWT4TvItwoUk6wZOBCfV0yJVPh7fYDLGfMxIzO7wYUWOeOXVALP3fuHfUclqCw94FeJfkrKp6ejFnVHzaXYAApNyurQjDNJ7M77hH0miSjpFbN3+QBWw6/M5TC9fF6dybcTfFxI3pS2EGa/J4k3N71Oui8h24fnT9ENzZF1btt5GXKUPOmZHAPwUsVXMVMqIfwdabnEQno/6mpIkM4WKMpN5eVJThMog0GiyYZnnVLv4e8o149N+WCWQjOUvc1sKYWSlw8o3AdptthQ/Oo3SDIi/B2beIQU6UF+fYaXmyTUBFwXxxFmpIEu1xC09Rcn4SbVD3R5d0MaZe2SDojIjAIYiSJcwOjag7JC90umvBf425GCTKDCszUQjh+8tQeWRnodXJYA9w9/dRJx0pHIfVm1F0VfcabGzR5RcHaQl2Xmsd6Z3Ni3cOtJtEm7Je7lVFuqbWxpgpXdEVJdLsUwtNSAZZN3tRk3tSkVDf7OIKnq2TItVA2GdAB9CPFSbTkj/8Rx0C9ZRP1mSkWLv12IDc/tER/uUadJw89jA3QuID5Mn3T0ILvtcU1Q1vMnw3JZK9gTf8PqOglNmGMCnAM5KOpKo0WjRRNmRjacPmtsAhUeNomTj/ezpgKjKjwjkIEyYDwNGEJ92mc2FN8bM0sl8MErtDD3iuKXXlToC6DbBVawLFgwQoyujJF7jr8POYrleqInXIZrsbs69JgpgpqBqUUAzx1UPXc2Zli97ZlNuoRaPP056+69awVFyXbrYgiFstRzG4Q99Z1tMJb7QLs1o9VCiUKfbT8Il8ahOgZNFcW5DWjwlFqiwK8vbLoqieeO6i5i8TOmKHk1qQESCejHG3vKi9tl7ihEPfcGzVLyM8NfyEMaLqkjPwcO0YBuywCVTxAeNQtpws8uH0F8aUktJ6Pip9+XwxB2jEQXRUzXK4ZMMZ2ybymG8PdKXV12Od1ZyWRnCuB0uqXwzau9l6jYMmm3uh0d/L/EF7VQ7QhgkBkbl62ElYVHhL2Cw7jZGyt5D/7OE3Ump7+eNzx8DBzDyrpntGQupsXvh1pIQk15M6cEKMoh2u1Qe6OPMjfFERUhJg+A24QSx1ZmS5qDvy+lK/qAGFWAEfSFNpe4DaSH7aJ53D/UhUqcKUfvuMuH4GkLaeLxYcYs+Vriu1Gw9WF7KNs27iPtWeB3uk+a8nVSmQKxOz0h2+PO6ET1vyZJKZsX7eoPq8vrGEmdGMeEqT71U0p6Dw57EwswNBT+iMB+lXAa/0xMLMtr9XT5wzvhojJ0u9ttffrjwJVVylG0nzq0bPdlJ7LXb1KQG4Qa9bnLGvvpYkTZ4j3eYgfrh4mkUhzh7z+YDtE85odWcpIn7jm2Vf3inJqUI87TphsVYfbDDpfgFuVQryR/8i4122rGgYtdj1oFOfe2FeUMwN+710n8xxmrQm5UIeuzT6oY3G5d8uuHukKJODW/NfZWm2hara38FDSH3SibHSGnIvfmFB1GBDrGyfL4OwhRlX+Wv5lOMbSk9EZA7BF43aWoe39XC4EbXE+yP/0iRKguTTbiBiZoZ0h94DACgj9CXKUdKlDJV/H3H4z/1JlE7pNSYrWCy6VKWijhPkORFdPP0Mti5D7XR5vM06iiGvWwppo0Pzm9B6ufU8HZIGcYezN0qHfpaAUoYnwmT+yrq7J3pOct2erCFDA0B/xG0lLOfWqPp25CBRJrngYkS0lBq7sXJWC9xTT5HwFiCs9COeOxYo4z7Aiv2QLMCM8HE476ElVSkVSZfdG6TPsykfFRMUCgdmdOGoM0ZePO9tqhKT9fSjMCKod2opIrRIpflhbrwtSaB4lhQksnWBfPd537Vn1CVNcMrviHD5onRrylkho2rxc6pWDE3/HhLaXQoloW2Sxnk4nU5VkNidMA5ICnPZZe53MnJaYsePABTE5UlRMlrUY83tVKrSSKrEKcHzGMcoH7xEdOZvzt3EOsaEfm1qy1OIh3m4AANqyHYVobOPxcGSGnGv5eoaQse8Mj86zAJb+umqpdRiy8hbFWim7Ehr5a0LcUtuavjeBlgj1+c5eh/JLTrfKqLR0SVV0THNmhoCaJDzsLaj2JMe2oRZOurOmxL4xFIap89hIfG6z7u1pFAkr70J+hIoxjdFiO6lWrPIEa0CM4lyOOArwuqeua8ti3pUM0+Nv49lbPVWAuPfD1Q0K4wi8I+/IXgzKMPh9QI/YPfYgl7O7QqlZ7dRuHdrhPF7AtJpCHBaV9t5DDKWFx9lOQSckgrCkMrgQSrRiVlH64rCFPUA7nitiZ9ZaX/895VgSOl/HHpnylRuc2vkjeVrFKKpFaQkByDkzu/DMs0Ml4z0CvHmLTfgf5IzlLOOQv7ur9XV2hxJf+Oste+ueqxFXq5z+5Pd3YDlD4k9gJMseENLhLrzskeL79VMaSajObIxuIly1ApUakn1eZc2lgQTJmO3LRsV34X8/hpjKpogGgLPtVghsLIA6CU0uv10xZ6qediDcl7ZjfyN+l5ak0gg3Y2EvDcOSK0QSBgIvIHXdS15T3avYPOfKFjw3nVPuATJhoc6+OZYYPSMfc3jQupULH3wfFkiEnPpODOrtGCrhzsaM+Kut1vb+bVwgIb8z7TlOYH71CIQTCl9NXho4X5blpCh1jAediO4Ul0cTfkbSGRN+02KsidfwC6u91bRKR6KgCFcO/1k62KlOeCf6O10i5LRN1ilYc8DYBRaKObAs0udG4BJh6CznyT8DfJ4XE0FW74gP/eE/PJabATkzMckjJbi80G5v6pZGoM44+TteJ4b2/ereagi7VGLIQaLFh4OH10v4dejUJOuPDAWGpdyqxD2tBb2GrndlF/yPXEel5NvasU05H/L2yN0iq1PEmdP34XH8740jCkLV2uhDQk3IDksDTaXwQukmOtfV8GCq78XPYVmO4x9u/H+oSJciMD5pT5dnoZ7BZKxWPDacLzmHlRHQJ4DW4te9dxAlBkHB2AFseVc4ZtuSDiorSh0NGSnPvuiCQI7Sd2jknEBrxPPpdkVxX+l0p/AYfcySViukWNPr9eO6uRFf8nU3c8kr6tS2sBrPZV3VJ+UpeQ01POfuLRXjByHi+tmVWP/ZRTaUz3V1tezzL6O2yOeh0NpJM3700EoPw97LYcjlqfteXbTTyGGXQIRmZMG3DR83NxpgpMWa+mmuvODqzT4Tvk3CrZlKAWtmA4RA691A5wEy2mxvagOPZuk6rI2tgF80ODJvHxo+JrqFkgVB0wEipchc6wJwcpPjbmzMc1nfVBupBhbRqW08xok7C84nUR5Z0XfaiFreekung75wHs/X7dNJ72lNExaKcy1aFPBQcEW0eCH9TtiL+XkPMasM+JPyCGPxr+2Y3a54AN1464fd3u6DkROgIh88ZE3qH0/mqhGDNFqqrgVvPyNuASaLLfZy7fJmsi7Mr7EOm5X/Heu0quXP6+xiIyM0sd6/y90O/Mpi6/62PjxQc5+HjJ1G7BiZ5syoIoQOQDiVfNKDkZNk8OmBLTW/qQ71GT4mokkN9TGwKJ5I1rQIYnm2J3QxJxPu2HHAn4YNxQB6AljQamoi7m7RmTPCB/2sloYiTcyJWn5riX4b/Rl8au6vNYE6LWW0Ut+5VtG+BXVbH/h9tMhH/7U1Zj7ehnRpTS1cllm76RKq7t/Oc5ZiTwkIutC65ik4jpOEvtP+tjy/gV1LuCMry7KTSOjrvKhDeuIVA7KdsLpKdsvGuYIrDX9/VptVjwp3GPR2VCIPRG418/dDr0Uz9k8sdbwE8r1nj7bPMeyTZPwS4VqtK4kHJ3kFZimhOpz6kPpclg/KeqMMwVZuJChLWlpGx/DOBlZDDZfjKHJU7y/dTidz3mUmtbadd/QglOZE7Dk43HUjaIpS4qEedvPimmjUUoK6WZjiV0fUdUipLtUqK/0Dgy8yRpmHbmtQcfk16lF303fFv8wl/O96lMgqkhM4RqIFT6oHg8QsYNXLe+C7BeSOljZScEeHrFvg6hkT3Wi9W5/q+rYq9tDDEB0biZdp+Z3cbeME2V7MkO2i0j8mSPBZIdqSk9wzwYvh4NW94kkniQp6qZ1suQSkWLgph5ViTsvG+zSKr8a3+6CAvhtJQgV4nCn5YK4dJvPu6vx9umwzK5H8zIU1jvsauhSW2XC+gISDvEHSsoEM9diEbWRHxKL42ldOlATotGuUBFlYfijI4ubKtSh6gQ6ZxKbA8jzOFv/Wx075uDvkt/an0cK9H+Tg3VIgpLuOGanQV5R+OkJOOIacsTOYTzhWV5VcM3HtBsuSMjn9bCnYFnk/NLJSIQz0wgBnEXX+6WBbbTvwv0Gae7argrh/+iSWan+cDgZUwNwXlU958G6QuJbRR4aXIDlVkRpkoIqcujzDb8t4Te2DtJet951keJc2I5LikzjktktK2ScHLWggs72jhFc6mqj+ibTdY0FlFbpPaZeOzvuurQ1hJe1m1SjirBV82ozXDzSuhRKSPla7fKFta2o0AZTXitF7JT6tl1Hy4LrpH5ZnIy1Uxkm+VrsxKTslyWJzojVce1DKu1az1tKO/n3QO5EM6F8h/whGtQJwjmwQSk2p8HIeoi/v0BG7lepjvSlIZYst/FTFzhgoeD13zNrl92W8ILfljULVIdL6F1PV8pWw3uC93ZdmQ9J6C6uJyM/GrR9a4B7Igwk5/cOfWVb35BSOERzJc19pCusMKZ1MFkqVYU6cv8RGyTww6bOpxgNunPA2B2Yq80FlwWJo9k+mBlz8AW+wQ6GNqKJmVXVdqIkWX4EHYVsEcAv1Pc14g/8HHx+QKl1keKzHd+vztmOdgLOgjo7/ROQ8EUHw1W82BnFkwHGVrrkR5OHiD3i+b40ANxMGlsPj78hIlkpjcoo1VyokxDEiaYwzHqK+z+6K2S2XMZg+akRjR5wEfv2FuLiJSfrOiq4svpbE4mz2oMileHhhLee364S4PISgfGz4rMzdBV/Vefk3IZzUYP0p6U1NY+OUgu3MD4chqCEL5k4aJ0e7s52Nz69e1Aoe2Aul+7k6igMweKQhCJbwjUhf8p7QHfxB1juy5hJCWWFCOGRJBoinji9kkSJ3xcRCT3mh9PU8713XDa8ncln7e9VUvg5BT0vsZcr0Jbs5adQPUeQSjIykBmLT9xI65RJ+yZ6ow2A3lg8oQl9uIU+lpKf5thIZHJKxSCAUeKrAhBuMu+kCAh40Pf2svGw4j3TFNGuQQTinD7mcCeSCFMh2RUx37LsEUL5SPbs+SzYoG9gvfJ/VQd3BjTG0iCjC5vH/oR4vQs2SKfV45jaF9TZrJ4G3m0Y7r6PKmAlULCUtoze77Et6A+Njx74t++WhpaBJq8aD0WNDxbRHyThO1agQH3DCZZBmEnfLhVUc4Xgr7hOfZla4VkTFGYnsVIH8MQQ70MFkU0WchjT3OEU1fK4ei/ZTS/gT7gHMLNqAkmagU+0g7zgP0e3LwTxiWyYrbzAuSa4taThPUpAAPkrygECk3SfEzr2vFXaintIcUmPTw26d5RYsHyg0oj83bXGH92C4O118/2szxQh52W5rf4ccFu17g0lrBciekq1YJPsG3sGgoVfOneAgFYEx5HrKRSPJPkxZEFEVF2CNubkNUy6oIPkuZ+FCCgZc+TKtFA/8tdzoVHpXIYy81b6kiK7V8np2CDYSP8wS9LHzZc5CkrDsQTuk5JogG9Y6mZIUbyYRPejbpB4hy+Hh3OsI0rZqCff7pea8rFIpkDahLANxOuLu5GY0UWQ2Bp37UYEv363dXtcJt9tLES6UEGm8SDuhaibBgulc4sPHxKvlsiE2tfRXSs2VSwiMEXxvMiuX8GMm/rgTUfZDEr1FM3AVa7vTVq0FkGDhStZO61oztTh1Q3n5qpH0kPpecthkb9FZ0eHc4hQZZQA4FYGCDrVwNuwmabBRme1eBxZJe1lIzuOKmAN9kS6Ik4ZNtiZoU9kITi7KTInMk+8wUXCq5+631iz8ZWQ9oW6SM9ABZCjOgoONF23XQL8pBcxxVI4nq2llS+8k+hA0TMmYq+trd2FhsHoNNWrbevxqral/VuEF1Squk36BbLs+r0Ihoj24A8/DjWGMtErY1Obtf0LYpWwe+G1ySGux9VXf68hBslkTxp0qZF2aKxrbK9+rbAL57IN4XIAViBGpomrAKZB0+jhMJlB+PqypxOwr87BRXsxSvxDwDjIQL4iR470UA1x7aLuS3TAL641k7q0rmvJU5dgJL0oQLqvXAoZRVEG7k46PeQf+jPki9kpu+o8OLQaUmFwlBpkpK9Wjgqu25QEe86Xsj+XKPC05iPvZnUrirvU6IdyEpRQaANtpAG63v72wnn+Vo/xIvdo6LNkW1sb32Y5dk9QZ8X99trGG3tKfTcpdJdjZo/Vx0smPzuQAhdkybMSaE9nGY3atQyWKIOP1DZWs16qeaCeT43NrsK+YJowf0WUGugpFEPl0mjZHL6X1tFkjbclA9X9/WbkBeX+L913e3EEJO/8LvoIPVfgiQ/mjY7jCv2WhYBxl/zMRGLKxcn40PhUh8HA7/5UgUqzcJibaCdFLPyBpR5svJ/y95qCm7Fh3EI/Dx0QNdWPZneNUUwDzfIx2t3VDXiA5ak+jugaxmDimIUeHjfJn1usw7juv2XN44fyVCcAcdHcka6SCPuUs1nWVAkcNZifjqLDvc3NSpjbUEA94L7I4Co6CKaF//NRc3AuF7L9hAYuaToa7obNFvwJz/RbYoZRTGq5JF2aWINf2UCyUsShk5AmDyhn/oNZOtmQCmAdKhdNn40edtg75y6R0WgBnrTAoVUB0/x3Ya2pqV51Uhy4s2d6DHINZlF9taGM+qMaUUENNSW94IBeQ/uA90/gf4D0GzgWQdBJdx1LxZwx5rGd+a7uNamHWeEqQzzWQi3FdoVWnO+oEAM+r7M7xEz6NZM++Uw9+os+OlQWes0FOx44ZmE2bIvxonhCAeXXmmLDqVOXSMa4E4P7f8AlrnMXbSA1It5ltfoLbl+a0UPJOOa8N2xmTPZeZMFXLg6C9mqTh2UwJZFJFmjK8cjkjoYZDzGoRQdv+uARDAwOIZI9EOqY8NrC/LEsf7JomD3kqz1soGQO8keFrqtPxOaACgfplw0zGV40TgmeHjqIrOjqU/0eBn9vQ0AKQMZ+CObcXzBM2faFZE/FlyxSfhYJ2Md8Wkzj4E9BouSVSopyR4YHTjiSKr0DHlw5B3zSOfqU61VjPehwXYI9QviUaE0PzJvmxbyl9v6ufxkvy5ddqGEW6wHnONWDYJw5SSL0Rh+owGoOQwP82/CcI0caC2/txW1yCTxwfQp+TFIYWljFErRd/9iwp4Mj58B/AisjiWumI/xk0Gr+eWl741aKQ4uiRGOBQE+EP8+HiU7Wqw3rKsyubBJ1VyLOB0zKCxyc3pLdDp3N1dRKD50cVhCdCG2Y+mZN20BiT/Zv2G6SsOi9qc/5osiOgzXxvJ6zAZqvWooVbxjnpPNddwd2Wf9JE5+5AKizpH2wNF5JmvKJ3lk+S0tbURcbxdEh+Xq9kXwAzdjQSoUNyWBaGLHx8DZmIGHM6FRKxf57PZfAtwNQjVyDFNxPaYcbEV9eOFXy0/Xi94bZ1HucaKJ/shgQRXitGO1V6J9F7WrsQR1SI/PqDhWLNaw25tRHkt+pymc7kytUBhjphbMhzXCHwQP14JNrRefyKgEpOJm78FBfFQEpDnMtM4ACQgUc6Pdzm+eA22f7JV1cjxOe2hRtFmqKsOqEguQ3R9hRjIhKNWzrqfxfSTTe/DtwUK6o4JEBEIGoRHJbsY2iFhH55f2Dnrixj0+xL9EKuNwgOkoKcE1hAUJDfVdFkNuJvwQcsKO/2EfXq9ts0wRxpsuqA5D735UBYgXF3n+OPHF4a4rJH2z/O5qBf10PwYnH+CtIjqI7PQ264Vva3w0Va+2mduqtUfLeV4L/0U0OCdRVoz4p88cjOC+zECssyPL2nqoUh2pT0nS3dsolQgewhTT/DeO3yL0JTQmjIxUmL9iFembF1Rio4KPfzzDvnVlWExl9jZub77O4phHj92Ys/YcGCuyeIV29FIhiFESJdqc98ExsFpIrHpEx+VtpxSwzCu6lkxJ8A+Z7ORCV8As9YEVkCU8fFaK1wQBWW90eMHtxYPkaIBpcmacA8mrH8ju0LLgIIGB0FAtukeGGFJ6W8f9T4OCpjtAj4jhyXkYYEW2PzQZSWEn/gqc7HIIUU1soz+ttfVAMaj4An22KFpA2bKAkbbJ0qq2qfdJg6R/oCjmlbu8cEnRZrRSIoJaD1aWuVSsbSrIgK9qx5fSqtKUmeE/jW1S3T2zehMLrvmtBjF2bxIiD/xVbVrpdPVwDGGDnt+ppUiHyRguWvPNFi1eTRGBFI5Lrjyaz3PFqWp5+t7W4bcXuh4BCLfGnQbDDI1puXycMIv4zix2RZVGn6H5iajl6Bt0wjpI2xfLjma0wQYZny8iv+jnnbq55qIulvTJjm6Go7NtgYGCbk1x5RqVUSitBO3rrNagc5mVr3J5sPP2vuSKqQY124p099NBKB0nGotgR13Q2twPbzs7iigbcw15KpWqbWcOXxAAJoZH8d+AY2blJdh8JBQfXDlvOR6ySqWrDj2fsrugGiO6Wj3u1KC5rFR+ZlMeK5EqYHUiOVNv767nYHYk3bxi2v+UtXV6STSxfOJcm9ybgaw2WhSHmxEaeh3/vHjtV9QL5UGo2GQpzXesqUIaDXsNiHXIjR7kdO2tfFvlz5JW4RKOmOlrquDYif5Kc+luCEl4qTMJPj/mzmuHNYIP/mrCVQ3r5U6o27OuH5pkWQPpFu0gssKEH4cA7VMfnz4nKLk1Cl10wqwPzrKU3CORNwkXRUR4DpwWin7helk/RqNFmnsYQVrU7x49zOfV3iu0Wwk07BMpET7DUYkyvms4Z1uXZN76j3/jGiwo+XWPpdpRpAXSUrS0jO7xduahSjvtz7CNRpqyrK6d91IyK4zFHK9ehZppSoDyntx6wxFQJ3w4bfsQjRbGzKDX9oM0GTvNJTUrQ2eLwHPN+8xCeNjfnzsHfYQHgeIGp8UPtkrbSPRQhrNUsC14NBlswQAmuMSS/bpe/7H+cb3Bxm2lSbcl2j0RxKCK1QOol1p0HT9U6Km/7OEi3+JppG59qLTBbMoue259vgvcyxA/XZUWOS/Vz52opfZk+18VZ1Qb4pxsUGEB75/bCZCtzzsUq0SLKljE06ny8U9UnLX9eHlRi8NCzouVY7QAgfmH1J1dX9ZgWmOZ0xzuYC+N3t9WECzZTrnZbfGSuz6boMOjoD4jmq+dJKTMT5vas5e7IKxwzsHQwrJq5ZeI1xZ6h4HgGnmxzFDIJf82Rbak2hjAFe0gjPg8IRKVChFZpNxFTIdThN29nyyS4KMTJ2bmEjoTndqcH/fLo1Q3HqC+l8rdlUKNZ2ou86spOWkhKQYyIEtEPeu2zNEnCnt84xm/a4bTqSLKtamvcqZ7gL++rpdI10G+oewYbwim2E4W7lWB7kdg5OSAtomWiIJXehDJMdOjeVjELZcGtKDZKy89DeH9+V2LM99rnuc0q4DiISJWdPLU81L+eRiNSjl1nD3nzUqpOChrvZIsWwGWMmsj4/QesNCVLU3nmzWyeACJo5k4zIJm3viARQzPj7Ai3RADEbaJZr+ft0YnRLJw7+d3W66QkhpBFzzMBeL6FN3zcFLkivN/fXxNe2T0eaLTlUTK4WO0WbZYzma4Pj4eHuWOI3pBHUF1Qz+wIwzowxat/j6rq8S4ad+toHwSBXPoNTotStdHhspXlXaonZishBOKTRZAXXvAy0ANaeaRkXSPNPNhg2qNgSGoeWFkjqhBeZro+UAspvQFEYhU6TUoBp73vFKTpJB8RzwLEeDzwIzvO0aEYpqP50kl/9F+eHwe4/P2bxJvYAo22mFzRSkNijTm8QHiGZ8HMaL3RFiOCZWw0Uz9Z+xLzoMji7gN6B5ZrcG8695Gh9UFrTF9kh76Y4PbLv6c87b1vL3Qy0HADM+fMJx7cRgdECCMdhp/jUpIbJkjgtLkOHP3XwfDeBlfHx17/C6qLwqJzdbc5x/+AKzqqNA9MzLIca/LgCtxYVgfpc9IcxIn9BaIMhixFjwXFqg13d3pQg4LR/2A+kaRYHRanrCuEMwSsIecDk8k6/vbp3ytz6+HAVSMsI1WSVWHk+YK0SiUa5XpP8Jm9rrZcmCiDBtjzCXxsljVDasw4Zjo2TUVHNpb9zf9etJuO+LDgYOXwWyG7ah5AW+4+gUF45ruBRhzl3sXujEFn/mU/PSb/m5FY2/V6odfDTIVShwKMFpW0APyeaQAGoZH+8OAmmNDHW8HvNQ3KhjIkJ6M6PduvTVyCUwIx8gmONCMB/g2Yhpio42g20B2CwKE6xAS2e0eCswcDYNB14ZH2fCLfeC6WDpjkPylUaXIEZUBohaGb3kkjbTsAg+5vrYDyPwCKeja+r6e9Nthio1N5nsA9baaJpvvucQI6AiwXu3noRm5ftmYCjbNKTESd/xEikBmjLIb8E8RSCb4llVeQlHKAR6DUWttjFuq7wOiyHO6W8NkjHuhP+IxC4u0PKh39rWYFIpRzU33dYNlYp5NhXsqMNVgGAKZnMg5cDHYftXHlA5PhO0+T3elrtIQdHlXxDnqfwGdjn2fZy+Couh9v3YpEYNMGFG7HgpGi6Imxw8kKkyUIhOAYsPA/K6uEP1mRK2ZrNR21UORAms8oJft8tDrDljlm/xwYe5WMbXRDL0QL4CQANEC4yads39CFAyP969j/t1ON3dTdMu8r2wAuRyBgp9Ymou/5JxlzyMEfhlfJyNKIj3eIBZqroI93vzO55C4+CDx9P13Z6DAA/EL/zyCnHJ6m/00LYD+HFrgDQtHJwRWDvdl/3GAH4ZHwd9TNpsPImv5Zo5RCZww9Rpb2kuOEJFZWpgixG4ZX4cw3fxyNM+w5PM7G6vmTYpl5/W+qHXQngZ5TAjQz9qumMwJfXkvBQORDtI+VgORdcP9/AquUsvYrTpEtt+TiZFAy93OHvuZcNUE3YeZfnP9N7LgdALZ4T18Sr5g62oFP96bK9NW4SyipiGiRx6FQV5sL2pCDTjCzjIxsKX2G+xo40RELknantcaR+LSLRd6OCI61TmUyvqQZ62v00v5cFjwuGVYnNLmk3eUcnw6/DPkvO0Twrosn9yL9FUDfEN2A9mvVRo4IxRY7XIIYwv6u5OWqV+CPCkqyvljXSrGfLaOIeyXm4s0MuwRILt+uH+AraMjy/2KbRdn9mRZqGVm/v2OyTrXEBX8PeZt45Zdo1zWZLWdK/N4+W6TlsFJZVp+CiOtAHlZlxuGH2BFSH/U3yhAzAzPg5T7fxonWsnB+vOaLvHeJKx/qF6RPevN9J89YNFLJqvE6vLhEeJxVBDWlMNbD8uIdwNAFAr9V0npg/TVCAYrePjbMcclhredWxpBZW0tYpylx2KfnxruLM5Xcbh9oZyot8+cUqcID1KMWVagL+ZLvfChmoCBRZRNULvxzcA6FM7P6usxTB6TuhodZCtmkrpsTA97zCPQfsYCDvP1MYUjB8vQXAhWrrrrbT5xfgFJZ1EKphQ8z8btRTME0VUmic1DN5ZpY7ZazGnmWuS43lebYDfj2cd1KT8eIW08DTTZ9kI6ixzMZdkBhyOI5GD3npkYW7jALgD46ASs7BQDneRky5Zs4vxoQDYBiXw2ZE3jxnGNqLHWEEy27MwBE2cdna/ns5bZZqAHQ/JGRjRASTca98sMiKA3vOEr2VqnvRkpZWiK5DiI06CDReEU2h8AmQLOtcx+wUL6bMfJBGmeI+LoSHgbSmXVHIsdfjiXN/1e1Pllvb3GLd45k8rIBhi+DaTS5ncHtkpNS9to4mxyvYg2zq4jk1OCv3MZs6sN03HAZNtoFqbRB65sjrmuqX+Te30onwXsS729OjDTnKKn+Sgn9KuWmt91zd1/C2L3Zd0Ky1pPA33eraGdzmBdhttTlKdPJXRr7X23hGGtkhkDq3Giwxn9ZoearZNAMZlWUqN0du+1Dy5iDro1aRq0d5jtNBL7SDuRmKpL6dZ8JY7551lO6ZAFwKL74hWoSLE41FFHO2T4LhWToEirMRNKOAATZtL34xSI1J+nDjvqrTMIp8KC0Hg2X55G570TgWhpRG3vqsnBz2csjvAr10eXeOvdk2HcPDrNqQkl/9CXhi9RorClrwlkuFPJsyAwyh+SUnh7330VZe6KXVG19dtHXm5jrPwy4a1GkPPoIvw7rA+Cbzodfbd37fVGg043kkebcGflQGHkcANxsszgCK0IgsM44Kd1SL2loOT50J1T0X7jtOMglxxUVKnkW1crrbX/EKvM0Df+YKu/2zCFepQhS2L0ahotI0rh7h/bDcSQkJhIyl75aVSkk2vHa2W9qQg7kntxp5pr/HQcUtURi7vl7isaIqDGeauBsKeFtlHqIBppZzoz1hh/LFLeqfEhvxpRDqdVkAyVZPrScUOWCPwC/BNwQwhFw5QbBCDZPLhnVkWdPh3sXYt0RWHli2IMZ4kLmiCFQwcgxV8ghxHqkcJtsEs8GfBql8XlwMWFIGXMvP9fbuFVEs+tUuHvYVFO2rmGxn6lEYLlo5eDLGEEXL3O9oXSr2pv47wLjKOsjIp9eM0kPcD4v0JWhBUQoMjBmnn27JtCRKdO2AN0XDXJLq7e81x5Ch7lpeiCo6+2hfXQj++vni0xxMv3JLFlkH7RGrXwpRsITJvuByl14/tEiXU5F2a8FJ99/LM9dBTfPTBGqf3mKlTEv20Gk6psaUrl5mIAoHWFp62QbbV5pySeKFjD6XtnKGZMzjRc4tJdpDbq6XXGnRnAwOtaZ9aPJw82iRVcN1RzWeamO3HbGZS+u4k4ocJz/PzCSB0ywNwxOv8u36o1wUA4vpKyKsPz1t1Y5Lejv6N6aNQgqxCTAPdQ1b0PhWUW94Xaeyli5k29D3BxK/EDXlSy5MtZ9kaWHd2yWHK1t9P3Kwf6h3sUT4wwqxZR9nBeqUoShW6CwWGFzRHgQKbYXQlqqW8TKEZv121a21Ei1W3SA1q5Rd04Prubi0cfl+tGBYDEFO4R6ZYJxoOCNYQYCIMJyPR6JInbZYlKeM8OakgoFM7tBCKArm2VRepB4gjCZAcrIVWF8FZ3jgJB0PJ7xPvpYZqJLy1x0Xe1CxyACAzoj8/kd8PuFsb8k3KE8/3jBXifCY4w7QnhP/Uun5DoQFTxobCjUYpMe7NygQ15JZPxNx+AUEN/ybp92XrHNbxG2Rc3/2OgCz0l+XWpdYRuh9nPHd187VIkghnDIEzyEwSldPZ0g/OrQsXvtMO2eWyYPAHaHa18n6Jd4tL4gmGAf8Sll37geWY0Ch6jXcL9Z7eYCF+2DYKCBOIoIUaXfIGl2QVw5PsGjjaHaeJYe87qbFU4ZtqpxnUQYaDQaCLWdn4dwnFft+BQ9dmVHDBoTQlNuOXARwPzgWOoRI6peBQHW6n7OOWPoQHioPvdavYWf2sPaHrjA0HFzxJLAqAE2Y7Ugr5EG8uFJbbHbXpdMoIPLbeyMmoEHeGs0c75RsADYdvDjDh9W5IG7PpyNpDEt4T9Srrr+/6Asnc/ASb8kKfzloynTXfxcu9UnQZiCLKgvdOuIZ9cYAf/g9ef9RDVo2upisNnwjUkYhTzvDWRb2UAOo1CpoJaoVxp9fUNZGZukPKAcnv+HctbnlpChsJObVO4HDM3Sm9JYhrt1Ofa81injFF24Z6Dw2tlEDwbALuJKH4qm1vNtfMTXiWQMv/WFq8Vcz1wIyCmwaqEuu2DqHe3bkwASk8PhSXF462GAJa7iqzSR4HRsEliFmXMRbxDRp63oEhYab6AdCgsKSzEc/JtvW8Mil0F9FdkBODMmxjVmbL2zU3noVfsu+FnXOnrm+AqM7mL5Y81yQIAAqME+XVygeiVqp0OTtj4LhRDP+FbBQt4WmSkCHZ6yrrEg34elrOBfrlHfAzeO+dLocNS7kx9knd6WnJrbvzgvv7donzB6B8r36Ssm80x+V2lfJGNVDE0NSXV7gCx9xNz4qA4t6/SKuE/MRqUE1axNsZiY2lj1aB/aHudJb4sAN8U4skSJ0RjW1VsXdZWdufAbzbM1oqyhUhynLknECGn1ZM5J1+QJlxqfVpmiUrdOvEcwp8xCByInsF8NoSWj8VtNRHDq94jsvVKDrHyOcOu76x/DfzXB3jQvmFBSkxAHiUsnMper+2Ihkngo2JT05bN2hFhwFOrldj/PqxXWuVgvtkdrqK2mo2S967Wcp1p1JHe3E1rh/bag2ufCdFVs7vjEJjU5G32qQkzaX/iHkfgiAQnLaDjOIuHHGNC3fUnne1z243pGelphAASZGtTltBiSCBKZFebvzN1QJ5zQsG8/SrYFZMuI3CkCEDCaCCRHi46ElpxQpPrYbRyi7FlhelQAHsVRs33tSFZxPKK0G4Txr/kkmDHMT7FCRii0d9n9Ys19bpy57nsHbDBgAkO7FNHXr6GI9Khpn245qiyOFTlpFQ42xmxCPrVo+f8tdcKvKsq0O/fqg7KwF+xpc65MJwXU8wPGndr4X13NoB8v9CqP3LYAJPFvPGIPPJ+cMjthAZbZK7pm+rozFUeQfB843ojUM4ayywnF7y8X14OzmYpfenr2PcHzbcWIQFbkXvOVOyWLa2A9wkuPD0ly7dIqN6gQOTpW8qkCnXSExz7St3lVucYcS7vT3tJ5n6XsRykHoWTL1aStoeG/6eKDngMwiyQcKLazamHMuzv6Z6S7krulyr1XC4yWoUjukDIjTMquXpdYhZVN8NIfI47rzmslpZTmBqA1b/nmnuUufJa1Rg5SxF5CxzcPbhb+8kvffjZCYC8WGplKrhMF7ArwI+hb2eABGhoFyspxx+BKmUX/jifJ+e4YTCye6cA4k9g2YeQOSB95qRyttMi8jj9GFtjOQjW1HosONXn8Y2DhJsUfD+4WPaUnWRneiDfNwvizGuPGiMfkO6FX6fMQiQG0telugGpne7xJTUaIjAL310K6L1H8iaFKi4EoDru760gmb1F7U4bqIj3doKb6L+eSBlvRp39w+9ZoXdwDdfpAY7DPnV6v7xNRgV0SZhIbgrbAZ39HGSAuME2lq6QNFNWh1sq7lKS2I2ZYDaTGsSE+rK4szmJ/54nnqhKZt5+YjZpjouxlWI1yRAeRLVTYAx6iavoinFLs+TL8hXMaD/X/rmC8hIuWAg74GokBRAghpkGN1lTTKjXiM4IowznKlTdc832tYETWxAPIr9ASia1I21LaUJ6L/vMOd4ATmKC+OK8eebS6kmAtWlAgnLUCwgl/R9ApQ6M72Uy2mTMHeb0bGbJEd+bAvuH+pJLozx3IAIix4KxoUBTmqRWxO7pfYHSB2uNmT3JnmmxDbqtVa/7YQqbGtSZzZ9001XB9Ya6EciOW7jcqadnTwqtZqE3iXj64fm80KEaqmzUK2ck/XSSJVa7LVFLDLaLFbqLKGsC6+93dX3pHOYoRQbtc5qy8VaC48+KGnLpVQOJMySkv2EEzGUXmwzGdT/xjq3NFR6dgW6eUP6Oe7NK9zJ0b66ZsQTmgqghWAklOzub6ChIhmVfy6BoQUeor7VOiGefnJIZOKmMvGa9M30B30EpRd4IknelkSSLDpMjjonyW3vwoMQztRYe5v8X80NpZsZoX2D8XSj6E3sGPOYeWfGKCnUr0ZyvOqNH1l6quK72IZKkquj1dty+b5+mPsJUGGa7/2FtAyFDySVd1dhsFKwK8jA67UdEsUM1kF6nUUu+MNQmv5adPlnxfKob8FdpqULM7O+bytCqiK8YViuhqc6qbqB4bmXVSIniptxh9H1Qz9INNTOgOm64456SraGc1uSdDt5LSC1FSiiLfHHKBLjrWnjC4zAAYTLo2L9EmsawLtCVBF9Kgo0kP5nX9iGx30aQG4y4exw6hrclo0N/PALLMOvepUOwbB35WO8LO6OluBJ6fqFaegagwIODLqcUcBZtWqWHKTzHeWSkP82MyfPimWz6ZehvSfJWU5UBE9Qahr22clxm8q5v7Dpeo2kklHHK6ydBqjoUgLgWDrOii0VRaU0czgh8JIhgHT9xKIfx6OCiNhpPVP4BaIo7V9zYYCprHbbyylIHMgwJ5OWYbEGmpj3E+cnu63QXC6yQWTimWT6Y34bAxaOgx+c+0k4Xx0UtaOhAO/XRM+KdvLqypJCo7t9ZEwTamjUoJgH6/zeDq6ANWpSgA0qJI2ZqejjLrSQIPTFYma+52h3IX8c/rlnOluXBRrNUp3hPXILwwuqvRN6UM9YYZbq80RNaQRAFaaDciYCdRutyF4mLW75Efh8NP2zWTAbK4L858QLpdRNS5o2LiXXgtJta0fnyOH9+629OqqtGHrWU3N7R/YJqWrgJyF3B0DAqHOTFctIkg8ytStXzKoxHTUK13MJJ6TL0BfC8F+CYgPEM9tdOeUBvmK2ywUT9wiy4vruth5d1DqpA2mjN0dPB/++jK5J/YIEkvX23NamNXZcOEAbj9XiaixcP+wtTZG6Ul9muoh4pp2aPvhZINBRKoUmpfB+RcA1FiUZqgPjVajtxgPpaTJRSL/LLJ70Aq8IOZ0uxMP6vt3YvNqaB+Qx3SuG72e+aafI6QS/GarVAgyXBlJyfXlwoH5h+GMU1YwORR3qVfVK8mhjUN48Ywgl55q8lTS5cw8RELoP54p0UQwMjnvsA79HCyoutzcc/uWvg8BtauCMEeT4UKS9GuK/WqOWocfFyb40KQMYX64s/P6xPUH4Qb75oZLcY4S8aj4o4Kp+eACCpF/QPCADG+zDdlsJCfF/NR5nG3XphwVDPVDljd0Z8lJwZ8y2+u9yMemUexAmOF50TIrxeixjqn3RPIdptfjjTfDhd78a1IxX39RnOvd46q6jotFr8LEmQRVbTgVYP0lqPwCUbf5EzpHQpR3LTZ+5/ES1cTgslF5Sg7ZHY324xOJBrvNy/Fl2cS/xdFyE1dzT0Xu0vUrUdxJ4gqua+f1wy2V6Cp4cDtohzUjRJlWmldEju1yZPcs20qatleWZzQPeaInPlEf4MWbd17M3kkQsuY9yiuAArBCeGiaWYVg631R8LsOzH1Y8/mnNIKtx1XKnCguMXWWJ2pChmpCSG0HYL03LlVA49cUSn5piR0+GpZ3Z2L2Ai0rfAAtZTuD2Laxdl+3Zz9EkavvD4d9MyeXrOhYiR16wCUzsO6sLBWz1Q1MbTRPTEooqUmcLGauwAaXEFdVmKiqo7b2E9NWnVjt1ZyxjOEYrduP2g6S/gR0oTLugqp+uhrdZGUjjJfX4rcncVbMm2CBjJ+BFTkO4qUrVDQZvgrjHtmhcCjvvhLu8auG93/6bBSkiPTEF0JyDWxWt5cMGi80l8Y59IYvahcW/2crTktRsiiHHJdHGg5pCEloH5zN2TSkGFkns3eAE4Hkb5bINOha1RW/ZTmtpvEzzMjawy8pT6R/V4wKLWfxLD6bj7o1YJ4rwfsFt7h9qwwB0vDwxvnYpZWlepH0PbqyS9XIwJDto6W6R7rAn5GWd1C9kvKf/RqE2qz6r9mkfgIigesQu6QXmNftZzJRr9cTPQDGicq3j2VPKOaWWjDwjUs9TQnwGc3Sa2I7hbd/LxgsZbxJi9JPV7LsfRvwT6PsM30eqsJ4mphnQ49m+SXJWDTIYfmP0aeMMGH5VZAEdhlVzc8fJVC/+sraMF7jAhL9khAs2PdFB5+eLjX59d8tGHpxH+SY8yWDPTcU8YqQN/+W//d///b//5//6P2xRh0B7QDnv2EtNdVoTskxN2vo1amAjoShwdTJTxmaiXgpULG9wZptL2IjUMrsmmhEfaMoHQGFf2Of03I5sdscGijFyq9BNzdalLwNv1T/wYislh4WO4bD9ylXfMUtS6SC8h0B+ZZXqzmJjc11t41eR7eyh+VWlQZup74DpNN7ZvFzKqU7f7SXKbo3pizCDklwnJVZx37OOMwzlLnjB/V0v1zksPjM6KdJe90nxsyc3V23gYDIeIqobSZFaavspAsHi8eXONZcw3Q2Bmab8N5ixiZwnXN5u13cfeOR/32t7G1SV1X4MTy5LdXaVy9qG5ySXDOjtMUgG7Gjq7DrQWZKZuciAvtxJWxtgqpe0uF68lKagH2M8E5dAS46n8mopGB8bZM0Mizhz/zU4fOs/ld4o65dhuyGvYlrWFz7TgmRx3abFl22lGWs6yauNQgJpP2h3jMIzOZMtZ3IA9j8/DEGvZueTYZX+0cMZGdsdzEmQnCLU6pfvqX+A5afM7AGj9ZKkOEkyx03goEzgNgb71YDiZ3TJsm/GgXNdP7BhF/a/mWmAci8w+yJdpcEMPCQjoClhe4QousKLpHdevQYvx25qEZsGpA4yBVQwBxFFIAOVjdKZ22XUufvNr0rkYNGpZUysCnXpVMNY9hfru35vaGzyHmhIBVI+gBwevWaNA0pekC/A3A/XKWVeIBLNvziouT79L35U0tcmRPbvrLwyfXUg7u/2tvbwM4J/6QNOQr/OPvDbnU2hwPv56srdP/yVAmycPoXaiAJQTMs6LPreBp8c2rwXvb9vayaJ9J8jecwfDcGrap7uLosLeBj0xCS5oh8X5MV4fG1LU3b8pG66oEN2u9hq1o2S2px0yUtQTx600h1enCP3AvWAj3nABf83g928JzxPkpVmQ5eTDRma4s205FaeTdMBTf5IJ+NPvOmn4Dwcfc7SRyCaAcs28GMmJVjSwYkrQ9849RMAMF4TATMsN7LK3TO9el4GFFESLsnhpODrFuTIAVZ88W1a9nW/zm7tzRKSLW1eXgm+qIXuEwCuzJ4PBJkse3bWfnZgRjLJGeiPOl9V1uOmrkgI8op611f33kzyvd7BeGWBcL1+RnmweD6PrHSfL3hvKSYrRx4xgO4SoXB8llRfMtxu0mJYB8lNPht5Fox466t6eoNCJZ8WhO0C4epw94wEHKV0ohOAZKfl+i9Vy5b/13Z9aUnH7jpESzbMHM56ABH1iKXWwm0I4X1kIAX41O4QlSBdznIcJS39NPJlDftR67Z7tErtg3pweXm+V3TTwn52DXDK0xeMk6MBXWLltoFHVXcHtnt0xi3ooElB4KzX86gf4JV7rvgOXgkejJ+RbV2WWPd3vZwUtvUjl1xbwyG6RoxqUHcJWSh9iZHpSU5rOiBkCT40/RYUkWPPl+OCW4Rh0dRPmdx8tyWBGIuXJbLtS2/7Qlacf5KDrqIHTvJthXW9qu3XSN/Y5HIdUmlckiDX920dMOrbeTKH0mqYwVwsel9smjIAi5PYnVbTI82D41ZGxTpeJV7WcUzE6g3A13RkRx1NbbLdSnh6A0+9OAwXkEI1nYCxaJWFtr8p2wXqaTWa55Xt3YyIM/syH9YLyus59tHVBYU3TltDuSeE++x9moB0j18bYRnJq0UyZGVf9/nVcuxGLLm3Z+TiElQp6idnHmD3wGwCtlfZrliI2z8y1y8NCmWuM338NDgueFpRIhSIzQLc374BaJodTkOy6qWqOBB/VTIH8BaJbqQeTywJKA77xIDCqa90vwtUVUxbPJmqODp4eILRBaCuMHCGsoJE0mTpk5mSxenD+5tEFHPk0obXE/BU2iS1MNUFAwwpEoA7gUMWf2uhafEOpgTFIGlITokazrXTC2kdOvniSD3WGGbUdcLIob5DU+NN3FYqwobkU92EJYHzIjXBwvdHVKzQ6NpOwxICqFzf4swEBJoyOeoHu+viN7JEIOjCB5uByfdy1AW441dV6EtRrqmW7gh2ZGcXLYAZAxY+IOZIjt9s1vwODRYaCr5TVtES+LVYHAPgApEYUkwGwEHyRGhuY+gRi1kvMz/7GL/i9e3j4Y52j+mIlnBcy4Ksw1IFU1i8ScbVqACbUD8ayFcap1y+iuqy7N4KGR5wFRc546JVhky28/YiYUraTiE9/rOEzH+skYNKjxIkhD6PRPNlbDCgvmIiEU7ikXbpw7Q82pRgli6J97axbBFJ2OIN4L5+uFe0Q075TBZPd+/4enaWdO+4zaNLljZWj/r+ri9p/PVjoZb/a6Z7aVNPy7QXnA58lSz0zgzv79uDmvKuvlhQrzijmhm6wo/+YTXYeAJiUHnvajvy3gqVi09K3r+o9sP4zwML7cm0h1Ty0OgfmNpEDqvLYQ5XYmTh9aVtQpjhQxWZ84sqkkGhXjL2k04fCY0bw9somGiMD4+75btheuJW1WTDILQ4yfNH3wBbQHZ93XrikGioaXysO4Hbcg3Hphf2/NAOyw25vZKmY1TUgI4z3O2C9kr/bIndjkZqRG6Eqzw+NsPDDO7LoDVIZJtwpDL1cIGO3vwajC1X6GF3yq9p422UMoRUIAuLUSB8b6Ame4DQFOgbv+hFxNtIQA1WjRL9BiJDfxyeTJLosLGYa6f3hX2ksqP6h53K2jjRkP7KaE+J4+YP1NmPi1lxf9+ukhHoyMRjBqASV97XO0f2gksI2/LPmmtyPWahW+q22vybqZ2XWx2/Rww7K5eYzcNc3lX6pudCmiggOeWAcoCidim7yOqlsu+L7+T2x2ZNA6I/VPn6Yk5H6JfYgQ6kLvqrP9zdlFdCsk1Nc1yYBUZW9oLsSsCcajzopxQciOE46FjIMqqQ+iJOFYy20skYx0nRC0sIYrqHHciDuFXGUZZzcR2GStvMxnf4rl6hAVhQok6gYgqq42ACq+wopH7vCeot16CBKh+yCTFgoxcgRmh909Ew3qWH2SBeDcYXjDzTmkdv/3Ezwulvi7mZKGyyNNvXd32FyORehaLuyZ9J/jUZrvjaMcndjKRpS+1M8+A+ADraYxvljtM+qLoI/jPt3VPLiNWpR+6khtW2mEfyhgHssC052Jk56hhQoFOZMhMAqdFyJjWdCQ+wYrbBMXWPJR9aKQV447ALYKzBjR/+d+O9txHFMxic2PmAx0/2AuC5vS+a6U37NSBLu7p6U9iKXb4a3NBOclxd4vVA4WwjzwKHgaOP0YUL1ikI59b2BrtOHFwU5fTrhb5fcng0wjvU25tJFz+E1huSc6dY6W+fFf1qmw7BY+DDaC4KNlyv1hUKvd/8BZNL6zxOT9uvTDNgKGZPkqiymu/39+0hFthkvKtExNu3+L8/zX7lZ+iSyF7SrT38+6EvDzOcV7xjuQ6NX8evBgNTaS5XLhUYo/JH2UimrFnSud1JqNCC8GRXjhxD+Zc1cyYO924W6BrJXhyJTgr0ow77Wh3Yi3edOGeOXnvVazomzmhS8MOlWOopzGuanBIHWgXIfTEem7fKR+x+R0/WeypJTYs8Vkdb9BHIVTf7kk7kru/7fh2PoAc9s0WrxWXpnGDC4xWM7OLU0sthHF/KElp/xcrSGNo4ilNp/Snsdg5QCAjmaBVPJslh0Y39wqSYfiGgcUw6z1+iLbWBmremydCNArxiLGYgxKzjoUkHPkqbr2rk9bIzM1KSMbtmh941PXWKZdYJHBIEHLFrqol31IAt8e1mX+MOQ3/MU9/rbWIdKjEktfNlir10Ki3pNRco+auVjWFn/nOY5DtvvhhlSicYGxUHRWe/N2EaYbsstAU+kksuYQ41ePgdWRuwKww5o9FHjRP/ITduZGPTBtWpWN9rybyC+iMwW2c5nNAmvWsRJ0jKkvy0JYHskftlkb/CF+YaseFRqbIw+mGzWMgdwJAj81o7TFCyX3DcKuiv+UBYvcezFHra+wO5NJZyoFkN+B0POkbaZefP1vBgTxUVJUmbGm5hSFKOwN5DgrosJwQQdt1yD6gr9E+AF9oR+VELzhobvCU8qFUTaVAEBYbAqsQtyTH5rlZzyWIazlyv89BCVqwPIJEBX6uAdxWkG5QIUa8rZJBD+RYiiI/CatMaJIn/z4U6tK2h0QYjw0KLypo25Fyp1F0/i+W1qw+pZWSfU9OnIRETJYrIyEsrT3SG1dvS1wiC51H46zoxdSViHVCqJVpCsqzfLs6/Hz6KS5Yxxo45KqseqMEVrp/OMrD6Ay9K/pOuw9CwcQQlCQg0M3ynk6adTqoAQD/k2nOVcN+89VTvH+4BdrL+XrO7pbugwBVZH5Fe/WtAnxalD30+EUFn7oe9MWDv9g6u4oU+Ma4qY8qf3LtSc8q0iJWHeKUksYXNYaIQPfiBy0kXfFaNA+pzUPV1UD2qg5ECQOhvEBAQ0WKeZke2wE7qR6WFuUA1nVdj1rUb1jeJbemild8/7FUSiQye304uaVdc9b4E6vCwTcExgW5IUAkhjmS0Qey8W1GeY9rD3PIIoNSpYQ6aWZmbvE44RRIyCzPTDrBJOJg9QNV3HgrndMlKmGzSNO6d7vukaA2aPJVFT4di9mGCBDRyCPEkaB8xwH5ODU3uyB7dLbVVRyIlJXqFl8WA6vvwTdYGDYsP2szl2PWA9M1wbkOvxgntuHHJ19w/9GsqqUg7kWdxEM8nnyomnhanJINUEP1xrnJ914v0vw9dykshyyhWlV4N9cAiZIHgXCyg6+v2yAZA7ScGwFwU5Hs4pt0Tt4RfDnBQfzoOI7wgc0AFwF6Z1CL1q0dWLpGDX9vRMLo8oDFgr8GsgDxL0LqCSfIl2cbRfdb+4ezItYyn8gNx3b/E8TdIPejXUF4wxu5GxZL/9/ZG/u9wMtB5jGbp/hwrNAIHXaoKIQ0AVqDZVO1qIEOHbWdfcHFlb9RztzpfVp01pU4IaiT0PkJWwZCLkAxCI/qL2siEyTaliirRtiRtgnFMuxg6PncEF7vV5N8fLNljxU8F/PDbbk1DVIo/8zjvA+sv4ZCF95D3qsD2KStGfhlFEmn7Q4o0O+QsNoEJeHZwN/tpUcpbY488OXRhkP2lfo8blVwKEwxs2t3WTrgr8ESDp1HtUoV6wCaUZWOY6aMlFq9Ow51SaMUI598oRShEsPE8oSmCoUPw6QSaC++UypXk6xFyt46RxScxAMEGSJUmqhdLbVSbK/D7MpB5JVMhVXsszuge82vfbBbCss349LBFIB5VASLbkiZJvGZKG44rr/GUI/6SYHBPGrxvTCKq9zog7h8+ai/94k8+JQNBe55jDIYY48xqKPQJy2lkMgioQBzuCYXctZE/zIDWYFP3xoq+ucWR1wuQtrAnpjOWpNgnh6wCGkuKL6NNTAAUJC+Ord5+WpwFrXCJBj3RYSlPDAK21Yq8Gy9+dVQaak+6nU9J09OCo4MjGAOBJmdxpFwOkkoFmNv89rougCqwZT/T5KomjU6AoFOZDogtgKkQBJpDqmHOHEOZ7xUwZ9NOubXMYI8RhzHqBQlbklMRoDB6jx2uE0TOD0EAcscUCbBMM9wYPmFDTcFeX+VURU7pejDKgeNN/w9SQPHCNytmnu4y+PGxVOAUU87yv2cHuwXQKg5Lz/8P3SMXHazwkQsPo0XqyECoD3zA3qQ4TubEBvA4faNmyzIl09yYt00jKVlhrzxDS5bJeKmnh8t51pIheGmsxHWineUItuYY5FxZGsPtgNKEtaeDbnyh2vEHk+0KhaOZIYEiQNvjO4Cz3+ksjpxLUo0aLNgaryU0BM+5HruOj65U07Kgm6CFlP1wHEDAHfRFRH9qbHrZZQIWeTI6B/rQNMiUy3m6k2aNP4QhtwQqhFoAPCl7bMf1gCRfRdwr6JFKDy/lnMuHutTS5CDnyOlOHSVvagSF6owfgK9LLcQRL+uIlmRhUTMV7kcXaub67laFHFR+HwRQqNc0y3rUXZ3kKDNx9QGg2wUsMOxtx2GnDBxFX6DSpaFnJhCp6JBUrBhTytCzgEoe7K0HjcFiMDqeZc5vH798idi7sijmvdHyC0ZQMFrz0Ovrsx4cNcvaI1/g/RSyzfz0NTpq61iiwBL1C7VnpFjOqrn7P/4f\", BinaryEncoding.Base64), Compression.Deflate)),",
                " Rows = Table.FromRows(Source, [\"account_id\", \"customer_id\", \"collector_id\", \"portfolio\", \"placed_date\", \"days_past_due\", \"region\", \"credit_score\", \"collector_name\", \"payment_count\", \"attempts\", \"rpc_count\", \"ptp_count\", \"aging_bucket\", \"original_balance\", \"collected\", \"outstanding\", \"score_band\"]),",
                " Typed = Table.TransformColumnTypes(Rows, {{\"account_id\", Int64.Type}, {\"customer_id\", Int64.Type}, {\"collector_id\", Int64.Type}, {\"portfolio\", type text}, {\"placed_date\", type date}, {\"days_past_due\", Int64.Type}, {\"region\", type text}, {\"credit_score\", Int64.Type}, {\"collector_name\", type text}, {\"payment_count\", Int64.Type}, {\"attempts\", Int64.Type}, {\"rpc_count\", Int64.Type}, {\"ptp_count\", Int64.Type}, {\"aging_bucket\", type text}, {\"original_balance\", type number}, {\"collected\", type number}, {\"outstanding\", type number}, {\"score_band\", type text}}, \"en-US\")",
                "in Typed"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Account Count",
            "expression": "COUNTROWS(Accounts)",
            "formatString": "#,0"
          },
          {
            "name": "Total Placed",
            "expression": "SUM(Accounts[original_balance])",
            "formatString": "$#,0"
          },
          {
            "name": "Total Collected",
            "expression": "SUM(Accounts[collected])",
            "formatString": "$#,0"
          },
          {
            "name": "Outstanding Balance",
            "expression": "SUM(Accounts[outstanding])",
            "formatString": "$#,0"
          },
          {
            "name": "Recovery Rate",
            "expression": "DIVIDE([Total Collected], [Total Placed])",
            "formatString": "0.0%"
          },
          {
            "name": "90+ DPD Exposure",
            "expression": "CALCULATE([Outstanding Balance], KEEPFILTERS(Accounts[days_past_due] >= 90))",
            "formatString": "$#,0"
          },
          {
            "name": "90+ Exposure Share",
            "expression": "DIVIDE([90+ DPD Exposure], [Outstanding Balance])",
            "formatString": "0.0%"
          },
          {
            "name": "RPC Accounts",
            "expression": "CALCULATE([Account Count], KEEPFILTERS(Accounts[rpc_count] > 0))",
            "formatString": "#,0"
          },
          {
            "name": "RPC Coverage",
            "expression": "DIVIDE([RPC Accounts], [Account Count])",
            "formatString": "0.0%"
          },
          {
            "name": "RPC Contacts",
            "expression": "SUM(Accounts[rpc_count])",
            "formatString": "#,0"
          },
          {
            "name": "Dollars per RPC",
            "expression": "DIVIDE([Total Collected], [RPC Contacts])",
            "formatString": "$#,0.00"
          },
          {
            "name": "Contact Attempts",
            "expression": "SUM(Accounts[attempts])",
            "formatString": "#,0"
          },
          {
            "name": "PTP Accounts",
            "expression": "CALCULATE([Account Count], KEEPFILTERS(Accounts[ptp_count] > 0))",
            "formatString": "#,0"
          },
          {
            "name": "PTP Coverage",
            "expression": "DIVIDE([PTP Accounts], [Account Count])",
            "formatString": "0.0%"
          },
          {
            "name": "Unpaid Accounts",
            "expression": "CALCULATE([Account Count], KEEPFILTERS(Accounts[payment_count] = 0))",
            "formatString": "#,0"
          },
          {
            "name": "Period Collections",
            "expression": "SUM(Payments[amount])",
            "formatString": "$#,0"
          },
          {
            "name": "Period Contacts",
            "expression": "COUNTROWS(Contacts)",
            "formatString": "#,0"
          },
          {
            "name": "Period RPC Contacts",
            "expression": "CALCULATE([Period Contacts], KEEPFILTERS(Contacts[outcome] IN {\"RPC\", \"PTP\"}))",
            "formatString": "#,0"
          },
          {
            "name": "Period RPC Conversion",
            "expression": "DIVIDE([Period RPC Contacts], [Period Contacts])",
            "formatString": "0.0%"
          }
        ]
      },
      {
        "name": "Payments",
        "columns": [
          {
            "name": "payment_id",
            "dataType": "int64",
            "sourceColumn": "payment_id",
            "summarizeBy": "none"
          },
          {
            "name": "account_id",
            "dataType": "int64",
            "sourceColumn": "account_id",
            "summarizeBy": "none"
          },
          {
            "name": "payment_date",
            "dataType": "dateTime",
            "sourceColumn": "payment_date",
            "summarizeBy": "none",
            "formatString": "yyyy-MM-dd"
          },
          {
            "name": "amount",
            "dataType": "double",
            "sourceColumn": "amount",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Payments",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                " Source = Json.Document(Binary.Decompress(Binary.FromText(\"bH1Jdu0wsuNecuz0Yd+s5Z/a/zaKAIJyBF9ODUtXotgA0f7f/+Wf/POfksr4byr/Lek/P2X9lvz/fv6v/NQL5P+W8Z+fvNf87fNA9addaPy3nmvq6r+9HaR5pNT//PS1f1s/SP/pF+m6XV/lt+B242dcqP43lwPVvX8r7jf/oPbftA+U7vMtfxUeYsyln9p/SOFPrdl/5zhITj/zefJ83qkCyj/LPeB59Nzqby6ASoDODUvuvwmPnuvPdi98bjhr/y28YfNQOjese/xuPHru5z3+3iuv//zsWn/5W+Pn/Fx4+oNsPvw8A+M+yRmNPrM9xzqP6zD8Wsm/G8ORd8By/s9PK/O3bHzk5LDzc8Bm+h2cANlh/b/5PMpov3kBKufzuQ+DFyi/iXesDhr/zfMMyei/G09Z2k+e7o7nDUqZTaNcegAThjml8jt45QhgmZg/ff0OjHQ5A7PccGKatP078PJlOazzcfL45TucYdnuHRp+rxfN45ocOAjmndNvxu/VHEEOzPitxMq5i8POgOb1u7hqaoDw/Vrrv42/186ccti55TwDk/AdandY+2/Bg/bze5u/N36Km9L5gG2fcQE0z1qO0Ez5d+Dl6woYVlYr6XcS2/G68wo9n/WIr9vST01/yw7zpawzmRoetOUA8vPubCu5FQfqI5U+p0a01bMQ3eN0LvTfBKg5qPPtd9ZUaz1C56qdfjvevY0z/907cPs6C0nPOR3Y9RJnV8mYL205rPKeZZ0v0XjX7cCiL1Hq/k14h36GprrPhH1snbnWMbl7duD5vgtXjqnV1IsDu3bAMdbvxKzpNV5psybjRfoZG7/fFqy1pWftPWDYY+aZwItPc0bH7cac3bP+DmJncIYbnHNdLsm2kr4cODhy67wFt6d+Bme5r9/5/udJscOfsdl/WOLyTVqhI/+0b2JkvkQpv5kHQ3FQ4ZxpI/1WPOeoAcNlfVTt5eMcQ346VYzZL6bM6AHhiE2dGmP8tBqXRN3zt/JBZsCw/aysLzuWg7SX53TerRHc54fdQONU6fm34qvP5DAdRti0cNk8Q+K/zxnmOuz35hkTd7ylgp2+aj7MMybPZpDPlj0xJrM5TOuvnamCt5tnUNYzHc7P8RPM4bDGlTnm2Xv4KDNi2Afn7yS0ApRx0takrzPPoGw33St2grP34Pus9NPdLoGB7nX8JuwgKztMKyG3Q0k2RnOVs0nFTz7t7Fg1QLhunz2Zh85qAeNzdu0E6zAWt4XgjMv5rCB+hTXOc7lVQtJyfrCTmcyf7g9OjOfZJ7S7ruVAveEuRlzW/unuWMWUyHk3vcY+Q+PIEDafgUMXv7izw8RezibJj7vPwPgvgQMJX4JE6YzMdksPJOqsr4Ln3M1hnfOs56wlu7vDmr7g+UqEDpnzZwB+rpzzfxKcDhRtwPbJrWWvcCG2lpzyOQIJ7gji0+e0fvcmqUs/w50D3F2wFQjMDtRvZqxrHsnnkPkZbrvHOVHa2SXJ0lI957r7jtjRsP0sgs2BdoJWnlhn+f8Mt3zxGQ/VHXqcMz5uB8WayavYbMxpOlQzp+8uYphWwCoHCBuznnUHlCO0q1GrM1ZnZUZWcp5IL3KIb8B4GJyZLLA4sNuMXJrm+bBRfyW41V2O+TDH4XkXp4h2t3z44Xj2m7P+yS/y4b/Dkw/wXzsJ82GA45t2Rd/jHDBcOuepIojte3xPuh1ox2+1BXJOt8OLHurfz+RaJN2Hek0/Z7HSC4g8H/cQYY9y2A+HXByDQ4Wn4xlcC2df1YseLjzd9sLz66xLMf3Dhf9AbQTjnBtJ4Dgi45lCeRQtsXzY4HQ7E9CZznGkJ1o/s8WVUkpqv4uC5TBij4KHlHaUGBnq2TQcaq9aLn/Nh4j9oZUbae7noFhCzzB53gCZOc9px7MiH34znZajwCpp2ygeFuNRzPtylowt4MNj5rPzzXW/zuEqc8aJNg+tJAk827UDxWXO+BTR6nyozB9atCpwSukTHDIz/SzFSA0dG/mwkrnjWqtnN8rShNmB0lS9D8ngfCjy8rx0GoPiuXHUaETxpt1kXD5MYrX4QAsEWk/UHWj3HYcQTX6bwyaW/678cu0wMN14njXthhCHZ986kc7p60C9aj+qU1/1nPHhSjCHZcf8WV/hSizIPTZ12SFIP8sRSa44iln+5jmT144o1LgW1TmTd4rz+8zqetGjyL1eoCgoXRTvyMkjwuN8GGnaKXJOVw8mHr5XXx/KvJ3kxfiWabInn8N3Pxv+zMaS8jlFPUiZ0s/hRFl7zhqHav+oZ5AocM5G4sDGsT/LYvIQPrsBzoZHw61qv3qos0Nl3AG/1Ec9pxoOzXCUTOP4ecBy8czRc0CRnx3N4sEhIX64vEwv56jAiRo4U6ngoPzqZ9d3cNW21uu99Y5o4Vl8tmGN1NmDHWyLuR4mV7nUD5/GeR1J0Fla165SPCzNgwlHcXaEkUezfnp//GJiuPzXJ3tOw6br7A/MY/twuqarR4R5ps0zA7Ry54wwjSLn4i4UQ/Zotd4k/s9NfkAn/nbk86Vav9vbwoCtuFLaoWm0rJ2R8ajITTnDRWF59t4HzZSPVdwwr/rvxedbZHvjhfFy+yOYwU5GAvPqHjXudBaadrnDunP2R3XnUX0EOL/U2VEcbGtt3DsvD8re08e6b7wjSvNEOl9xyYKWwP3/5gAei6KY6+lsKg7VEbWhfDkDDgHP2c97WA3O/qpveHaVgPJ469e6eEi4QzV79lHqWjJn08nZH7pgLrVNaYIzRz1s/GPCqEl0PhcvcMJsFG0vjzaeNjiKdJxvjFZ/19NZEjR8nnHzsDbEepQhmcIZNvxv3PTGOavI8c4ff3L2pJJUfy4y65JqRLlJlKZPfIjMg2I9HAkhQ2DqHtV3OPRh/mY9FkZrPZ/p7E/6EuUspVw80wN8TsffPAgvD2tmljq7TtFDZn5ycXZ20qNxaJlufmaeg/WlZjMqXc7UApX8GxJImD3ztdIWDEFkkmetFl1bPSgNs7H7EGwRxHcaZ7y6Lu0elUFnHoZKul1op/Y2isrz57dwOGCqLg/hO39YWhIF1uryqqAMQ4xgjJYXD7DSHLLI14XFujzm+LM+RWYKbNbBeIklsZY2iAKztUf5WKNJmhVYroujFtgxYYajcRqm67KfOV20lgpM1zXFgczYtmTYhvG6esuFhMvhbnrm+VytY7PLrFhgwfZmTmqwXoxaF5ixq3fhNO6J56UIw5BdnZTgK2Opat7ClF39Ou8gCtK/5VwXQOn1Jj5aDmvP9eGcmQyEE+RADq4akwKbjH4YQ+a3kEaTb9IZU+rwsLF+WEL0YNOjg5OvH9muDaZiwBx35xZy3QF1e1Bb17mSxOgofw+K7Y4hIldajiB9JVWn2tnPf3L1MwtSox6Jzbdp9UExyudac4qckWp+a8GGWGydHe7uQFmo2mryYBzqnl9D59mcJVLKoe45WDQ57Q5n0jC1FeEsa0yzWdngNfJrFAzhUtOjhDxqfpWVDl2TKweuI8/hQaZhceALHwrvUPtlWOA1NQ6JDzBn9LrfqDeP3rVWTVicoxO+nzjtikxTpQ+P6Xw4fFrv26cHNWuuN6j0Fe+KWXPGeel1NhZcfB0cs1q+h8Q7tJKkNRiP+a6Hxedg8Cy0EG8bCvD47rl45Xm3acsu4PH9NTAc0qvPDx7vDZgc5WHe2AIi372jg/arZecVmHz3uwYW2DQ7QQGT99ZPrt11DiR9AjD5XuP3O38c994YLn8kYbiKGTcKmHz3p9mAMjQzZwGR7w9Tz6C8dEsXEPnu2TRYHESyjh0w+e7PLHyKNuzUAZEPF2OnrOexyTzA472JFUdW7U2yvoDGd69nYZWHs5RvDBbf/Z6DI6vBIKyXWvFiEmY4N+mrKSDy3oIr464ZrwqIvLfTcn+HWVCnA5j8a8YdcK5z/wCTDxdzC4d/VPeusFe5/Z8urWrSpoDJv6ZVetr52GDyHqVp9ZzPvxwwMPnxmL/G0R9aFSDy46HMDd47vdPyqAz6q16aBybvDbNkAKlnWZMKmHyw24K3HGUsggAmP5yqpj8AnheCZ7TGEz6wz9yjAbaAyHtT6Wf34RQAkQ+GVDLmKvNkAZH3Vs9EZ93ZX3Tt8Kg54pPJiwIeP7xBBMzzfGGtCPB4bxYlW6rYfvgZQOSn96Jxj8iyZFXw+Pl4XM5A0pcNFu+tphjm1b8rz1BN73OBsQpqiv5ssPjpPdqyYOrjV7D4F13n2iG0P3eG3fRMui0UYQJ+Wg0jQ9SPFSQ+mE4n3dca5woO71Hcuv2hO6Jk4bXaiVdB4YN5VGaAptlRweGnn3aFzqvxWzhe4PDziZo4S1wRBeDw0wfPQHzaflnB4V8wm6OtgsJ7UDpeE6eCwc8nuqbWKUJTweA9ShtR6zKKVxD4YHYt8io1ofu5M5TD0bRcgRUE3ltleW0yA1MFgfeGV87IbJtKBYGffikwImjZNwCB9yj36LptjBl84j1hjU4k2QYro0/8EuShZYqkMvzkYQ45VXPbVDD4YNbVubNsRoPBe5hXn51bPuIKBu9vzgFpZ4FT1VYw+OUJBCn6lBe8gsAvv82ClerMquDv69m/z8LVAgZ9X36pYM+xMKkK8u5BWReLzQ1w9/Uc8IdYKFgFzH15BwQunbItVhB3b4rm9ztf1UYCzH119/ErdrqzDjQQ26OakjtZaFEFd18jDsQ53G6YDNj7Gs83gFrRBwZ/XzMO1YRTir8M/r68pxuTY9n+XMHft7cdcQe2NwZ/34//qN8QgAoCvx9yuM6N7Zkn7NORHB7F1uSCriDw+4lVoeVxKqII8U2PZakVnZIV/D1Yu3mmmGisoO/7lQbT/NAV9H07ZYfRaKuLzVSw9+0pGnxX5zMocBDs3V/LL7zSfSoMlv/C1EnZJiXou7eHcw+FVVtBWSDw3phOa0bX2V1B4IMtncEDrYljVVD4YIinq67eNwaH3352wD4zEsV/BYXfbj/DYOEr6M5g8NubYRPMjjZnQeD9pSSkqdhpBQK/97sILdaqgsB7FHIUhFTbAgh8uBbqLS8LNgOBD9c2WfGJLRg+3WzGQmlzK+SqHjIR4Y4wGenyeghB8a4Dvmy+0Wj5gH5PgUQ+clPTZpaI8gsg4o5ypc76XAy6cQ4r2s/qOVkdaoET7SwUCpJ6jsDiPQ95KYbKLh4erTwH+9l0OI7nKHKgvJ4LwSMcx7kimhUHqSN/YqQenbPO5xMHWsmjJnLnrnI6HIYWYcXkVFMydZV4b1m6s/yIdWGw3LFPpwIOFM2N1Txs+0aGnYNDvTBa3h2bZPXR3r8wWl7p4Iw9U9YeG8Plz+eGCNsl3V/XiqiEzmV2az/XDkzZJhdO3RgvF3PC4wpCmK90eHvJ/0SPnNHUYJ9dMsLFRrMr3rF6WJwjUxjq6ubhdi1ZTeS9boRn5jj52iH+jLqqZ1cp2R+ziGhK7UZaTo8W40LGKg53jyDD2CzUq571G25MvYFth4GKZ4kW71YQYRkmC1rKHta0nss8XmcHelBM6zl13LVUPTrMBi8/SksYK+9p2zQNdCnKMwf/B5zOUFpwKQbriS9k8GHWS2G0vG+gMBLWdHRLK8I60yoFZ0vbg2ag79Usii2n51qe/4e9M3Q1Y7j285l6MbnacvFwtgiSw9/1XLl62OxDMKYIPSNWnPOIkqV83+JQeJitwylekty87YxVAG/kk2Jqz/v8e+nR2EPognsjjtYZBgnhdp7XoVpQHVFBvPZQ+H/QcigPeUk7b1PKY8Kp5vFu54FKeXbFemfPuWe4kkFVRv9aaRGkQeHsWlmXYpw8/TOjIXfEVoZHzTDULcq0lenR61bscqG0sjwqS1kBr9DvYqC8ORJT9uxL9IO0mjyqJXyImUhnqzmi2KfPz9Ib0RBIHnwVtGMYN2iIJS+v2aeMG+CMcPLXW3GW/5IBryGivLjNlEaQdO1kDTHl/zgkZrJTryGuPLgzmDRQFHPTEFnuHQ6ZoqPpHG+ILa9PFMtZhPpKh8L/A55dmBtpOwQ+gJjNR4DRT94OfS/1OeEH4tmFVo/KcJNhUdCvtojyzFoW/npownNnOuhLlW/uHBI4G91WacqAJ21rGCmfJ0FnZrdTqzUMlTexg2Yn2aNbw0g9Qrgjrpij0TFUTwRSvp+gZw/2z81FkdV6eS5NDNtjrH3HSL0GwXYeWB/osPfS3DkKMwW8MjpzDnsvzbM/RpdZ0F877N2hzTJsksR5O+TdocVilJKcwu2wd4faEix2xJ7Hgz/dETjuoIex0gTaDnkPsGIYYdrnYB367mCZXhC4NpRGUDxqIuqgeq7D30sI/kZMwbJMkDaaR29M3OGHOuwGhusJE55nt6NuaGN41KzRG6Opi2e82OI9v3fGgHkPPI6cu7eDwgeQTgVbK6Dw7YlX6VXHDRh88zshrHrnbE9Kqige/dNBOrtB4L07SU7sbK8DAt/87l0k/KrujJH6ZmwWP1tnuyKJaiDwwdnUTLFoNYDCv2HqCNXWOIPCB3cSXH71nuzg8N5jxIyxcRchOLxHlYCSxSobKHx/dlEINKqOBgYfUAZbwnInuOJ8igQtZ5gE+X1B4YP3JstRyeECgQ/+F1CdeTYlTXgweA8rNLfd7QEUPlw9zZCpEw0cPkS+d2UVaTTB4f/8Mzrv1tnSGEXTwOGD/wW5Yck8Ug0cvr+OvVTuYQkO3x8fah7X8tvA4bs7S2kGZ3w8Hwwc3ns66IJJOC+Jdo/Khn7Uio0nKHy4luLiDLfmPTj88O4/hEGbNaSBww/voW0iHppA4PBv5PqqmgIdFD6AQ/47focOBu9ROlCSxqqDwA9vZaGZbf4KrB688X3t/moDR3S/2mR0KEpx6hE1ek93ZAd7H09IIk6sRHB60CKosJ0xAQrU/Q8tYva732fCMHn/GfT71NbRwdwDuGXkpKWjg7l7F4aZR2lu6uDtwb9BL+fSHtpB2+cT1HEuEbnuoO3h2qHcpKKHOuPkvRTcvadNxg7aHlCGbDStzw7aPl9Sv83y3kHbpz/NGL9Q7cODtodrmz0VrwVtn68onDNreXbwdg+LJh22mgQXD5tjrS5Tqx3c3UePU8e0OyNB3r3/QxI7i+t0kHfvp+D2f07ZpjsPjw7FMdTSdMx2sPf5zMmzNCyuq4O+B1fF5EJJArcHtak08813kPf5hJNlzMosOEc409DZZbvtoO8hvByBsmd7n7oWg/UwNHj9tzL+WkQV8VMVTNJB3tcTMrCb+dY6uPsfmhUxWJOIf2dKaI6DQd8LVyGTQj2B4/yo5j3rzAst8bFgBtFKA3lf7sTCdrWapUJ0sHePMj7mLCby5A767sPX5T43CdxB3wMK6+tRI5o7oO/r0Yw55SV7ZQd/X27yKHLz7Gf6YYyWTz5P8n923Rqj9WQBM4tN6IookyGnsrg72Pva71qC0OV3AH33cFFy2bJkURD4EG5OxztyWzkgYPD7OaKPIjMzWweJ9xb4dCWL7t08asu4W4h8B4ffz+EA97jWEjh8QKfCUfUVweG3sytiIQ4E33P7AIf3AeuY8nBH6NIzXNuvFshCOGc4WmDw+3GeD9A/zngQ+L2eG38ghsoPNFV0tsDwfgh8DdZs5bhrOZxDsvogemWI20o6p2AEecTaEj1HWfV2cJqUpwXA9nNaRRShhD3fR1oPWpSarRvvCDKM4NyY4ERu9mtCH+d19AEmsrMfnbvbPXVm8ajduS1To33W/wEjR0dDNTFUnnCQzQ4R9D67R5sCK+fdsSYGyxds6LKRkDbM6UGLjz9MZujS5VFZsiciFPTM26PZMlu6LaKzSdb8hFVOpEJxDZ1tMKBUdinZrDo7WfUm38LYOAv27QvJ7N6MwRQV5MHr4uZh2YuRBUkx21ePKP0rN5LoaMufmr2kpNQ9R6Eoy+HuNYSaE+5mtuuHu1cfEM6RNtd6P9tR9aZZekDP1ErK7U4RpY/zrHyahPvGaHnph7SmdY/CXTxq3sRWLOup7xovJvk+G5Iy1XeLqIRuMuNc3xgun6eFA+0oXCOHG+P15CHDK0Bsekyb2TofUatlL48qVBhbrM7vvZ/7TrlPacwYCYP1ON+qTLYjZY/VG9tMZT5S8aBsPq2YVB2pxksZ+oK4SKa8nwVWQww5g2rOTteVgN89bJnO05bKkekRlbtgW8LQSDPCNAshHoB7x0iomeDNIMywNp/QSNujFhqLwFne+tD36u3B2GRXslDecRZZ9VHm2HZglichGWedOPRade04GmchBJRmodYt3G/k9sCM55njFiXAeD1VMPIRoTIajjw8fKnSebKh357xahpYabHSgy8PSymNYua7cb5x9aUyFO/TZJEaJXnUmMVcFrY7SvawbZgJCdi8d0GpiVePIh16qt4Cik2UODvPtmFDdr5TDbHkzIS6Smyc0ay+6EbhS2dtXeOw+Fpf8dEUXT8Oh6//WmjNgjPOUNXXugtT+BK647V0+9xLK0brSZHpqI/CRVGzR3X0tDokl0YtHlWIG+uuEMRIPaEqs1ku4ajNo/oK68xMeygMlN/TyDrPxaqGVIeHNRjjKCn6bUad8WKx8H2/UcVYOTnMbJCzXTa98PaoDgjUV2DYx0BxF49mBmfIwDJQ3KX6QAaGT1XlbA5Ud/GGY9rgDqhFjvIu9bW+7GG7Cyq8VO/axWlaLalnoMhLe2YsfH5V6IgoizucCauNCYVe2rPptZ5s4qDUy1sM5GjSLY/SQLEXb/qVFx3xwHxjlHsJMFzw5zPwWpR78UZlevdTuzMLBV/CtQy9s/D4gYovwfQLBnjOCK0j1nx5MjaQTqblz6ovj5JCaReVRUHdl/Y438BbNFqo/BJMv9zGpUkHKr8058rA3Dhn2tZ9MVRP7aZ5RBZZyUDxlz8089J2OIuKrmQPKp+3wy7EcRwYKGfalRm0mW4coO8hkYCGFOSh8ROBwHvLL0/4ZXEOAww+1AXBGp1JFtYBCt+9Q6Iol4wWqQEK/4eqFlf5PhEovL+WzplDz+XlHCDxwcLK+hAWejfA4runePBz7XtQg8SH8HgQGqgDXVs8eufkkIVmgMMHdKpcEA1aAxS+v8flPvRQBx44fIiOp+/9fGMG/A6Q+ABTDG+ZWQZYfB9xHeKwnLoWw/X43vsN+B1g8f2hcHk247QDNN6bhXlyYLyEYrieZFN4/ih2B2h8qGNC941MkgMs3tuESR2T7eDg8O99S77LGxzeW4ST5XRqeweHH88BXm9lgQEK71GFQEx7nfXcuFqyqAoRbRhN4mLZ55F1OoPBjydeBCHZFCUDDH7UZ6GhMoRuDQofYJyx9U5KMPjxTKw67+YPBh8i7ulR2rZGQeDHw/BYZkfLEAQ+1DWRb8eWMCj8eByo8DVrfweFD9VUFJepQwcM3puNFcKQrBjgBIX3FUNsNYiWTpD44a0KQ95KbloTLH7sZ8YicZ+sdYLGj8d1365PaYLGB4P1UBLiINjB2eMOnVO1tO0JFj+9BOCdTVxMkPj5mAcmInOFnsEKtmFGoFtk9QSHD4HzJG+dVGiCwgeQpQ6lhSYYvC8MwhB0knTBxcPm2oPNeQmu8epC37ysURMMPhh+VcasWOVIMPj5+EDzWvcrgcHP/r5wn4phn2Dw4WoGWLR2fxvD9WSwHo2vA2CCwXubMwuQoSIEXwoMfj6uKkQiacBA4N8SIchuI3ZGaz0WqXUD6yfIuw8UZ17+6JbbMsHeg3WXO7jduEdMdf2sbuEEdV8vsU9XckyQ9+VFA5OyknlKJth7uJrWH1N4E+zdG5X1VEuGtAn67iPN6dVrKdu0BH/3seZZ5YmGxM4EgfdXq7ToV2QNFH452cqtdl8NN8Hhfaw6kyuzGXgnOPxbNgUma7KlCQq/nLBg7Oc5s/jKYPDrMcNk5IprBwCDD0Hw3FzOBrEFbw9bqsi0jK4JCr+cDVaxENsyeidIvI+Cp/comyl9gsQvP6nhWTjTa+vaGlHu8vV+CpD4EEBPxnuEPJ0lEyzeF3zJSmSsCrCboPEeVowGth8OJ3j8eoKsZrcU2Qkev17/fzkzTOiOKNkWnKxEweJDORmmQXabAqDx3kyfVfYh2TuDxi+/0SPiASyQ7wQaH2z8lER30wSND0kDWTZRjhZY/Hb2xW84VFsPNH4/ES0tV1mmJ2j8fkJWSk332uVRS5MoIh8TPH4/62nvIv44WcTxqfqK9dCE5ogyGKLJ3zHB40OJnMHqg9q3wOJDKRtmyNqnB4ff3kPDdBJIVl3bPdwvI5qy4kyw+FB9h66QqWinCRYfvA4kPVRwExx+v8pjNqszMMHh93rWsIwZEwzeX0qvfreyChO1Hb3jQIHfzULZJ8o7Br8CyiY1ZTFM1HdMKX7aPpQMPlHgMTn6h+OQK1+Xdo/KJbGQ3CZ0IO8g7tG0wfNlUecxeA5U0UXUcaLUY6jrg71uyP02UevRR8iLCmeN/zmswpWqIWE2lLkwUC0ugrIsk2iu4lFZWJAYXVR9snpUBG1biZG5MFB+HlvAnw6k1T0qrbLXljFzrhFROlBR44hGkrnmczF3wW22jLkwVG+aCaI2p26+PaxJhdxGbXM7xYu5CU7LQJ47e1R7wt5T1t+5MVqP3Yf5a2Iku3r4ph/mKZ00d3uuZgA8viJHbPcIc7faR3bqwTBibwXmPMxZOc/6ayE0H9b/w0ophudZRi0/MVSYIfpUh8O3ELfPUkISFuuskxYC761wAq3l6yyFiFaLGaRGW2ctBFi5KkU7+zpzNqCMREbVbF2L4rN+PdDBCk84a4Om7mGLcV9n+jHKYp1v6GC5AFDIqqg66oyo9rOzGza9FYbr8eHclOuVMFo+U5RJEKjCy/HKycPDfM59cDtcOT8XkyBWS81aGePlt3Bah6q2vJWrR7WnbQSi840zxuthDhAIS9diuJ7g+Yyi0kU/PDws+nh+71fg9KAFYKIcnH53efRWRr0lxdaBmq/ow8z5Gxy0DtJCMW8s1W01bA+Fb2+l74LCg4wrWYfFR7jI/sOtax0W38rj4m3L7NnrkPgWHDWY8rDDCe3xWr1SGfeHB7xJbvZMedlZqGIdGt/Ks8ufnYvLdB0SH0DaneZ95B1BpaKIF6yKkfJEWaGKlNlnAnmwWB1AK7FbS7wSX2DZx6s1YliCu2uDXxWD5G2VyVJj9JvdoyZXzu5qBYErBsmHomWNsO48PSiLUbEs/lUxRt7pQ2Yuubnq9qCV3pxWUH61FFHlGFgl73VYe3sD7gtIAc+koys8LB1cUjND1jq8PcJFzlme3uvw9lYfqjlFZNYh7c07dChyEfDFsWjDo3amYLJpmNv0sL4e9t+ti1E12yfdkbObAXUdzt583LzVC7Xt93D25msD0UuKonhCc7xWZ+wt+Lt6iTATCZfOqtUxVCMu3JmshsOhcBHFcLRbqu/IcNRPiTSo3JS8s4/+tPpPDKlVB1iHsjdf5KeowtctbX04u4MtWiidqUUZsvr2cDP4CEZePFBm/G0tcF6YNrKF4uveE6EGIGZQWqi/HuqeMz1tmXZfKMEeHBWqqGYkbKEKe/BUyKmcFMm4UIq9edsObfvDgkYWyrG3h2n1Zkl3CwXZ28P70a+DGnmhJnt7rHdnO7Ei2yzK/vqqpsXfLJRl7z6ADlbyblkMi5XZHeVIxSwOqlAO9u6juuWEh3OOzwX+7gv2cE2Me+KAwPuCPczoHZa1uUDg++s/TeL+C/w9VOTJOvinXukMljf8y7uaLaVzgcD/2e7lzDgnvw5+EPjuFhuOo1tPbYHAd2eqwMGOihmatiDwwa5/69bRv7bA4H28N81gKEHJkQSD705E0ZVRrRbXAoXvD6k86tUoFih8sM6zlKu8XAsMvj8RYahAoO0BBN6jFM+g4Hqj5VFLX4SVQj+7Ycd9qEq1OlAL9H2kOFbwZPHjgr2HaG7lVOo4A3l/Q71LN8v9AncffgVPMhH70RZBVdq6Ux3EPaCo45Aljhd4+wuizJaWPmh7qNDDs27NCy/M67gzoEeQTiTw9mCYT3Ks8wDeIO7jUeWHAG+B2YP9Vq2gd3uDtb8Fyc9teS5skPbxHMCoorN03xZRJuMUi23d4OzjNeXsbEX0QdlDoDgkO9r56NrpUStodb4tN8ENxj6fcI1SzEa9Qdm9QZ8GOcu12CDs8xE4w4zfG3x9Pt7pbOfJBlv3VyqEgHapDa7+1g9HhpcubB608jojm/Fxg6uHIjeMai2WD7XB1UN9cUbqT501G2R9Pp5NxhhxEWyw9fdiOPqzLsZAeXlCW22xQv4bbD2U12HKC4QAPwL4enAkqPXQtMYE4Ovz8SNBn3CgQdeDI6Bxr6m6Mcbr7Wl0mJtNSdB1X5GGHuhmQXUbbN27CWhiSoebcTDB1qfXNk0GKH4IsPX5sg14NtUQYntUDAm7Mu8Lur6835thkTxlNti6D+JmcV6UBdGVZ5iCMZ6xtAp72+DrwZCvGuQ2wiDs6zHXjHwnOgh7iPAuulatKMDXvT2cXo9zKuns22Dsy7t5ljLd9QVA2dejTHEGCdwebJb8ZfEfG5R9PZL3KCxR9g3K7q3ODE3LQ0a+DcbuTcPJcnu30OrRYczZZjr4+no+7U2w2iDsOz1rqCXphA3C7uufJwneYjMZhH17aQkL4b5bIAh7uLiyPKK+Afh6ADut+1YQcIOw72fesE41XxeE3dur5Wc5SoFn7gZh3971zA40Okk2CPv2FJNmnPzBDeEtkYEgkooccoOx79eTUobZRDco+/Z7ylSEF2XtBmUPF3PPqObE2aDs3mxttGlrPLYHTSpMMoENuv4WuYHJgvafDbruLdYKSa/WGmiDr791amh4IBvY4Ovbh8sUFUjQpgG67k3ajPDplkexwdY9ynVU832uEe/M0mnT6pRvkPX9GGkQxG13XhGVjmwKLNkg66FUDY8FC5bZE+2CnM2bjlYoH87ZmSNqYau2658TsKc3CMv6KexzygVQ5R67nSfnIOpvwfiMaiTaGs5ZEmCO87dPntOi++osjGkdJiOP6EPsSyQE59ZWi2SfA6Gnx4FXMtQtJ8DZ1nuozsKFWK2+1mZ3pcdCgXA4rkO2V/JBqTTUWqjFRn+l5M4begiWCa6NFkt/qJ1VYLfk3JtdlnwRLBZYKFaKYqPTUiiwgv2hWjjsRqul/AjYI6myrAEbzZZeY2xdtpWi2VKw405WX6K3a6PbUrhS+tQ+ItothYh3VipYxmXQcCk/XgIERGjDQ8+lYNKUY8PsUxttl/ITtrZRQEGtjppHjeKelVZ1bX+upSX/TGoOxtk5enksRTlVCzzdZ29wsNUawTLVO60HVdKi5efuswp7MIgi+adaNjtcvej9EX/6UCdrwJPOOuzBNMnQldus7uDlwZXEb51/0mHvAWa5WuyZBp8xK/5TKgnslu9PCb28vBuKxHVZJOjBMW5vFcWeLKPj4Bg4vyqLonLU6yil5WHrv4XYZjVuShi59XwVpHSqO0XKyePqMLGryYsDZw8X2+RU1+agxaNWFY1BYRrYQ+h7iCbH+TnkaIYRwKNWFqcc1rbs7t3j+m2G2NiTow2aj3S8BS4YUAwbFRayW39VcZJLA3MmcoD5VefXm+uw+u6NhCwoMc42q3E5k7H7jouqRmHtDc6S8OiwRjFn2LZdXeLVLL7Rz6NbJ66CcWvPN0XNN7u8PTBTvKzzQioYtqdAeUP4mEa9DA+3vwJdNh3L9PjNLmjZGoEVDJtnraT3eHS7/X5wFi0TJzq7AYbtifKut+zMgTFu3vE9maenZjapFo926wvR7IvU6lGrZo1YzWw/3Tx+y1JY0RoEsqGKe9yt0VfERuW8UvdmUIV6HpnWNCwVbfcezwkkhl29PFqtk5HVHznwRlS5W+EMBpr3c5/f7b6WB83kh/8m6wWXPWyBt+ZrPGiB5dKh9K5b+OuBq4dF6hAC3QxuMI5EUgdDetVbt+5hTYY2rWgSYs49fMPc0t3YGsbMy8hh0eT25MvD5u9Ap1BNtLafq0lHy92VD+/v/TF9nHnarRNMOsy/h+6LjCtoFmV58DNuoQhGlxXJGvAd8t/7s/7n2dls1z3kv4dQadigzFB70O5R4zOH+3e7eMSLlf4jWX/Q6VEFeOO9rOPgIf/dt2qkEp5WauzA6PL4tjiZt7AbLPcRt0P8rpKRPZytXWxv9yAexeNFVr3e7pY8MGp+fatwhPrNpNEiypCmdTeW0T1qtSGr9blJYzx3tu4JmogDY/aIAKQt3bdaD1zVscq6G47tYfPXIyzDFiCEQIiMVgyYqZeDo0Gm5w9sdlBkJDjwGbPho6K4IaOFj7VlrGgu62Yiu6fWu69BD4SK5DTG/G3IEATDue2Z1HlWme0PUASjRRjtCW1HhiQI1TwYA43YKsErwslSZG02QRIMb6MXy113V4UmGD3ONmhzzRaIAn81T4NkZbcOXDxsjwYVrBeDLPBB1hT+c97jH7LgbUtJ5T8N7/HybCUl7LdHRK1tyu33lCAM3qLqjFop9uLL49bsA7ZMoTuiVuH6O8LZjfUNADtX3a2RHVnfDuJjz7scIBFCX0n6ztI3YaERgtmY15+nt1MBKmE+ZyWzF/XdIBNCKLgKDFjI7sGHx5Uag4rz3Z5+enhwThU4WOy0hFSYnjwVlaa0OQWp8IaL72SvhtZzEQUjLfdAQ++5HppUqqOynZZoMNe9nZi7vvmkM5rAhYtJ5BHPOQRj1F7HMjypaoWIXmv9n6hvcO1uzzbi9bS/tNuFN6PhmsOr2dDy92oYNn8wyOVZ7GRA57Me4saZ3t/NQoe0CI/LqrhuYy2Uh/JwVi4FGtlpbKAUQuF18IxpgaEZfcYCzKvHzF+b2OZxyyA+i1VTBg2/IswTc1qeB7pK/PRQ5XwwgkQzBo25/kHRbGrazRcynR+2vU3IZ7R3DXC1ioQ2LhAK6/GfM3FaV0MprMcHM6wmIWL7fvqfQdyqCGCf6IafYfPR78zltZScjAZaDpU3uab0ddftOOTie+VV+x00CIX1OuDbDavNaPYarqc5qJmHNaPXVbhc03X+2rBg1HzuBa3u9X5v6ITljx0cWvX20kTPqR7s7vhi5Z6Y6DnVvWVdFU7Wsv6f6PkacG5Q4xY6yGgd1d967UjeXvZwPcIqkdO+fsfQCj4cnfaZVG4HTDRyiniWdcdmDMRCgOEsLNbeGd1fHVpvXwx1EkS3pu6D1RWSdnsCo1+Tg4fZymu9AwOxsB6D55iKSs5o2NS9hZ9FkpsV2ctoAxtgDQuop+AeYWWeXA2Ehk7x5kuZaYaeIQvtU7P2/KapCKmwvb5SRco7KPtBMWTVii1ktEDqu8R5XubtbY0WSAGmpb51q4aHYo4/fT/epT7G3bUhFEIlfNCQcoUCGgp170RgDsC2AhQZPYG6D2zP2xo46b2hFEJUPAty3eaPaOwTr24K9rP3xqC9GRf1bmsQCv9UpS/ftgadsF9Tcb47KmTCfhyTMOfaAoFKCNZ+ZdZ+964etnRPBAapjTFa6IwQxY4F0vb34z3ClhKUbyPvMTx+ExzGHdMx4+WMoEepX4PRKt7PRAYtKTE/o93NCFZ/StrLAA5nGqGQPMf0a0WN3jIRV68+c/tkdJf5B2/bgt6QHhRh2SiKFXvO6AEzgueAEVXb7OgZ3VoCTnazLHYlo6vKCGXht/KKtC/N+aBkZcnGZWLUnvRuuiRtYPYD09Gy+l3fK3lc1IlNTrWtrRwvV2frZvoMzUSGd2uw9VoxnYB+ISO9Rop2g3whCR6cRu9U7im7MGozTreC9koal4VRe/rCIBxs291nhFVvI83vzZfHLfzS+uRkdI4d3jFiLU2SHbI7edj62cB8Y+N2NsXhvRsKGrWyeRn9PUZ+NsaMyGo92tnV/oHR2VsSB502AqxM1GvGQKuN4UPRubO1dEf97B4RrrJD2KAfjRBgsqrrp0DQG3qJPicwoxu09R2NEHFRm23UCE0mRuhPyyR6tONUm/uEgfPzldm9687n8+efEQoHkeo3029o2zBCxDojbm2ZorfC8NXiZaJJ22yoaJ8w3k6z7BUnyzX6J/yDIxN32o9j6J7CBPir6QS0QRih+BBdXlmx+Ci75WGLdllWzTyjV0GAmdZeFNOb0apg+LB3Vcu9LUkQcePxIZM9SpZvwRWFtePNWS9XA3O+2PAOKDVvX7+Gdo/mm7/cjCWg9n+4WrZnqzIBv/7PKA8DQcC+zYjzziN4oLq6qSR78u1hK5yRxn3y87vhapIfdJ7Wbx9oFG+LZO+KZX7ZjEL7AZcVJlkPr4xy+cN7qJglNZXXhQpeUMBuMaiVz3XDoMHsCLXv1eTVuj3A6oHdNDKccYjdtnebHraa7MMSgzPKzI9QR6mqUrHoEyrFh5uzasiNjsooBT+880tG4GTZzhktZkfoBTx5HttKqcWjFgWMRhXFcIybL4POo2F+c6I2j2tk+rT0zozq6w62z1aLBeRmlF8Pt6d/67ZIyyjAPspzNIwbtpRRRn2EiP/9H7V1FotCKfVwOYPp9jfuDSP3xPL0m26J+BkPi9/NQ9GSHv0IhREce4xP+SbkUQqjPrGDeKG7hR2pEHBucQid0amIIuCjeuWqNNJirBnlukeI72d54n5NJeg+O3wpKdKwjirUGpujF0bw/TEKu1/fIAprD1/0icfLsCCKjNrZI1R9YjuAccfuKIYAsxBusgQdlMR7bs5ACIs1zChwPXxVf6XxLSUrZ1S4HsH3R2q9LQoLzteIKw3rbw/tGLrHO1iaWpxnNKId9VnLzfJwMmpcj/qsFwaJC90eHfoo+zqiUKY6XKy6BNe0hnrSwzv3OB9HNrqAZrQj5DCoYoJFpiGP0ePy/tV0xxSKofpzhak+4+6PUAzNOZqZUNUtMzKjOPTwnQdUW9o8waj/PN4EiYIgEKHruVblC+5CgV7wrQdUy+UeSdALzZl/1Dis3lMDcsF3NVAY5rgvDbXgew/QB9U+jgK10Pwa4lkMdaiJBrXwTwdnFnOzh8OgPdZOJLOIoaGycYAZB3+ONKNAkAuhVpT5zzSmkAt/+RdyM7Xb3Rupkj+jPRER7ZrUUIF4tOdMQLJCNxij5uNiuwiM7fkQC23Ge3foXru6evgmBu+78UAstNe/Pb4xh1YIBf+xM+RyDwRohVBSCoaKz3mOzrQjlO1n6ue2GLqM3rTDuzStquC8KxBqIRSdUjjbvjQDcqF78TpVOE66Gv1ph08gYQRuv+oTHWpHyBGhujw0QXYUFA0eobZU4lFs6xdq4W3MfGj6x7ghF/ojL1FLzzgI5IK/nD6DZRluyMD6GT6RRDEy7R43kAsBZik+M5qhhO8ILZJBiNe2kKmMSrzjnw7LNywBFXPD1bSjsPaRYIzaU8i5nW0vGVwjzIjbdtUjCtuO8RDiXawHe0a/2gAXdR+x1mMZBWodbvyHFewMP8P2Jn/AAadvhp61Ac40R9yTBk1rx5tXcij83QLQtXb49gSszTmveRk1bof3W9J6fTYQMWrUqR2+shNjxeEwMLhGmN6KI7sVUoFyshHOiuhf9tv9gXFe3ASgjJqwI3QiUD2yv0efHrcsT9ITe/Plcdtay+1TlFFoNeLc2Ktl3UDgI4oq0qfZLXkNThcPf6koWQ8PsTC8/htKy5FsR7XU4T2XqrRi6g/VUuPFrHxw471Q03R4x6PaFlwlgU62w6eysIREuwoMnWwDTF/ImS/L4IXSPZHQIhWp2VtvD8sGPJZVGM6oSxphEIi+rXNsRmHS4XsbMKAr370VtUUdbEZDWDuS3b563PI00J5GXxRKIeTLTKtuI/QM23z5ZO5G1VFxcwSHZzfHoL05hILHKe/QfFYfHEIh+DR5bPx9NAgF3z3a2vVdbzOa245QRYu+uWWJNxllLAPOkUPwtj46pIJ3DNJZPVH4UUMDrfCHK0YA3d5s4CEVpttdlTq1zKSKspAOzrfInrXly2hyO3xL59uLdNqPY+h8UAmiH1GiVV8VOsE3ZmaTDjS5tau3h20fSMhM0HeFTvB5MvSTVytLlFGmcYRmCl1NHHRzyIRQbwuT4rqBUKUxXltV2G7ZrVu8mByojeuCR7nEsR5LMuqAi5aiXqKDFVq57okGjRAqWy2ellKtqIfoUL0zOkbfO28Pa52g+qhtThAJ65mra9x9ExrhbcbAXORuVxeP36bE424g0Ai+MJYYbbLMiIxCgSOk63Q1xrAzAyphPbvuutoIxf4CauHtdlBDJKzHIDiX+RvR9jaiTCie33NhzF7fOQx6ei2oBF+/ivUvkCetq6ESQv/oaTY3O6wgE9ZjJ8iz7g/HqL0pErDN26hCJ2zPQazwn8yJqGM33gbVC8nnBg+ogjgf6BKxoxA6wfvulEaBUFj79eVxa96DkHQtEyiF7Scy7W5WHB4NZDxsIRPLmlhnVKUboV4VGC8iYbU1QSqEbhbqNWlfDUphP9vqTc7LqME2fC9q7Vtp2okAoRByixg/1G7AO2qhjeD42+pmZVs6lELIPVJa074EAkphP7siGnzZxgShsB+XRr0RhqgcNkL5qUnZaVHdqB02tk/WMAuw/fQZz+nLSDFNqFg97YwKYDMkxrCq5vWAoR1ugFn5rrS77Z13nulxC2TW8tYHPTIh4iycfbeu88oB5W9PK2KfUVZr+ppQtCUmK+me0RM3wAoauAY1lM6ab8/leu0AqI41Q1tkWiJviCDKY830GG1QIktmc9SxmumxvDQEhC/B7V8YjTs0KKgZNUPeDvsmJ6MuKOwUYMVOTotlRfElB4tO1lsUOKP6Urgav426P3YxxszbZWghXVZiOaPA0vRFlrhKkGesRzsSwcGWj4LkdP32kQjT99FQgGAyRy9qGU3fSIOpqFY5Bg280SPoOUG7FTtCeKaHrVJmtyTzjIpDDrZtC01Y7MGnhxXChgC6aQ++YGt9iEEyDo66QTO/fKxbYdKM6j4zP+KjoH2IDByo0TOzj5TlGoEX2PDicfPbcbro4QqG7WkwgcZl1X6+edhCbcsd1SMQZnGnAfN4UODCfnt42KrP55v3gF65M/h/qmwz2Z7sDJt3czCEv9g5iGa5MxQgGgzJloUARWqmd6HQvrjMlIYiNbM8YrONuyuh1MwsL4Ne6iKTUWomXsz+NCbW0C13+ipErFZQbkA1ysXM4KIY1pxSr1zHAzNrwY4gNMsNKKZChxNVE6livDyvwCGSb5QUSsZM791g3HG9JxiqvgSY6v+ml2eUfYlXD5lF7bcbhuyZZXBeSCmi8EuA1bLrEm+Ubokwu732u200DNqON1/NutihubqHrR/YGVObKEcTzPo4AvFXM6Ohc+70aUuikWi/YLffSJmLTDBbIdOMCi0zOAeyyqTbJzuaIMK8OVK79eZHFcx/nAd/29KRBeFyRdYgcE5f5eiC+Y99H3VP7PLu4WEWxHpjHdBHd4bcIVyOviRCMXBv6s+lwCiZMus/cRbffOk7XqwOf8auUbxk1mey5XXIliQwSpQEXFVmyrV0oZjIrA+JbTvZg4/qUY1avYZLtNINKI22KOioMTmyYHorfLIigsXggYYz8YMhIsjea3q08N5rmZ8JRUGmb/FrEXV36zi6YAYbOna026gto7TH9CWQqKXmt9ceXTDbazLlPm94iZfrHNhWqjKjFsdsbipZn8/x4c3jVuC0ZpUwzqh5EeBkbMpW+Bzx7orAWJcAo7LFDJlH1AXoYGy/vjxu/iJUlbaXw9A9kgrNu2TyRXPdGZo3qOT4NtqysodFxzqK6+rZVomwAtDqjctFLYoZegZP2zntcgycz3sqqpRnI7N6hFlXAJxIc/kog9kfk/B5bTv8jzCIKGsWrEtbji6YwcRPA91NTELth+mLRNGxibI8+ukjDAIsOoZYJv34UQaz+xlF+X7eTDZ+FGJwuCxFSE63CQtpEBKf5CJIl4lCG3S/OSGqBg11tIyhDbyRX+bD/d19xKtV+zLfUYc28D0mCKdvukEb/Fn5JXpK+sg/tIFvEMzuhMXSPdBsd4b0o6aqr01oflA4hbq5e1EnYAYHgbX6lAUK/XbnW1IKvMDOWVQKmCF1iYXjrukPpQKmN9HT/bCXeSdQDGCG8k+0W/SbUoBqAAHnYbbzdawi4z9eTzd/3bbzIqt/jjcIbGQ77JC2P31iFLunI2RYQwN1MDyLVpxnskWO9PsZrPjdwh2n4OphTfYC8aH9Dfn585/mEbCrJMH9f8D5Wl3QhncOT9y4w5QbwYAM/vmmJ/VqLeAysvADrJzz8+PDLt/P5cXC6zWw0Ajj3aFQYFqSENnu0ycY8eBBg3CDS7yc7fq+FEQku8/p3ekMUbCjGt14p7eky6Lz5VMgFX4GSzpjQ248NVLd4+WUN4hRsNvPeLlqZ9cb1Ih09Tm9G5Ixkbe2X0ZX3hlaMwy1KbIVAZ0Qij1llT+XUEc++px+H8hmV9XDQyh4YzapxJd8iZTweDXjtPqdcZAK8+HrOd88YCRtT2+NZt3gddOLkJTtYLN1Zet0k5GVPUNhJh33N1AdqdPT27I5YZEvu+3Xt8cVAHf+YGICudPT26tvMxyFeyI5eq78wvWGhKNJ71z/yLPW7nyHXgi42q1oI4BaCG0epqoQyAiILr0BVrDQDVRFAvP0nRoU6Z7usEIt/MFZQsYKCWb06Z3r8TPWcc0+yF/+B4agtS8KrRBgBmRXY9RIX56hclVWsoekArKXpzdnqw5eu18EUmE9/Awh2bZ7QimEVg9Z9g/l6qJX7/QVqGRbMYmEBOTpE2wYJWE1lzMShAPKZK52Pwd0gjdnq010u/MQOiFkx7Bswx0S6ARvKmdTnr99DzIh3JvVwuv9llAJoXAWQ733PYkhE0I3B9Vfn/e4glBYz0k90PBdAw6hsJ/wjNqvSxp9e2dIQ2EC3U3cRrbp9HkkajWNtn4aF2iF/QSdlfR9EWiF/RohrnMUyZzTd09WPYrvtIFUeNsr5C9vAO1759vooP8NOoRCqDjFYhjqKoT8oJ8ZqkqRLN+6xhkZjXM/3xvWhbufQyi8VakgRY2MIy3Q4WJm85a0zujiO/cTZFnmdxhBJ/h2CrQkXNMoEvdWSESh5/SzISJ1b73NliciqLS8z6azQvOCog6QMkkheW695mg4HzUZz8Jfwdys/JxuZBrpcSs9JivE9ttCOesvwjTPIP5e43JWyXprPaH2it18/azkBpVCYJTvybeHjZ2sdeGNYXtCyAvOCgXUIFcr4iyAf1PSkYy10mP8ybNYY7WMbKv1j1E51evpR7qVw2/50PwRu93j9SpfOctlGGcuL981QJbhdne3M9lW9h4rBn/km/2HzKYV0iaY+HDrzqC773oLQ5V7SiMxaYW8BzY6ucwLqUcBto7EV/4hO2jlx0GKqJhll5+R86ZjscZm0x3pPeutO7XmlW/IwFmh0v6yOPAiGMPm54yFhzb77RlhRcijsYw9+nour6qWqFQWpLmskLVg3Ys1bDlFFL+N6AyZzJEDs/41iZ89SC5OpLEsb/LmcWZ90fBpPSof4+3ympFGEq4Vnb1lCJBFssozmcqCu0zDcgZ0BYO5CizcEitI9FjBJE5HQ78BZMjFWOVxkcxyjf1ItlhvaSv8unZH5EOsYFEfSoQVF0fKwvKWbcKH6Q+DS4SzlZbSkx2VsHzzZQ1qvSF9SDkIVxd1FBsfjpHzcp/VIay8cEZcf4C5FOqXtonA+xUSC6qCHbPdHeP2ODnrF+CO0PhVnlAleIalcRAav8q7BZ3Paq4nxL6vt7g9qoBr80Vo+gqdkBG6f15Nv31UQryYp8rVGAj+jhczL+DW3M8I71719XIu6y6fEaK96nOYl/EZr9ACeHkzLusnWyutjAjugDLQcu47G49IWN5MyzpIN9kVcdIOzSLLt6V2Rqjz8t2F1XLvRtMglnnVh/qVcr0ZCGVevrQU49qQDqEHb83DVm8Vxko9eOsetiZgqd3v2YaHZbmCuVAcBhHBqz5WmNb2nYptRZhpJId93d/eSLN0T17VvUHnCSKCV6iir4Ketm0ejbB8M+CrXmxTPhph+dJSzBb4gnkQr7u8AZrFEdv1ciLidoUQcFa2uzv6kQirPX5K1E2QPEE/4ABzx+43hAExs+HejKS+Db0zWgKvNwScdasM3g/M6k3bDOsIel3eOqzTYt4lMnK82iLi7vIcGDSvw5NOMptKA4P2BFi2Myw2jUfzsBx+Z31eByoCP5ePERexS9ZjOyOyc/kOAlxiME3rm4z5wEVx9wqhQvDmas/OBHtgErqfi7GtjZtIj/jJ9dqWUQTwngdHJwS8sGR4NWaEAMjl+xdYeNYNf0cMo8Nv5cqjd6fhZ+RCfLsowo1qQZvg1V9zJNq821l5pELEC12S667iIxUcXr4Kldluv/69vOYbV4tAv+U7K3NPR5crfRdohRDgzhZH6b47pIK3jTP7cGSjGFAKIbydFUpuJSQE1K3+8DbU4jLGi6C3FYzXSsdqd8+HVvA1w2gaqr/24MOD5hNI1n43I/Js+fbKHPTDy7Y9GgbtLVdxdmVDMWY7rsOOICnNJwiFNzh+olutHhs6Idi+uYP0e5xAJ/SHte1xs+/QOHj58HSSl8MYq8FnzLztWSpi3yGHSPDGZYalYpnZow0PXw2B/q929zNq/xqPyy1uh/iqNd6zjoU19VGgEoIB14wFenUEWK0Qpp0VzKz5gBbCazynGQtnVsFn4HwPYWt8alsIQqQcrJMU8SVbaPOo+qLBpF/s4h7vzRpvsDJOwQNt0P/uzZoy5YZgIZJohW4HtCw32zrRR3iFulVVvEkmSkQaLV9YqlrzY+59CCRabwR36eMeCggVCrgI5bopvojnWcGwTGctMof0apAJIci7qDGUNjdE9PwDw8JglkSE9ITbM30O1Re6YAycP03ZG2bfCkhoKbxCCwOraqGvApUQSk8xHLj37+rtcetaMz5fMoJywvXsW3jLDKCr8PIR3qoEsK3cdUbczZqPPfBs+7cUG3oLr9ADIdvI2+XNwxZgjiIpBmPgHlcIWk83ezgM3FN5HAWjzCyHGJY1H2sDmP4yeHlY5imYeMRiEGYSYUY1lFsJEnEky1vN1cWo3MuhEzwMLrCsWRu6Tf8s33OZGqVYX6eMOJAVTO60N2bbmdFieC2ffoN9/Ta1yAjzCDAD3Ha1CQOVsJ6w3d6viQahGMvXpWKt1dHszECX4eWjz2nN35cHINhircdWCTeITlK0GV4+yptlQ+HElh0CwRjLd0emEGjp1ltGp+EVzObsNKwS+CiFiQjgZx22a9pCRMQKrYbZS+IrPYWYheXLM9EJDTus+DhiEtZ6zJUFRZLs9vOBWT/m8LNuz46R88Hc3LnTrTuIwIC1/O7Lc+XmwcH1v9brxFm38h5aDq/QwoEc5Ss3Auf+8hZs5slm65ed0XR4eQv25Zb22+1B9ejd/K3wrq/tP0tj0LH872g7vLyFWu0/rqiF7z3AjKNJ96NALHiUm1+69WHgIF/BQJ1ZUksucrjH1349HWvdfRlawV+crW2bvRW0wn5C8NBSc9vVGDJfL1VO5HuOQysEmBHJtxII/MsOzhaplu+uDKXgYXwPbJv3xTBmjxQodBLra0MqBByn6b4zEVIhhHlbsoSMqPD/BpiRA/V2dc/oRLxTemYi+yPoe5+TdqfXG4KCGvre5yR0sEmFfUsVoR3xTg95QxdzGabgwN3pkbUj3VgPNCQOMGsiI/tfo34Ok+3LJNFK2r8d4Gz3O9QqmtchYfj2+E1jw1mq258te4daSKRANZvlHm7SHRr1sqDQXYOreNRiwtplXwvD9taEQNSAXny1Bzajvygx3IE7GMZZr/2IFKMwa0Rc9Vfa1TjwvDm8mbmg369y9rUdorlZFq+a+IRn7R8YbRzkhEKH4u2t8ooAXNaMIcPztvMTF4ANxBbi2Zl2fowscILec/6ohZ3r81XTdf3BtbZD3121m7teLHjPdvabm2qsXD8T/GMOv50VroUIDqwIY5NBt2G7+/KwhavVbNZvtCre2VtKKzt56d5wYAVUjTZvPjz8V9uXMspqOmjcDs2KA6zj0rZluK8CSv5yXczwP21fqIh++Zuah17F25dBokSa7ZpZ4J0KV8ta0Oy4gf9pe7u7qiZvoyBwIG1fiUjWpxv8A/9PuDrL4r8ufmbaDmZ1psqbKQDunx2M8ltljfVkZ5ptXwtILaU+MygcODu02bV+Nsl+ukVYyb/XrQ8HjYPrrVlTjR3BQ7PLK2Ow6+t7nhHdbxz8nGZjhZNklxpfrO+7NcHPscsbvAyHgCQQHBEBZ9hRS9ckCE/ELv/sy9PoCTwRuzwGxdVuIww0Lw5wVsNQa3yS4UzY3uHA86zd7EA4A+LlLLJkRZLQvnj7xr2MurzECO2Ld/BFIJ2839hmOBJ2KATU5AGf9ss7wvLRJNsb0MR4B1cE6w/kW78SfYx3eWwBR95/l2PUvqmc/zy9y/DqceXY7JpsPtTmUWuNsi0VFO2Md/WneJINxabqUQm7Pukc6L2l8wDW+u37e1D3nYmumEoY1Hf164AOoK9IEEzmEVcVyRvygL7Gu/4TU7RumC46G/9zf0hihQfCar7raw08ovdujEcobO+GYebhGGpditikn+0D9RkUkW6pR7Q33sELg1Mes82ebcSraUOGV0+v3jByTwMB9CW3J1sezRY2fuujwMC7fYUgflK0U7f51FO8Ocu81kumYYHdPoVALsNLMWAhDXCy3gbZbl49bAXj8VGH4Ri2l043k24wYu76GOZREsKebHjU0q1vTCOskNv7h8TjUcbDrsaoPUoetMwWaceovY1766fM0OrY4ZaqBrO/lBlMjduXCUpM0p8WV4huxzv0Ud7GbvRwRyfEq/lq1lstw9S4ffeRYjLCDumjEyLMsENrLIvUTQ9bXV/0J9DAHZ2wvROIlXzyLQYPQ+IOfZqT4GEvtj1sm3b+ZvLRCeFqmgKOfDISAJngCwHJ1XKlPOxxDm5WAw2WBMHVw5ZO1q4vBPYwBxf9dp+Xz8KitdujCwtyDIr9+og41/Cc4x70EArejcRwTsQk2M8vDyuwsJZ9nx3j9hgSMtLGiEIktCcaYn8/DIkQ8hNgfvmsADC9RBjHUblR1+h+vEORIgaw3GAwmE7i1Txmv75KaIC83zbUsMrfu59B+3PiSJTCZqW3hkQIJYhY0PjSSSiEt8AR8nQ0jSEQfEsWldpKt4A9LBv7nwJFud46GbBsxOsZSdY+8gOJ0B/yg26ectOiF/Lufl+cjLCzR4dACOkF8HybBRO2iXAp9o5hPjlYD/brf2H+vS1PaIPQ8IVldG79DHRDDrDiwMZtwQGRvvsTlgNHhWyM0OjbN3Shh2ZfGY+WyA62PobdGpFmSPRwc6ZrozWJXY0h89YsitVbwwci28EWClU+AydUcricFvV1jwPI4O37dNPdV77YFzRH3r6htjxXZ2ua9vDL47dxb72OXEjZ/XqnClJGbOigEbo3gTDZ/CZnokvyDrWbaIuDQtHjQSb4nt3qDHALH0Bt7uHZDW2otrdADe6QuLEYD63jAnJvDyd2U1OVMi0EKDYHW9eBcgtPQnQFmPSifFHL6Jbs8GGK8ZyU0578jFto302b+LzhgVBOO3je1DSmmusf6ibi7MwyLs+HfAn3ZzXocduHQGDs8XhCZr5l7SABtvfc3QJvNqOhEkLSCHOYbgsj9E3evjKTEifaLcoJmh9wM3vdKQuh4DuMq2zLbQsHIh5hSd5b+Rxkeoe+L9R2iOPVyEIpjMcjum6/LZDZHRqNs1HmqubgAh/d852w5aa9gjIGWF2Q8vfbZ+B805dstctlwgBvCzApSrnhOSBuDlaA8i7fR4NU8FeDZJztw0xq4GU75IxUZfuJi4NYOTjfJEw5S8GMdnDMLQs3tekIneCblhcWOrTUUnCb/TZtuf1WMxoqB5TROdeMAG6y5+NaR301W6bQCL70kfavG64AerDn60JGsol9bqiEkIsybf+x3RUywSejKFXws/bhjN/BMSa7uHVWzjiot+8DDhy5/NsuLx42Y2BKt/AvTtpwOcP7bp1SNFfewf/EnNxskQE4TPd6I0WQaKiPAqEQrlZ6k/VXzTiyts8Iqde7roGHUliPKRH0yW5+xm29gQMorKtHg04IXVd4Ht8gWmzaO2SbsImPBZNiWw0Xqwqi0T5sejs4vrZKZdlxCpEQaiuRFU5LscautkM+iCwctulDIyyv2waJmZg0NqUdnGZT8bV2LcbraQpXv0IC2HO2d5mJEW7T4dhTAkydjS40ujkUQkjpyDSH234LgbAeB2pBYUg7K6AQAs6YwlrvGQ6JEDxicj1fGwIW795PeF0vFuCPxbvf1iD1C5fC6oqwfS/bzaEPAszGQjfVH4vDwVbFYH7bEhTCfkzG6LNk5i7M/+1LBIntznSnGkTCflz6paNXhcYdKiFczxIM+TuFIRO2c/oX1dvr96SETPCOMauZkWS+xWzaPq2DfPnsHjZ00AnbB9HRBzxu9C96L+/QE5ybdr06A9+cXYP//sEa10lv45tHnCG4d/c5SuFB1TxO0g0Tgj2Fv0+jhp3zDu35ah7Xl8WudLfm8938PyjZh2XN7Tg8A8+2xH9LnZbUm/SCgfW4Jd/DFyvjFYaWjYujLEj7293P4P2PfyjnC8hKhI7M/h+MYi4rmFgwPB63yiW22xS0ZGZn5DA/0Z6vGc4xfFvIpLPZ3RvU8A9GR9K0QSz47XiHwhDRLDJV8OPsrRwObpbpth8YAbdAzZatDkgBxvbKf1+pW+mWLhxDmB+TD/4iQYnv+cMGy98vqFODdZAvuJYtluMaRiuGohvkHP7hNtK5NVQLMDZhjmIdNgbDa8DF+RDcZ6+Q23s9bbDJTCgFLZrZp/nvvGJG3TK5X9Ck2f+DpgGCuu075/ncQM7WJKlS0KWZnZ7jPoEOSVufMe/nH7KV52AoSkGjZo+LsW+LSijo1BxhzjNUgtc3KBzBJ1auLln9Cho1e7hY3JVVOyvo1OxxadRt5VgKWjWz0/Tf27FsqPZw/C3A3UpBZCmtglbN7DX9N0UzPWhLX68sth37Z4+2nJqCXs3xH7gLFlQ+1z/U9L/+gTW09AI1h3+4xqJilXQLejazX3U8QVGoV69Ya8CND40b41DQtjn+A6tlrHH3mdoDbgXIqqWJFDRuZs/rIEcL7Pw2iHU+/6AaCPCeaoZVDqOP+ck0tnUbo/3A8jxPiyAraN/MttlhCiHg7+5ELYd/0F5XpzmAClo4PzeoFiBne2Grzz/IL2eVuwu6OLMxdxgjuBO2hqD1gFvuBOKC7A3Gcz1X+ah3ojUMYejkXq1fg32Etp5/4F66cQdNk4ZB9M6YW/DJlmHHGNb3RMzjrvKOIQwtGTALcv6uL0wnd7OA0niUO416Df9gXrZ0G2IUdHRmk/Ag7cFnpsag94BbBCYSigwfAb9NI8wrU9DW2eM2y1oRuS/o68wu5GEEkNV/t6K+wz+4hKmiWTI4hit+5V7S3UkHx/D5yrPfIR4lwGbXQYklPeCoAbc0+6aKOwXNnT2sAA2ko99fx/gFDwiTjJdlpBZ0ePb/8EUNWoBIQZPneAcednvvu9IHhrC9wo2VjoXvgIs17jHvaThTwK34PxIMbAgmRtA7O5RhUNUYt6DTc8Qpatdd57MG2GKnEUyqF5wYwr+cGCVQ7G476ewBrdbJ+Yrigk7P8R9uZ7upLzDnc3tZI5qVJS9o9sye7mGz5zZkr7cDbmXyupXZL+j2/FzPWNtuaqug4TO7wgc5NZvVoy/o+Bxxq0+27yuu+vwDPT593Y1stfcHcGCOekd4cQx9IldRFv3WB14j4Aprg8NbA7BmgIsGIJk/vKDrM/vW/60w7AHgIvZ+O+ASXXDcCKYoCQkyrIKWLIipJOoS73tJanq/73FNZeJLNHF8pjWMLInKpD+msDbmZXMUJt0H9k6VnDBCSl3ifSiqd5HvLktdEkpAcRNLli1bEnVJf5zT2CWS4PXAzFdDUZ77APv5AYZaVEsZKZmqpD/+Z7aZqMJzwJU5AaOWCFGmLOk9fuHMYudb/8ARfPhqbRYdWDJViXfnkK6CLNgDcgSfsCcU/tVJmqlKPM78LstFRuPAAA/1OoUBqQvnAL6tw3ezTT5TknQ/wZVKtG0FZGqS/hDe0qygXcmUJP4G9IoMK+RXMhVJSPlh9n23YzBTkQSvCmdIkSu7ZCqS4LVhCrv2wEw50h+jIzpuMVi3ZKqR4HSh7LfenyVTjbwdM8ZSx8OSKUaGP6No1LBInJKpRcbDg25L+ZIpRYb3bmJuWGh5yZQivhwWUx6T+U1KphTxjg/WfJ/LTtBMLTKe4wHmJi3uTC3ifRdqeY/6QvYP/f2HaRlu9gMj4EPbC1zWyf5hhn/Q6kPHaZvcFCShcQWD05K1DCmZgiSUxaIPFw4SfUAKkvGyIAYta/5QkHgfiUyk/c5f6pHhHZpMIeoWNVQyBcl4TEfVioaVTDkSYAZVG4/NVCNvZa16jSKZYiS0uGAQPOoc2fUz/EO9IzQV3lcyxch4qTiK2Bf7BwxhqL5F4zYMJ/oJypGQJdVkmNH1FCO+VUVi2BT8BvoEVCPemyI/ULIsgpKpRuYbQ5jvNKUY8Q6VrLaiMuiWTDES8Gp1cjRLKUZ8shEfsFuRYESAUn09hyBSgzUJqUWm94jToX7W0bAX3M8NmM2UVM63ZEqRcH9FWDaRgEwpMh8nXkH7bwnGTC0S/qHLYiGalClFgmemGkuw6zmA3m3OLN1uZ2CmEpnPDC7njLQtmkpkPo7xcbsolEwl4kt9VZnU7QSiEPGeGQoVxEHY7XfAFc6Ijte2AilDgucHm+Qssl3CiHvwleIaAYezTZY6JPS2wBF3OIqkXqYOCY0z6N22LsglU4gsbzRhGHr59hgqkfAPsumM7x8wgL7aGOUyWjppBChEgoOoMR3O5hdlSGigwbTWe4RThQRYXSlNJWSqEO/HIQdNVlSxZIoQ7wbiCX39eiVThLxVxVDawk5YqpCQftUVlSEhmqlC1hOt0qc5oUumDgmVw+jKbfJqlkwZ4q+nSewbfaqQ0IWD7iCrVl8yRUhotNFVvfniO+DFeiIjrEPvTxXiPUbioGcD0f5EERIqjDF88lA4OyGoQsI/YANZ2WL5kLH+/gMPcmueWTJViM/iUqPuoajakqlCfEsO7bD52+IoQ0IlMoYR9O8QoBD55w5tfacclYhPFFN3inI3YSqRPzzbHtHvIFKKeMcZo7xuiFnJVCLLLXJ+pWTlLUumENlPQCNzQex6DOF+o9wtPLZk6pD9OHiZPm14f3A1emiXJVCH7Cd2GCk+EmKZMmQ/K/iccWbWzdQh2yn1pFIDZjLMlCHed6cuWt0Mr4UyxONiwZeGF8qQ4NxLaoUlo2ihDPHJctwDb/ufUqhCtgsBZlDCp8QLVUhoTqJAk/7doId/uGXprZxjKZQh+1nESAAwllEoREJSHdvPWkh8KRQib94cWhx+/7DDP+gTIVxfi6hQiLweQjSjsnOgUIn40m4U05+DqlCJ7B2foFhRXljJaeh2QkxhTtbEu6DbdM6+ulu+XZXtBh34Ww4ZWjsLHwG3CM+Vv+ebAbfM5GkRMwUdpyOuDnh2TKLjdM6hfByrL9kpi47TOQf/3lajFW3DaDntccXtbis9XtBxOufgvmPFwGobEDpOR1y5XtYGCkF8wP+Rwd08H+g5nXNwzlHHW1mJgp7TOScnQ1U20EoDFzSd9rhVQDjX3+dbAVdWBKpx2OvtB853e9LjV47eGyuFghy6PVRI9slqCgZN3/SHDMneN2jG2nRXKGRI/Ich56J9feiQ7F1/ykLMxrLQe9rjpnOQQWDXD0YDuA8wxDJsgCBEcvZiku069zX3ov20/wfzgcNea58YQiTeQSXYdcih/3TO+bGng8bY/G054CpqAlsYoy8LOlB73Ky9y9rKFbSgRhp/XD5lNasmU9CD2v+DBTChXHmyX+jvHVibLVtvqoIu1DlnF4Gl9jVj3FnaZvgHs2kXhGlqGrQV/kHWEEgJnVPoQ51zqEynkjVmzkEjao9b8SdUS7YbdI7ijqMEDm42CTSj9v9gRgEEWskihnbU/h8UJb/3pevoRx1xHLVD/bcKulHn/KbC5XwHCFIkwCoK2O86hBTJPlfOyNw9pqBFcnniAle7kxhSJL8dYQbUtm4PKZJ9Mhy/8HWboSU1qgDGGbJXMVsVelJHXH084fLQ4EKKuH8QF0U5NHFVtKXO2fs2aS0oV0qhL7XHdQaye5I9wPgf158/mz0dralzDnlpFotmm8Dg8PnYKrp3zR6E5tQetj2CbYw0NybH71GS6Hsvnw8aVOdcHv/1QEc9DfAsAZc5vU5LzC9oUe1xC9FmqU97gBb+IVso3lASRUGP6pxDL5fEcLpqvz8emFXExt2DIUWy73KvUnnf1SvAZi77fhqDF9rAVMuW1reBDMk+Pc1qALY7+tAh4R94BsEdZGcIdEiu3s5CS8+d3FAh+Z9WMk3R7wWdqj18myldGYlW1R5vluA/fw3m0PnwHu6eKPKswVscvB4HD4bqYjhHz5lh6A9E8L+Nz/4fuKNfOwX8ylTrFVnQrRpB53HtnwPj/v7m6D017tu0LN2CdtURT+pbehnwbgFXuglFnAZo94AP89feUtUFLatzfh2iqHVkZ8OeAVfxh9GvnQNNq5Ht+PcDvH6aMxNdq3MOlf/Ya3za1omu1R6/aaXJOqwUNK6ON+AX3ukqdbSuztl7M/kF4fRfwmvAi86eMo0Ao3l1zu0JMUTqiV3eAyxjMcpKy4yG5tXxcpxcSJAYdvv54iq0ZxwN3atzDo3g+YGWda4s6F/9/ANz22+Tt4IG1v4fLAoP7SXtJzKHcMURQJEM+QPRwzrn0JGdNyg3vKpShPiac9KZ5R5BlSIk9FxheSKrdVwqRYjHQTAQEyBjbKUI6Y9LfO16x4AixDdd4S411jClXKlCfGN2RVrOa6uo1CHdCwm94zVFVCqRkDiVxETtBlQi/xSgy1Z7qlRKkVCBDl77fQ+ZSinSH3PqOjpL9q5KKeJdYqys1a9HoVKKBKcOpYbtk5VKJMCkKP17PYygd/qk28E02fthBN9O5hvNAAXvF2a6S7Ys6lKpRcazUSL5Uzy8UosMd8irE0n7pjG1yHA0VjcY1neiVGoRfwc9AlI/NMQUI69TBBV8jURWqpFQcU6dYiwKrFKNeL8II9Vgk9Q3oBoJbhHLhrStiGLEZ7bQZDusuDRayoC3eMfdjaXWEFCMhMJy07YifSOKEV86jknyo5g9qlKMTG8LAAkedyekFnkrz4Gl29UYvvlouXZzokulEPG13yiGb5RgpQyZ3tjT/vPXDa9UqpD5SH02jNTHoQiZz0a5ry2xUoPMN66or2srqhQhoQDbltM/Cc4BlpKsf5sgFYj3p9DU2K4SrRQgoUJbk0d96fUoQII7hA3tz9ySLbNSg4QibBSi/UYCV6qQ6SUMM8bWfYEZYItk3tciXSlCpiehCONtRoQqRUjojIK5hZgU/TpFSCjENhQBa5+XKsT3RiHNnP1OLqoQX02NxftaGff5qEJCNTZGlZRf+/32XM9YemyA9vs94Ebkbmv7UilCXn8AQvX1ealBvDuALAA0wfYnipDgD4CtFrNf40cVsrzQx/TM3+elCPEOAdb5rN/apwgJJds4P6rJ/EoRsjxRYwo62p3bD3D8Hp8sbKX3ATCAf7bsamYAy58vlSJkP1EB6B1mmyNVyE5x+mVrXVgqVcj2qXE4n6alsZZKGRJs2UyQ+bWb7wfl6kvf6UgZEhpwY+eFs1GjTxWyHwaCQjg2+yhCfAttdWacN2SoUoaEG4iH57t3U4iELtsIch7b5g91iG98kplHtu72QSGyH4aCop/GkKhDfCIMDRz1b/VTiHhTNoXaTfMtlUIkZMKYnVi/Tx0SEllwtMDbJzgHuFhfePXyLZUq5DWT9z5t7VGEbLe1Moe4tzv1KEJ8dxNKwKOrLV6pUoWEEnEW0GUvTxGy38lf0k1iQE/sXNIzedtt4VbQFNvjMjMPq99Q0BT7gbG5J6v5haqM7+2Rft6sDWRBX+xckg+ZYVuqZUlSBZ2x/T9I5hxur6+DztgH9qmffL/WLt5eXO1lbkQQmmP7f5AMRB0peZPRHTuX5M9mFa1uZsNBf2xIgof/pnUD3NEh2/+DNSZGxIkN0X5vQBMeygfpBplj+AQkwB2pDQ5dsj2ub7z2jf5Gm+yIM10p37ha9Ml+rucD3EwcdMpGfXK3QjmG+4Yuo1e2/4d227JfBoNu2XBvun9QTTuxP3TL9vCNS1rfC6z3ckaUGH1Cv+x4OQ/IrvoKBf2yc/F9wJkXebcntMv2sDIf87XTo1u2h1V9Fr5ejR3ER/E9yNUowoynaJadS8i/gQFsW9ZlQbvsXN6eKtUKR+GMB+yDmeiqNmKGdtkwNrtxa6qoZx8OyqOUR7qMfcNR0TE74iqJbLVvC3pme1wCvt966wVds5/rqwqg6GRG22yI3ajs0EnODh90zo7/kOzos5kP3RFw1UGyfl4FzbM9fouTp2vEQftsVC6Ie3tGhQqJK3TQfv6BEcfYX+wn1vsP1apha4wrx9DLN3yDfaNR0EXb42YGXNZipaCNtsflqBrJ2oIV9NFG16fIfgoKFG+7QX3+IatdUtcBhVbaHrcdFvE0OkLQTNv/gyWalqtf0U07l9CDHPQ/3zMK7bQ9btrqLD8NYOMA+t2DuSl3+2z7gZUbY+IA3bQ9PKzrxx29np+rebzczB40084l2KerwghsgvcacDNy1nlfvbfnejU9NB8cumn/C4+uJloFzbRz8eZlOn9AfDUy0B2lPssHm4MC4dBQO5f6GofGEV73H3b4hyET5rrdKgu6asc7KNzyNk8raKudizcCc+tPMN5oBUJ8uH+wgsNgV8nuUNlp4OGP6LuiZ4T6CLja1dS/f+jvP9AOO6zlTEGD7VzezuGoy9MM5zA+EdMoo3qX4OA4+ilWLBTBPsTY4R+siQrCOWwjnen5B0sivElq6LWdi7f1Kpt62SkxS4CVuT+/IZj1hYtqqukAg/4o7fU0JNS50vNDgPzzDwjGaXb/EfBqLUXKZShQIOWfJjLorm44BrC90TAwdS97gE3O5Sh+U+KKYGiQEvrIbLoQbZOGBCm+zzkP6OsGQbftB6aJMl0KCQFSQiNyXL6u7QjttiOO0UUnKDkK0G/7wcnwkGGoXWRx+B5+hCIAQmdAqzHM9S2htcI/9D8Kalv82uEfbu1ZJDVogDbHb8Zl3G9r1oK+2xFnOYxrQEHb7VyajwVTUoa1xi5ovB3/gcfsHwffLeCyMDZEBNr1GMHuBLISi+rfD4zwD0MNSM78sQVAEeJvoHAstBqyf1g06LhvrIYXN5G5UYf4f1DG/u0OXjqFSDCkaxOoaqtVOpXIW/4LBa234eXFoVOLqchOIRLaw1AGoxjm0D9gEH1qi3wBiAhZ+of+/AOpCBweTfgIuLGxswdN+wEO4lMjHfXXs91/BVzrqKFukt1/B9zSA9vV0Z0ypD9Eop7DVuu0U4aEzBfEfaIBhn6fMqQ/MgZpp7aQO3VIyG2BIarcbapTh3hDvwwhN7C1U4aE1BkyeatlVjpViE8todA/Oqfb9TPg1t/V2kaWThXSH2d3b1Z0vHTKEO8oYGZP+pZJpxDxzdhZgWVZ85PSqUT+8TQcMqpzoFOK+Ouzsr/aHUCKEV8VjAv9CFAjq51yJFT+YoboHWCqEV83TJHt+bscAxgqcyn355ryOgVJyGAZKsSkrbhTkITSXUUjkG0E9v/6gXqLlpRORfLW14I5RFKwU5GMx9ySrch36RQkY8QBOmTa/BydeiQklzChfly50ClIxjMFqzWbLZ16xF/PbWrdoK5OOeL79qTbfMKu5/jtOEMYUqXxoxiZzz6KBlpymXaKkVDCi6kP6Kmo56camY81J5fPEdIpR0J7ddXlT2Yv6dQjb/JHhTdLj0A54stlsebF4YP3+hZwy1BMN826U41MH5bQlB1iQ0A14hvdKL8n5+8GM/yDBBkC52wZU4/MZx9mlzH7SFQk89ln4cpS0E2nJPHNcsT1yk3C7BQlvuoXg1Zg8baNirIkNJlnMdh5d2LKkulNjrR3lHKnIXXJfGySCH1VCkGnMAkpMCR0+Vbd6JQmoSUPjarpTmRKk+kMD9myEG2QKU1CJ3vudetORCqT0JRnyGonwtgpTOZj2MDvyzLRqUt8iktmLatujKhTlnifkXyeN7agU5V4l5AsH8lM8p2qZL6Mf8AnohekKgmdeVT34n4iihKf5CJFcGRNtl+Y4R/MdDGt+2npFCXBayRW2+80pCjxaTJc63PfGPNOURLyaDBPV7mEhZrE58lQF6GAtYLQO1VJqKIG23G9xLlTloQWQVNLcRreXnwpFVRvSFWyHrtb/6LvOlXJemwzA/UA7P3mgyuAdN1VRFWynrgCtHm2dUpR4v1KMnxsucU6RUnIQ5nWK1kzgKok1DyzStUGlwfmPpavW6RTlQSvVBbZkO2gU5WsJ2oBTldp0k5VEjoF0aM+vvtz9J7I0HMQLnu7+cB0S6Asj/38enAusGkZKp2SxLe6V9xpvk9HRbIf0waOPotL6ZQkvrCayf67R1KTeK8Rh6/coI1OSbIfwym5sOEt4Pq4CGmwz0NJ4q+/ktpOeiqS0I2I7abzJatUJN5pRNPouj7XTkHivUJqZ53S3SAoSPYbGjy+JLNBQbL9FoWggHVLBw3qEZ++wAybah1Qy6Ae8e17OL13uWc9mn3nGjwnVg20CG6A3zLx6YgysUG0+/b/IDIGQZTsBuO5gRrmocKbPcDEPzyWycLWSkP/sJ5/oIGs34Il6Pmdq29Dr7o41vu6oOs3TLWOr5IwJyPUaPvt8a92oDYYdP1+Lofrp/7axfVFEy37Yppo+51remzvaE8ttYS+3xFna92dvh8fAbcs22sWRtvvXEOCAb9+N7WKtt/IeYvrt3erFYK23w+s6n93ZCFFAs6wsWJ1KAsaf6O/THz6dau5FnT+zvXtU8/OD3o7KJGIF6WP6cNDh1SfW8BwHXRH0NSDEKmhE31RmXChGLrsnKYkF1+CKTp/e9wcbgi6t+tXwK3h8rgBYej9nauP6qc55Sg5U3ro/u3/wdjHhhTW81cO31ueMH1uWTQA9/8gm+Wq1jmnoAV4xFl6vtnRjxbgz/2Huq7a5KocPz+51C3yCgU0Aff/YG4POC1FkNAF3P+DAvcREyPLMvqA5+oD9xVTBilkQ7DDP9yqn7ceE3qBe1xW3byvXxbNwOMPmGPGKoWgG3iuoTAZk6zt/EE3cA9blui6riu0A/e4GDT6r9rlGEDvtclFOczTnn48uHLER/5+f4Z/UJ0NBPVJJqEl+PMD7Am+79bYOHyPRMiw+eoBegq49TaAxU0wR8/nwDJk7MuvQl/w+A/MvjsyTqPba4Bv+ci/JdA5fg8BR+BCtefrAbeqbOnaWtAcPNf6KFmcbvr60B81uEbot0P3Svv99fyDSg2VbwOFAok/QK9Usg8MAVLf5jB73MQcdAj3uPXsgdtOzw8BUqufP/DdXHMkWoTnGqqNwTOESlN6OuiP+hYTQ8Nn6SP0CM81tElpzM5b9vQjwFYBIH2ze8yA6+nb9TqjR/hzuep83MU/OHbvuZvnTV1En3D/D7K2tpYv9ZgcPf/1aYa5BfHQKNzjZkZZ05xKaBSOqk9xdrCCg+HtwfkC+8b2o1G4x61BVynf/ceLVxXks+GH9Ki+HYtqX5vfDY3CPdysZ+xlZhAe8Wp6te/Hg/BwsJJi+h+cmeXqvp1Cab+zFcqj+nYujIdG82e9PJRHDXH93Po+WgblUUNLFvZ2Xfdsh/KoPi4/2dmklQHhUYO7JauGl32bxbF78z7g0zecg/e0NkG0qvHetQNerNWedQco6Bnu8a9J/f32m+PneBtO73GDOdE03MNWY6vM+/i7Btyq3E05e9A0PN5cnfhuKC66huf6FgBbN5QbXcM9rGef+y7bPZ+rkzrf3mW1V8DNhzHT3bSgOWrPceKhoZxxfrQNf/4BrLJcEz36hucasgXY1/eyAjQOj3jWt6mmSic1R/gHUadhwaCTqsO7SbgykdTShfcX1ysui8eZVB0hH4ExJ3buTmqO/oiW9bnsJyWHd7Kw9skhvtnw/V7fWQLQCgNMSg7vROHiqTcbYlJy+I4ozHhDm+4tvDy4HO7XejmpOsL1CDdaNxJ/UnYEHwhT9tCRxf6BA/hMMUh9446TwiN4GdT3bIhZTCoP72Wg7pyW9jYpPHyJLDnavozUSekRamgNnQ1ijpPSY+Q4x8qCbdD+IT//wIrBqDisH6D2CF6OpYLxWkWT2sOX2aK2QZUuux5DGPqTMGnxWnYmxcd4LNTYX7UKJ+VHcHLAmbluQsik/BiO+rG0OdKO7P04gk9pBZRekJdlUn4MT+2KwoltfKg+huMO9DOdRar6K5Pi418fSK32gak9xmO56u3Gw05qD++kMFW9zTYzqT5CDSwVl7hF6Cblx/QB6XRzpLtLUH3MZ5dA9Q2R30nx8YdbwDQ9ZfaIK/yDNoHylRKdFB/eycDccpi3CVN7zIe8rbOGZDeY1B7TxzuwNc+t7zKpPQIOT+DKRn4nxYf3IJjD3XrJlUn1MZ+ACFTOsajrSf0xH/6YYbzUCFF/BB8FPe7lGkcn9cd8Tundbo2i/9/WtWVLjKOwHc2JHfxgMb3/bUxJQC7Q/Y2TSjmOjXhIh/jjz25ljQOlUf4OCEBOS5X9nCZHqIcAJEf4SaIlJ64nAskkWMbF+sOwywfMMsD1S8aJZUoI0tsqxgkEcIhASoDd6d/NxztEIKXtggn5rzrxEIL08DbI161o4RCDdJGRP6a5QwhS4teIAF2v+TkEIMXMCGWkSA4RSLEjQgsVJXtDRCBdKQTFnW7G9P2xOA3v3R4ewT1EILlrYlqQ4w27FLuHKO6NssBDCFJuwP7ZE9sUMcjtVTFg+LD3SwxSAtjL9Cvc1yAI6SRKQJAW4ToEISUE7USRVnZ4iEEyw9E0+v6YX2KQ3NXxmPqwf4KEILkpw/QpomvxEIL82Ydl+SRil4cQJDeFWHdu1DUeQhBN8Q/rupleWngIQXrXBxhZ/P0SguS+Deobr291EoOUADlhwvUg2CEIyQxG9vlEfPoQhZQAOgMUI/ZwwhBtET4yHPn1nL/sh7EqNFL5hyhEW4gPJFsWPT5EIdocrd/2cdzM6cvFKmwI/N3fXy9hiLaqwElpOnuBxCGZP4gBAGBY/wO32L3wdLra4DzEIdpOueXKlPMQhhQzs8ThJBCF5Og8H++gud/WD3GItvgwK55s/oFDJDdOGIGWBpMkFMmH/IX3Zyhr7tgAgUXSgODWeN7vDrvfgY2x1zMUECXP9ijY2V7fClXyIU87pvfnRwGNyJOLPQjSASR5fwiT5wHmKSKq7+UkkCbPA7zz7bgq0YQ2+ZCn1wI8a3jdJuTJ6wDCkf3zdcUfQcoAb9xcO+LsECmvA0z17HHJtQmV8iElhyFe/jf9J04bYJTMwaQGofJs3z6LLmc3oVRe7cRc4CKyeYZUOShW0w3EuMDMFYBY+ZDcPUE5UGKKYQNmGbBcbAe+gNnfYjfMAof0MbNQAzw9IE8iDdJXKJYPGQ01/oCCIxIoljd7cBr7HzjF7tq5YLpwO2awJBss3rL99trNJJI4sYoASP51ObigDE9AtHxITlZYwAIqHmafxW4fIiitfY3Nt9hdJgbdMXYSQre83YAlMdtzpRAuH5KzIUyT3UD1kC5v9h3llz6AE7jrh7bRwOj/gBOYy5u3+bu+RKc2+3S2LAuGQsA8270FYUUeDgLm1e6Uu/Z+Xs5fJoFhEb6EcgAEzIfMdBRPLyax9wc4kszmCCiKzuz9AY1I7lJhtkb08YgUVMyHlFSDddn47U+xet1n+AkQMc9m8wPQ/Ow/jqmbrZ7qj/IfGubZbqFWVIbbzAKJJLNlQdb3ZQGISE+CzJ+TM9z+FrudYdDgskAwNMzb9ahIBD2T/XdZ/Xr0bYHs3K/nzGUY8hpdvJ2CkDHP9uDYuy4mPqFkXgdYtOJ4bzKkzKud0bo3MsCQMh9SxF8ek7a2QihomTc7r9cIpkLNPA/wOp6NQ9LewHr7ABMSe9xPh6D5kEyixFToR6kPSfMhORNC/qw32t8hat7s1yI+/vGsU+yuZxqVWlA1b2bQAH7qN5A1H9IpmAiDLJgNXfM8YNgSu9OBHnTNs91UI8791hiAiLzpdLDPd0X1OqTN8wDbPcBE6EcskIi8/fOD3qwFPKBungd4uGCZGhuUfoo5Sr93VPJA37xebwrLIUU5oXA+pBAtDSO6sZAWJM6zfTrWjT8AJFLNw0SSX7ePYrcOUXAF+go4nMFcqEQy168DHjLneYA5w29Q8kPmvJqtzmI4koPMebbHCnWgDZXzISUbxIB9dIhD5Tzb7fFWpKqhcp7NTt9wt4ejoHMOYbq2h4zv6e9T7N4bg4JTm507in255MS3h13OXg5XWT4hegcgd47EdN2EEFX3LRhIRHo2B0ym6tdj+kr3DJPt3x4DJCLSkRwCestvgAnsTE3g3vqm4JYBoRkqIbwC5fN6B5KtrqB8hvJ5tbNuGRJV7ggDjojkjV4MrLuLBTQi0sLm8nNx/C8QjUhbohKk9ZdYRNoKo4dnXwChiLRtWt8nPBgikdJDcw1suwtLJFI6cJYHnf16TmArttIIBV0ikZwyYiXh8M9fiUNKUgdQe0S4TwlDpGczZ+TylTAkp20s1PXD+ssHYPZKe4vJ+JkDqQQhKzkw5v/6Bq2EIGvUDwSxwuOPv4t9OdFalGkqAUhJ+pBfKUR3lAAk25mPRFG6mTF5haKKiiHXa3mU8ONfFFbTdUinEn6UvhnWooxQRFHCjzyA+cYd+mtK+JFTQqziQqmTPT/xR+lr4QG0o4tYiT9Wq6XQv+v3f1wPdhjbvpXwo9h5fASMVcKP1SKhIPM2D1GJP1YLhEFF3ROySgBSdO4pUosuZptiIpCVF6AxBUe1pRKCrO5CI+Htz0AMkkmqmDN4XexzKiFIVpu3iL0Ha5QIZPdY5e8Eu27f3f5asbOdcEoAsvMBO40Cwf/fLeZoOgiEpsQfO8frybcfkVgl/tg5VHqsWMliVUr8ka/3WFsoQighSObgMh7Nr6BLCUF2yzqy3Gn6AOkD2Oo+ootViUJyVoUB+S8xqgQhO7lhJHlC24K9IcKQbGc4eMYiJgzZLdo5v84bJQ4p0vHTSiX9KyUOKeruzAfseEUEIll1hAVpU4LJVQlFTs8LbomAlxKL/AeF1vQHkGL2Cfw2MSKRk2JVLuvi0WYlEil9K/x/UfGhRCKFYgvhxrU++y12o8lFrbuvYAKRohI/TfnLPgDikKJpAoiOt+t2Tp/Un7/B8KFEIYXBy+V+7fxXgpDTcNZ0EeyphCA5W8S5fz1Op0Qghf+LpabHOVSUCKQ0tJBsf8TcE4Hk611qesSf59y18ML4yOiVECTbSTA1QnBEiUBKNws8xBlEzkoEUlJRJBGOtjQlAjmtYgR6KOLXv81uNQVB8aIEIKVZ5NgB6LdfxRzedwhSKPHH6ds3BU38908fwFJIQDxbXMQfRTFl2+L1b4P4o2SqcEJKqF4pAUjJVLFYEO6fD8AM5lwTeTYiUqwEIDnVxP7wqEhSwo8iWLIs1RGXY/6utPmHmrXPEAFIVhyxDm6N5U8EUoTtsX6RK3QPixCkUJBdwwCvP8Et9u2yddtBshKDlFYQzyX6AUEM0ns95vjOV2KQLhkCChlbwIQgRcLeGKS+3YMQ5GYMw1acEx36SgySB3D7+nkG7gErQUhp9+AUShSmKFFIGcDeTYkNkiAks6DxF9Bkvn3AbQP4kiT44KmoLlkRhCWNEpUrVFSX2xIaqPuyOAE11aWwpJFIFIVbto0QgxTJELrZGnUHlFWXkhITe8u+yRKFaF7lpMMJLWOKqovmM4BljzfaV6mqLtqz6uPTa6aqupSuEVY9jyjvoaq6aFpoUZruviSRSE5ruXIQYdpLTXUpVGX80F9zBF+KqkvOWVmo+RiOeimqLkUzAzDtdT7vl5rqUiQzSJXqVb0vJdWL/bEG4Meg0ktN9TKAq2x7WfFLTXUpWTEWboIt1f/hQWC4UW5DMPF//oS32QmVoNF6/QZaBtgMso3/0g44Um7wXMvq33/++T8=\", BinaryEncoding.Base64), Compression.Deflate)),",
                " Rows = Table.FromRows(Source, [\"payment_id\", \"account_id\", \"payment_date\", \"amount\"]),",
                " Typed = Table.TransformColumnTypes(Rows, {{\"payment_id\", Int64.Type}, {\"account_id\", Int64.Type}, {\"payment_date\", type date}, {\"amount\", type number}}, \"en-US\")",
                "in Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "Contacts",
        "columns": [
          {
            "name": "contact_id",
            "dataType": "int64",
            "sourceColumn": "contact_id",
            "summarizeBy": "none"
          },
          {
            "name": "account_id",
            "dataType": "int64",
            "sourceColumn": "account_id",
            "summarizeBy": "none"
          },
          {
            "name": "collector_id",
            "dataType": "int64",
            "sourceColumn": "collector_id",
            "summarizeBy": "none"
          },
          {
            "name": "contact_date",
            "dataType": "dateTime",
            "sourceColumn": "contact_date",
            "summarizeBy": "none",
            "formatString": "yyyy-MM-dd"
          },
          {
            "name": "outcome",
            "dataType": "string",
            "sourceColumn": "outcome",
            "summarizeBy": "none"
          },
          {
            "name": "promise_due_date",
            "dataType": "dateTime",
            "sourceColumn": "promise_due_date",
            "summarizeBy": "none",
            "formatString": "yyyy-MM-dd"
          },
          {
            "name": "promise_amount",
            "dataType": "double",
            "sourceColumn": "promise_amount",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Contacts",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                " Source = Json.Document(Binary.Decompress(Binary.FromText(\"lJ1Nq2a5kp3/SlPjU2brWxp7bi7G4EHjgQ3Gk/Zt6Kbx37fWe/JWaoUUS/tAkQWZS3pj61uPQqF//ufwFb7y1x/xifXPp/4Z0h9ff/zXv/3nP77+/h//8i+fP/7H1z9HFj0Q/fd/+9e//59/+vt//N//9b//jdVpVec/Q57q//Kv//Q///7v/89K8yotUlq+YMXvXIMvras0/hmrL22rNE21L+1fabU1PlP6t//2tz+4XMLz/KdnqseqTn+GeCrX8ExNWUpffH8IrH36McfIqphlVYW0ysufKWwfBZv+8VEB4rT8WxH2llVbplxo61f9XQ1FVm5oqzbJ2g3d5Hts3WGsqvhnqMc+8Bx+d1eFVTXLf/jWxcg5fgp/zzF9tbXhx3ZU5VU1f1fUTCwmxyrbSKyrvMg+Ehub8ZyHk25yVMYO1p4LKT1fqMRXDTMF1qbnmGNk1adAxZg3B71nHSNj1/pM+rwPJ7NYlp6Xytfs2nHRd/GFlcTzv3H8xGZlfev9MS42dKMPonGnQeJwmzTyYz4wNDFtBBKXb/H2gTla2bEc8qy79Luu4/dg7f10JnH9FovvKqTPsrHnasRBDG65WbFoErmTOO11naiu87D6JKbmh8Thu7Ns5VxmrWXqI8fRoUQj+ww4ZlKqv00tifTxW79nm0kWZOstxdqgPr+anONxRCmzvsrvyfa7vN08O4nL90TuiQeJqzNH1MfInrMskCzLn67R5KlG3jprqq6NKh4H85pJ9qth77JCsl9fvbaT9llI/KOd1Er64rST2uyvq8/v5ovO01OdFdTWgUgthtqspr7a+Sn/Lc8WSJa/C9PLM5o8HyVOJK7f5e8PcS2bzD8zqpd5MWarbtjqSSwsmXU3aJdwHIhaP8k8GwaJ9fqnPzZnJQ4mZ1UUPf7EjGTMUMNXz0Z8Hr373IDxCuc4evRqZI/oPr3ZPI89vXcjC3tPf5ae3gfpi6zf8djMj91thK+5tl/2M2oBNiKJq+xuI5E4f+9S/EY+stGfd4KjkCzuw2P6/NJfG9ZZcZHKQdncjPhRpdFJXJxeOYY1QDTaabXJNEp1sPaqXeMzqy/RfProXfSTKEG+GJNJXZwWF55idKrJhacao9UoHJ5ZgZnqJFw+sVOC66QQnmESqC1pmJshtkdaH2Z1Eoj4DDJmidgXboFtANEITVqSyV6tgMJc+3HesprmamluqO1Y5qorqcv3Ts5VN1In3QznzMp5n5etYU4Oq+7XDmYt7O95+a/CnsMpJ7jsncMcp8wvKLtnR46NtsJnqjN7Q6RFl6RVs/Wt6svoMyvc5K1qcX6csfjSd6AmY6LMflZkfzsYhzhIXRw4ENJjclVLmZCCVTu5RvvrdnNXaHMXUvrJx6VZi7ykOrfpVEh3Ia+pfqWH+pVUN1J7yCqk/pV2rO7mOoxats/8kDrr4TQHUpfvjaGrjlataiQno06XuTRnWywXhJ3n4Bvvi/6QK+miXgPkZnI9L01DnrWYVop7pschD9LF7zIWn1VmFRKbj3bY/e4Lf/WUMmuR57jjAj2USLoqiVQoyaidcijZ5qpaRSmk9vYcocw6a7RvlbY2o3Z4f+lGJ3tHGaTOl5OMh9S/1o6uOhhLnNKtkXRRl0NNNld1nlJnzXUa3c5nVbWQTgOHUCupix6varPqcy+qs+bGyvrkpFSn9PndhaIe19pj1OE8brdgdaouWiR1dmhOaMnkKueYlq363NJbsTpp61yEBToOPM+erZGuOiQttG50ilCHNmuLjhfieQnRH9IV5yQu9EA6d53YZw3RNku2kp6M+swwQ8+kS9c1Xy82gT0RynTAHHqlBPpIKPRm7JZjXu/2K89zSZ91lunAT/XH8Rh1uGwMRqAERa+DR7RqNVCPZE2/rDNGNtkHVYJjVifD9nO/H9XoHE+B0UiX5MlyGJ3UHnIJY5Auy9kqPo9RP9Zd4Hvx9Y8mGp9Zf5UGYDFlTA2pr9uk+MwqbETONMSIT7YJjgNcfArpvK1xfKrRqSYRn2Z+XW3P49NJfT2Bjs+sy05Gq8LG6XMnY8R8E+F8QupHg/gIP5RO1oueG+GGQqarc8+IwzZWK/+BUIzpQffzGGaljm11ePD0aF84+Fw+8ezsEDrpNOaPYRj1J1ez7F82yDE+1gwxDcQ45+O0eWgYctbW7CMl+IWRRfEBQqZtkHftyaTWICXGYo1RTTzOwSRTh5DOOI3U8XsZzLx83W/F2ClBckBKjMPqxBwZ02PUskDmThlH1bfVZZxbWdZpGxKpNaOM2KWS2hks54Zv1SU9JKRK6ovb0dzuGBtUw5hbjVLvc26cW41VVyShiVho0/R1nnMjlsSsU81yLmFZ7bQyLNdIp9Z3cS5k+MvkVIRJv5N/hz1Kip+Z76+ugWl8rIsVOe/PaW5VF8cvIc5hfNUFZ+kdMXqTb9V56RXnsFn3kz8xtJVACdI3CTBONGs5lGh/4dzQ5qBWCRle1qJxDhEmgfT3K0Z9WXfH2Ta4BJWrSiztq4Z1lSdnb7Qk2hTKhces8Bq2hrqX4DS3RupUtmq+e8RfVTNzXRMEh3rEKTIZn3t1TaTT/CvWTOrkNdE6ay69XmDWWW2ZbD2PxLWRzl251FlV72eNOkhddTNoj81bteAWSF2kV0Fs0eTteLW3WWfkEXQ+iI0tk646ZCi2WVt0bPOc20qrpPNOCGJrJj9dot2q1aDbhrVBtaw+a6vTwuvcW3ogXfXWIz2STntxx57Mrzt9sGejk22qF1Jf5uE+62ysy0O5FuiN1Mnrib2TrkhCFvswNshVznisDaqMRyB1dU4P4ohWp3riSF/ojEuPkBbnr9klXzoYx1FIfWEXo5K6eC14NKNL+z2P1W0mjv7V8ott4BikS7c5Pj3PKWOVIFCC4qw20hOtTvmSP8macXYmf2blld8Fd10cpadQgip7a3qqyf5czOlppNOnFOnp1mjRq9MzSF1uNydSmFXIDhmXWwRhVmGj1b7osylEUrtXGcKswr6dwbq5ZqOWJRgKqT33uRQq6fJ+nPntifBX8wizImn4UuvEFPpXf2gPIW+ADFLrg4kUH6M+7ztSDKTTDvkpRmPxeYpIMVmdahIxGxuiRbTfRfNXMcdyMsPNvn51Os1XG4MUm1WLHX+KndRV7klTnFUYCe6oCk8PqT3n1ZSC0Z3X5SlFqzuuSFJKVnc8300pW/vUt6dZZ4lGLSfXanTnOS+lRjq9zkxp1tN+tuCqh1GfT7hTfk46L9ccSF330aTxaJKjTaAGtZysMdppJeVsExzPJFOeNVffnsynXEld9WyQG6nzzUMz5W6y94we1uhz5ymP0TnrjxLM74adQce23n2blcdHIWoqKInUGimnkq1a1UgpVi0tqcZu2VPKrL/+Fpyn0kkdnT1uKoN0SY/v9TFqOQ7VYCw+e/GkGkl36ds1fcEnf8n1PDHWbHRy1Krla8RtXXjItZJOewOkuYXmXGUPndvNkd4y7TS3WWM/SDHdZB3j2nPK/nDtMxidHITm/m1VZ+nIk+beifOWzW1uLEze55FlrrpZJ1d3c8mNOxIvV3dzBb2qvY1hmqtXzvWxEPx7UvldHcMkkKPWXISt6qDHoblQWtVR8rA0lxaDB9zzFm4uAgbNINribNRqb5/m9Mg2aIurteTcW+fwyjrZOOcgNHiCUo2zD1KnWyyFNEej0WjHch6Sx6w8HujVEDPHl8GDp2r7s5uwWn7ibENGfV6cjVl5fBv+XB2zvHAxx96HdH++sVxfxEswleXqQDdNi23uR6vzFJGwOKv5/ISvz02id404P5HlnhtJfhILo3dR/cks1KfD+SnWXnmf/KmbvepG+dOs1VqO2ovU+47Lzfyg3hIt98Q0mcPDcs2Scwgs13dxc4gsvx4s5ZCsPRevpByyNenMUHIo1pjzgisH1GTeDhTdj0RN8tHNJVhD6DaFQkoZ90vND5wNjw8LNarKMdh8ZWXGuJlxLuiYNqHeAOaIOqRYM+c9eY6ow0aHyJbQJHKiy7HaFOfRN8fGQn1HJMdu5QrPZNyXMXIVySI923dGXYQJldlpE636PW5nrPJ6c2XKnxgtlMIJG/IJzkKWqMPcjNgsnK8umWrlZ2ybEZ8FtygNFVJF2G0KZ8pDdJbAN5RVWSM4Swhvz6EzwrOY3M8FjQAtJqSMaoII1GLkmhxkOOxyCBjZxhGs5RA5x5VXK3d6JkK1GMPPcx/CtJjwMqoLI0oLx+qQDRV+gmHHVK48WLlsJIjbwsY4gzxc+FgoB3kEbjnky1PwuhHOcAUzkU70QU1GCBdTMucVGIK4rBE/gsNdMgK4mGAnsqwHy7WrdEYol0BxsT72msEvLmWCqC6BYc25rSKiCwudSRLRXALvTI4754x4LoFu7ciBHa4b8Vl3+7J5IKwLy88+BxmBXSI74qq+Bd+A+Gxri0O+wwrPJzkZgV1WYfJGZ4R2iWHrIAdhZGHQjQyBXSJf3FHLQhz7shlOp0BMF5OvGmUR1YXlsoIR1MWEY4h/bLB/cYnOiO9iUqhhERFeWC7NR4yXmF+vURHlJdLBv47TFW3uygkiI9LLKr/ETUOsl0gXL53hq5dNeG6CvbLw1+pUjLW9bVmfVwdgxnG/Jep+29jyVUPoeKzhTicbqMC6Hc6JLxyRU7gbOkBNFp6RbR55E5674kC98apYjbUANiy/3LnJYDZx0DbgsjUCtllTFB1fD9gmPbQEEi26AN6w/HKxuoDi/OQHopU7YetAcbCHebefKmA5LD/3sIKN6CoMtyv0BRvRNUXeAyYVCphUwHLWFOl2wacA55jfOE5mBTgnRXLH1k2sgOik+JZeFBAd/gEZWA9EJ6W1AaseUoBzEofyPVc/KE6iCMEKthWwnFUe5WhVQHQOZrjyZj9S596tXK0jCnBOyhso3MsEq51V6I2xBSAn8WGJqhSAnMTH+aqFAOck3kEcZ5yCmTS9vg9ZwHLSHv1QNG2wHE7x3FK0zXZV8YA66bWjQwHUMV+gDzkKuE6qr4sIQ0TiOzTHqbAA53C+aitbwHJS/cHEVQB10ut7NwVQJ+2Xfw6GVxYG3XQBdThfXX6oz0bbSGk16pPvXSo5uM5P5MHKLy4mBYDH/MC5+j8xeEl43m2VT/zd/WbpQVi2HOW31beWogLHOvip5X8B0cnP61UBiE7m3azd2BfyPy6AOpm3tWfDP+F3eZ+qLPmE4X1v+CcKLxt+rsBPHN6wHSa6+RaWa2+F8onFy/Lz1ASQk2nVcAnkXEB0cqYUatIB0VnlnvddAcvhfM9r+wKEk/O29D4I49sckxVeHJQLWA7bIAsBLMf8gI5zXoBzOHSBOtIpgDr5heddAc4xwvO4AZxjIjLYHtgoEEcB18l09iNXI6A7mR4JkMtbMB6WK35QwHjy/gTB/p2gO8ZqsbsuYDw/kddNfu6HoDtGqOobaCe3zV3HlQ+W/1pXigYOurOm8K7uFHCd3O4eZQVEh00+n4YUsBxj7DmOOiiOEaoWBJbDwRguxyYFUMeEb1BtDkRnDZmQ5A6/gOtkcieRSz1wnVUe9cINXKewN8d54QauUziknjIDUIflt7ESdKeQV7c6NStgPCyXPQykp5AHvKKWBaSHc9/OnSudOxeQnjWFjldSgHnYHrlRAeYxhXMcuCsAT6HASKpxVdCdkrYNhyuPNvfzcFlBdzhftXqqoDuFmfKxFVbQHfN5opFUoB1jhmi0FVwHd8XN4tCVd5Yn2QQr0M4qz84Sp4LorELP1byC5XCOCs5UsBzzeVKe7Odt7x1leu+oAuqYMBTOmwmFhXq1XIFzCp0OqotnFTin7I8SHMxABe4uIAfhsELlUlsBcky+ZwMAclZh2b0yCnllVLAcTnEZVytwzppCuwNXQB3+AdnDAHXK7tXuyquVhz0WdezrB7cthXrLDESn9O246VD0g4Xeqr8C4ZgvFBNqBcJhA87LkgqEU2hnrJZyFQinsHuLY2+2QjWzVJCbVa7Pjyv4jbFalkbbjHGs7sfSOAjHVg7q87DJrnyKrIZ0MJvK+/LzCAZUw/nKXgVgs8qDXMRVYJsaqc1Jq4uVO6sDbB3qizi9FdhmFeobohXYZpXfSnls9p5nQtCaymEHz50JtKbyRWZlL2hNLRtpF6MogE0tm/OS+wPZyhVOq5gL2XxZ3MA2tbz106qAN5U3jdKYzvLqzeJgNpWi98qPRPtnubQa/IblciJCe6p7OGNXnqxc7dnq55ElNuYyb33eW2pvt23189wSR24/D5SfB5c4+O+5dj6PLe2x4A/CYXNU1xAq+A3Lz1ytgtzUF1HuK5iNyVGD8gpsY7I+D3jANm2nuAdhYWHWbRnAptHw7zxlBWCzCnUUkgpgw/k6AzRQjclXNXdwGpbLjRBoTQu0VTlXHWhNe+HTWUFrWOgM+aA1jXw6L5eVK4ANpwjap6EC2DR+z8UxprFQk50KVMP5ysoGqkEQpOs+BZBmFZaTh0JaH28DrVlT/OogokwAbDiFXHKA1hjb1eoVtKaxR855pwVO09q2BT8IKwsvWzLgmUYng86IATDTKIC9sycEkmkUZf6cYwOSaRxTVT3iBiTT9oCth3yjzVc+3QwkY8wQbbkBybSfRIJtYDPGcPVsHthMY84q5W372vNDf6AyjXcSjnCwUC9fGqgMy+U7eGAzxgyx2mlgMwerXXnajJFyvDn4bJW5lwnADAvPi4YGJLMKk37GEEimU2RCbW9nuRezowHMGKGqQ4AZNuO8vWsAMz1sQNLNN7Lcu5LYAGM6uSDLTggY09O2DzzkW1h4aT7AMAe56NzAMGyJrEBgmJ7fOtY0wJhOsRg3p+VCTssNVIZTyPYHKtPpfZiz/10DlVmFOpBSA5XhfOVbpWAz5jtVcwWb6furNq4ctVrobd9z6waVWYXX+xANeAZvVS7Fcp7sgGdWYbldjmwgNJ0ugl9uDzZAmr5fHfeKBaiG5Wck2ABpTLyS49TfgGc4VMkWva1S9LYGQtM7HRUcV5wNhKb3bVlzEKIOKQ7weQfSwGZWoSa0DWzmIN/zBZthoRzKQGiMXDV9EJo1XoneNzXgmVXuHaA3gBkTB+XcGIBkBr+speZvIJnB73zpo/MGKsM/IEcaUBnzA+fGCSrDwnh5Bhhghi25vBjbwGZGXEca5VfQwGZG3Lbr3F/Wa+ENeGbsD5buXwsww8IzN2ngMUaoRmrwGJbrl5eb/ULPDFRjenuS1MBmxuv7LQ1b/FX+a5g2z+Ism+cGSGNSqH4GVGPkatoFp1nl+p2mBlrDX/ucxzTQmkG7T7n1Aa0ZZSOP6mXstv3AeRT8PI69Z+1agvqkB02ddv15GpvfMlXt5PM49i4/5Bs3oaqRz9PYu/yQb94+zBEWm+PlyY4GWvOTokDVMdl1irizsLrfNlioj58baA3LZZcCqhntdVsGp8ET0QZJ7VaD0Ay6enQOV9PQ44xQGlBY7u6hQGhY6Ky7wGZMjmolAULDcuVb0sBpTO7H9tDxRvbDcfyPY3hHGJeHXwgQs1/H+9hGflw7d7yL/ewvpx6E+QuPRdlLVq4BheXe4qjjUWzOV802Ha9iP0SJz3C94zVszvc8OnVEY3jivUt2PIDNwovbaccj2CaFaGQd8QceeqlUudZ0vIG9yvXxQccj2CxXfb7jFeyfyCvLPYba8QI2f+TFw6fjFezn9bNuHY9hr3L96l7HU9gPHfeq7XHHQ9gs355HrvQ8csdj2Gy+mko63sQ25kt78tEeV16O8r2a8CD2w6fDMt/Gco0wOt7DNnIxXXU8iP3w2bPe4Hc8jf3UF8MPXsVmoRx+8Dj2wzEjxDzQ8TT2U98eGHTcr3soZoQcL/BENsudkStVFurZtqdm5ZcLuz11TpGd89mOazkPH7uqAskPy72rRD0HKzzD0I73Rp/9JNk1IFm5CvrRMyqQljXqAL7nwnL9+GvPsxoDhy9X1Qj/80Dg+XKTsefOKS5zcR7bD5xXOeWxQuUn0UvYzFCFXuJmxrkblGTzlbVTZmWGuPn3HPItLLxMUKXafBXl6aVtcrt5yeSv2QuqkUn7efCDT1tg51xleH1Yfhnka9jk+jy418gprlCo13RM4ZqUWZ4dWt3h6RT2sHUHYWVh0m0KD/qEFxG9e+1WKGeOOlh+qcn2sDzf3Bd6C9sPnEsODhfhdQD1jpdcQvvBhdXesk1xxtodD4EEfiNWFWGrW77nKaShDjmAx3lcaJ2Fl7kGZ6sHuSiK/nAKfd+x92Dlsk31WZMctklON3ifwMjV5NHzz3IvLPdugXQcBMUlsp1+6673xvJrsMfeu03hLDX6YKHnFNBxNrAKPbfwPoL9aYXAO+KeswFyohnJmuEwA8S1jnFdvV/ihfRROMVlUBh1k6t2PRrLr1dYO2DWGk9Kv0PWx2B5lTvtAagT+cLQcV00AHU43/PB0ADOifvtHNcA1CQFTnqsP9t3q/1HgQzQnVjv7HlgGxb5WsyxkQxwnVg3XmTm8rba0GwKhTwHAE+kS5uKiA1gnki3RpXH6QDsiXx3VJU4SA/L1T5hYD3H8jMnHWA8RniuF9Cd+Do06wDdMUGoRA8boDurPHyvKM37ssvCbADzsD1q7BlgPHGQk4KqezCeyAfGxzXAAN2JdGItqxF0h/O90J2BcYd/QC28BugOy2UbB91he85UbYDrGKH8zlmficK/aqublSukNkB3UtgcL135+JEcaMcYI+WzSlPcGuJehEA7iZ2AVQ8C2jFyJ9/MQu2GNgB1jFz73Q7QHU6hlpkDdMfIz20KUMdYch6kAHUSh5BQgx+gTsrbsZ2/fBigO2mPUbFbArqTOKLHeeYF10mvnawHuM4qjxJgDHCdxKFixfJigOuk1zc9B7hO4mjje7TdZ7kXMsB1+AfOQGCA6BihaqvgOokch+SoA66TXty3GyA6iT1NVe2A66T9fuAh31mN+dnOYw7CwkIdXnyA6KzysNdI5BoB1FlTRD0vgejwD6i91QDXyWFb6+zfCaKTaSWvcPYA0cm00D57NA6AnEwLeLkcAsUxZqgOAIqT9/2HK0dlcug8fbtjAOpkCuUnRwdAncwPD6nRAWgnv4jNNwB1ON9tX9NoXzPAdXKhkUTNYYA6LFegdQDt5HI/hR+AOpzvJR7wANQxhquBB2jnYPjBkrrlK78QNclbEFXxADxGrrolAM8PcgfdYbkcXUF38v4akitHZdLTtJeQMwOAZ03hXRIZQDuctZzPgHZWuX4yZwDwZHqBVw6dADwmUI6Uo0o58o1qMGA8LJdrL5Aell/uAA8gH2OPKksgn/JsF1z2OgLsKYGOGlWhA/kUjiV7M3zWalm8E3XQxQHks8pdrgDYU3YnyYNw1mThN3tU5wTjKfSm0WXrN/8/a3MuKVYcJ8pw6gPro7P+mcq4KUUrnPpk9Wogn/rM+vzn5anzmaRwEu3GMPXVFo7qSFPfWB+cW51TiYqlKOJqkpt61Cy5CapROjxAP6xXLXfqA+vL7gBbaX0xk8TtJ45D6VQmqzyzxKnMW56ays4kZSsZWafAQPyl5xlgKlGb7b7SnsrOylu7Avop5LqoVgrhAQFiS9S0OPXB2qPWolMfWa8vhkw9KpQ9CrQ+W73u2iBBhZ9xl4MSUJDRixls6ttmjzOIAQMVigp3Xi5O5WClvi4SHiCgwtHs5DeCAXH+l7szM0m0xp9vA05l2ox3eihIUCVfS3Wbc+oL6/V9s6mfVVmZ6jndEwyIlbrTAQWZnJ2qxD7c5CybK2AQB33RVYlt7ZtoMlMZbc5evQAGsfK8XZ7KvP26XgbNJKjEtBWd/4HV6nXVgAZVmpd13wELqvw4vFOVgEG1ruvy882I8IADVY6Y7eQJBMRKb14AAzJ5Oo0Z+GdVxst6ABSocjhwOQIDBpn87egRzegBIMTGq4s/U49KJO6mezp4UKX4amptO/Woyk4oV/ZKcKFVHy+NFmCo9m3XpPoFEBGbpJe4YESVbzPKIgUkWvXerfKpLNvHHoH4VKJaCTQ+NiLPd4P+3RLAhjiJXkwCDrWHWs4eXTwm+olhk3jDPvDQqvTOm6cyWKVCFVMft5zlKARCxHpvtQ8yxF93Zv9TWTabZVGDDTW+gng8RJzKZpW67YELtT2Sq68frL9N9CBDqz64kyCgEMraNCc/Z9QjxwuV9Q4m1PK2sjpZklnpj/zgQW13dlCDCZiQMUMO6YBC5if2qxyBehnAUCu0/5VtAGTI6J3vBRRqlU47jkRjKlGbFFVaHdtOfbR6vfcBFGL92aF3KjMr9aHm1Ber91YIAEHGBp1zsznrFg4sZMrQqxfUYN8gs2iHeKOckpTbpc/weZ+bk1wcIAPe6KYk1/eaAt6kNr8ix3M8TW2+/UbD8BqzTXKehvAKc8SlVNP7fGPapvdynpXbeYelBt7PS7ysv9YX6NCaJHjbCryvGzs91i4XUZ/nZ1l/gcMBD9FSEn3yPvXZ/oTsLHhwlfTR8RUIeBn1rbKx8gJM8IAp6avjwBHwgmnscT0ZkNMoXvokfb2UBtAQ5++1Q0AhVjqDP161jP31Q5gBL0la/Xk5hJcTjfLi4x3wfuEpiW9M2/Ta+L4ZL6seXIj1ukLBhfrup3koHBChXt46QAW8Xkd6d/WCR9pMzrpRAQoZ/XkljFfAYmcU7HQEgKD++vZ6wPNVVi+HEeCgTr6UZ/e78HmGaVX6wwJA0KoM+2F3pNu1Aa8IURLvzmnAM0Kx73HoTsrEyij9FgOezjF6uRPHuzWkd7dgeHLF5nw5o/m8OGIy32ftSLM2cFDnm+qy6gGFOt9wk3qgofFsRwa+PrD+sonDAxWk91xSAt5kIKV2Mgl4hsBaohb8eFsgDo5felsuAhOZJE6zBCAafEteNksAovH6jln4RDc3elnsAESDXHC22MSJYhPPJMH+hLdwAhoa5D3kHDEEQCHO09nCI6J3HLu7pv+BqE26KO0NtoBCHJ5GL61BhDjgzMWSvunlVAUcZMLlSHsAhfhLH+tw+k1nflcl6BAn8cZ/cKHBLz7LTgRWMWie1R8LOsR6bwoAHRo0z+pNB3bkq/7XAZChvpGKBTW7H4/6P9FZ/2u3YjpRoZ8YNonDzRAo02YujcES20S8kTUFUjTeHGEjhGMcb6gC4g4apaQKiCcYB22EncPxT3hAo9Q5N9b7K0lwoVWp3a4C4tHFwaeicqQFHRqv39YKCKpGen3JLyCCGOnLfleo0F2hgFhi6aE4rBeTMut/LZ6NgwSNMOh5T3gbsSAgVhPpb4PqbGUmf70YmDVs9c6IN8syPfxqlo7aHxB/h5J4Lk0BAW1M5s5mIULFeUqMhpAspL/MGggiQnp94SkgfIfRSzKDqBnp4Si0566NuBPpydtALdZdiOhASS5LQcRoMD8h+T+CNKSHZqV0WQoiLoFJ4kxkiAVglaqpIxIA6auH6HEz3ihlv8a9d6vX1/UDboanh9/5kCWPC9mr/jJu43oz6dN+Qpf4hC6G8bOfiA/rdXzB8LlSa/KXnxyjLSIJVXCB1HyyrrWIWm6vnW0+F0lZ76yEcXnT5qwWb7jYaHPWJdmP+pMlqFM+794ntbhOajE9nMS7aRk+l88ePok+79pw78woJWXCbSvSV72VwJUko9dVn8pmuTN9pGoL8BxTJeC6UArPxvROys5KHXIv4EqPyVl3hPxsekUXcUPGWu7UY46b5c435mTzlKtoXO9Ige7cS8KJuwxGr2s8V9ZfyB4c60l/4Qwfz/rAL5B6ZThY6Z6HfvzXWal7TUE95pUxqovgAd7jRu/sXD7+4IFv6lgmWZlJflyYA98F8jIvVumQfLjcGoP1sFBQia8f6A5w5zT6y/uOAQ6PNsl5PQwHRqN0nOs+boOs1PVYI+svPicfrzqjl8UIrzpjj84fFUrvzbhlUlmZ3WV8bTbPc7y+AA8mUnpBJwLckYxSL2DaY/VeDTbUYH8/msGHJbx4dibAh8Xk7BwCwq2DlPXSiuCjwTl7cyLeEuKcvYV0azZP97u6LQFv/GyoteWGv/fqecDpNCn9dtgDK/3BqkdW6qe/Ak7hjA2SJ8c+ay1SiHw9ZOHEjPV66dgr62+LfLy0EJnMy5aMUxfWOwdMODwh5fVuZMAphDVGTsoj2J/wOsuY1Roj7WWsa2uiRzkCIDolcbkfCHGK6f1qFswn7oESTjmjNukiql4FgfZEvo96248D+EQO1C0bMLBP7DT8novlQ8Limy4P4ETKu5/PB7GwGbIfAbGkyC/bqqb1oSCsl3X6wQPpxRsZAVtYUqZbVIiAvSAluRrfrTHOEjQB+Bizz5MCFvs2z/Ng+1lWr8p4bYSfVbAx4zzmJ0CeRPhOznpYTpK+aL6KdVBK7Eeq1kKf9QLrddWA85j8tb6z/uK/gbnI6G/+bJguTBK5TMKIa/XnURfDZ0r59cISgyLp446UIyPlBMjDP+Eag5otxCjsPfBE98BnElQuu1zKxgPOk8hdxBsbMXStyos/G4Yik7NclqAzWf1tkAHtSZ1MsuVTKI5Z+HSsNUnVLkBoNSmNlRBe9NnqHacaVCwpb8M1sM+q9yKpBJSiUW7NpphmA/5jzNbGzMrN7IAh9eA/rNcdFvzH5L9HQAj0CQBBnESeYiTgIKO/uLInECGTRH/1rOLMdxNkFwARyvsTUGb9SYMJoBAncbaWCTiIlXqaABQyxkg90JCxxJmXAYWM0mnJwEHG5tsqC1wo89VCZyEBHGSUTlcFDspvLiEm4KBMK3CHHiSAIFa6dvbjF/kVMY7WunpQIGPz/vofXWtKwEE5EazW70rNJJGTXA4gEogQ6539bwILMjnLsQUsKKftAEI1KkChvD8pfTKmbWbLxR7QUKZoD7qXARAZ/Rl0JKChVXkbogGIjN5pukBDOW8wzc852Zy31tI+a8TfrQWkyHymNh51So9W3O6DJCCjQxL/J1CzlRClVz7dKnWDBD4yemefAnyU+eKtM3ICHxlrZbsCRDI2yNIARDJ6WUGASMae20gOjpTbCkC8BgmCtCrD7sQS+bA7ASKtSVxkl4CPMr2fcX62airHlqdce4Md4TVOwxB8fWC9v0cGOzLKy/2CBHaUx/uNDwhSJua5zRrJzBqASJkCyUo0lICS8v6i6Ol726aUkwsIEuu9LRjY0eEzvZwzCFJ5Xq/qMzgS6yUcyIBIhUKzy7E3AyKZ/M8jRgY+Kgw/1QiQgY/K/oiXr6+s1w+NTP2s05LW1uKMihnsiJXyYDSDIBWOMH7ZaWagpMJhw2XhACiV9GKyyOBIrHSYbQZHWpWX6wAZHKnk900RHKnk184qGRyJ9fJibwZHKvz4p1cmqNCylrb06cogSIVPD3W8vJBBkNYkF8+fDIJk9GpOz+BI/AkXfbL5y3VgBkQq7InkNBtAJFY6oDKDHZk8tc2o0EYM3IK7zOAuAyIVwi+6jQEiFSI8znFJBj4ySqdAQI1YeXmSfCaJm9myQYIasV56eGZQo8LzkexKYEeFj/DsgqewA3wGPiqvn/2e+mb1engHQap86mfduiq7dWVApEoIXW5UMyAS6529TwY+YmNusYAy8BFnrkcz4KP6/oAjYzdj9LI8wY5qWH3XJXXPYEc/0jfWX06BM/AR6+USKwMfmfyd0R7gaFVeznMz8JHRy2YDiFRfv9w+9ahZDiS1OygS3MhASZWWB7fzowymVHl5I2dnkKUf6Rvr/WEffImVzkWtDLJUCw1rt5ETcMkkcYZlMCVWOjfLMlBSreRG4nwaIFJlF509YD/dn8qgSZUdZS8b1QygVDnM4GW3lWFU5UiG561NBlBalZdLrxlAyRhztX/YT76F4MuAS5Uff5R9FnCp7jErfH3c8j+z2Qy4xEq9kANZOlhyyrlsSlnyAEp1fxDT17ctf9mjgZXqHkrf1w/W63dbQgZcquw/IMdVICbOX2+7gJhMhC5ZU0BMP9LPmjWxtmT5gC8Zvf7eyvrbIg2Iyehlmwdoarsns/FopeU0iJP5CVkFIE78E7fLLxnQqYXNT/7QXwCdWth8hHxj0pazs0IAa2pxHQNdZWHlr4nYHEzktQxBmdYkxf/AxsrbUAPK1OhlEt0AwJra7grl6QtY04/0gfWXDlXAmoz+ckJagJvafqFmL8wC3NTeX6UpwE0m5/NOsAA0NTr+du6HFiCmzt1BzWIFoIn1coQsAE2r/rImL6BMnSK5O2vmAr7ESmf9UMCXOgeTl98IytTpGqODuwv40qr06xpkifN0ji0KmFJnXyk1hhQwpc6+Uk6rAFPqdGnR8RAuoEmr8uKDXYCSTM7O1wEircpL5IcCiMQ5yz1jAUTi/J27MAX4iL9Rt3xApM7PFmtLUI9870OXYWP9ZfddwJFWfb4GNS1ASZzE2eYUoKRO7M65YFWAklgZdh/dtK6cC1BSfw8GC1BSpwiEct9XgJJYf3OZKKBJnSLWesMOIFJ//QbV1DfWX5asBRCp0/NZjptxATvinK+fCXx0+EyZBPXL0fxkswdEMnrZjAGROm8ZnDYJfNQ5eqHssMBHrE92IfSNd3+3TBCkH/1Es3ondkQBO+pjJf/OnquAGvWxHVwelKBGq1K/tzv1gfXuXZICXrQqg4cZC0jRWOb3eJlbgYkGrweccgAdGryW9qytrLzHlSpAQ5z5jVcUMCJO4nhAFTCi8f52RgEgGvux4yFnAKLBqwg5ewITDfbzkS0EsGjsHkr+k14zCSp0v4To/0Rh/eUKZwEmGmXtDnqaBixa9ZcdRwEsWvXZXRSBEQ26ya5HcgAi1idbmJmj+BYworHHBzgYAzo0+EhLrsPBiFiv111gRIP2Gt7IBkY0aELUIwAY0di5lq9vVu9A0QI6NHjA15YMq9dlCDo0dhp2sARcaAyaBB2bsXJfle6jSwUsaIw35QAKNMb7cgAFYr23kwL/Md/lKWeLePigSrY3zKJPeD+yIcjfQx6bYb/7HGmkQrS8Q5KD8XMwNkpvQJ6Dsc3T6SZzWCXl5aSvzDES/ijFdEBfX1jvVyLCYnHOunmgcz+Vzv290uib0rNhWKVzNFOfh5Vpj4We+Q5gfQInucRlrQ8qsdERydCLgfokm0SC0Ppkq3c26fUprKza26o+dctZW9Js/rc7JvVBtXYao3R5DtYn78CrhoeVQTsV1BBYf5lrakDN0sh2e66ihlmz4dkgm/8Ts2YDLz61ScXqnUmkhsrKC6usobH+EiSzhm7z9/pgGJtStrH4bN8YL20szpoNO3Pzf2LWbOBYyuehpsbEynB1BK0RdZpfQKSKa7uBo1nKBhyrzfnGk2tsnOR+gFtjt78il/01DtZfvJ5qerbykWNUCvYTHF/TmlCt/HKubGkpWf3Fksz6pJd8NaF+6+ohf9sn1lQ5yWX3V/GgOevlyrymvplkHZ++Z+jf7SENTnLxsK244GX0sj3gflJo70eeHFl/q2U8ds35616WM+vTNWJMxSvMYXcA8H+i2p/QM1dGLfd1Pbxdki18SbZmVPQOgvyfGKx3jylreTal7DUlsL5e6hcP4MaH1oHS8pJYf0Hftcz6jTwf3RZspdgk0h2x4h1REzFjv95FWLuWtlnljHJ4oDKSe9V1SiqzcmNe25teFuJhRtZfl3lwEFvDUMRLr6yR9ZdIj7Um1l8/IbP+xUq1FvsT264w8a6w1rr9yq0u8LTdmsR9Y6XCt+UQ2eOkRP0Sb5H739oe1sdLYeJ9sNhWTqsnvhZZf3HGri2xvupz4QqngEivtUsKVHEIz/Zcu0yr2yfoImr2E5zTsYp3hOKgVcTl7mdtg5PkS+fCGz5p4SHxMl71wPrbkNujzd9rwz3ZnB2WVXtm5W2Z0ctm85l2Vrz+kSItMPTXNavXVQ/6hKXk0novXp0VAGpNcrnJVUGfzE+oQ8wKBsV6/QkgUas+XRoMeBTbLw9VK3hU4uNmOSCARyWOH+g0MPCoxPOCs5UDiUrk9Xq7tVSBpBK5v3qTMpAUKx2vjwYkxWbIqmngUYk8XeVasYFHzVX+OhBpfbJ65xsbMJRRWr/uxgNXA49ak7ghAhpIFCvdAmxW6biLNMAeo9RFMewHOgcoDegpPxuid3MGemL97b2bBvq0JokeYGmATnMT9brGAZ1WfdEbooYtr9Gr8bMBPbE9crXQgJ4y+yydO3sDdMrkRbOtqwuvqxvoU2YXIKdOwZ04c7n1boBOxhitR4Uui+p4ffqzgT7lvO0j/J/IrHfZacO6knPWbQDoKfNy/bIpbkBPmWmMmiMauFPm0J1qAdCwIMr73QRXD+6U9/HfeHSsm+gG9JQ5GJSaFhsAVOZ3vpyhCZNnprfD9AAC9MR63RIwJeb22uupgTsZy/cIAMSFGtBTpoDbl8LprHe3Mw3EKb8PLd4wTBZ6s0OuLhqI06rPt/wj64vbrcCaVuUlfn4Da/qRvljL5catATQVXiTLZgDQtOrvXmENoKmQ+7fjgtWAmAqvq89LtQbExHk6i7oGuGSUchAAXCpxO0Dx9ajQ9NpTogEuFZ5E1E6tgSyVvC05VIEDLv00SbNJ5H68ATGVvC2x5E8Mm+T2wGsDZTJWOS0HcMkoZYcFXDrY7+tRy+TGo0dLwKVCbkVbnNv6GSN+j5aAS/wTuieCLBX2RJINFVhptgzr8ObrO+tdZ6EGuLQqL+GRG+AS5yxhQgNcYst1ZQEurfpL1JcGuFR4KpSNH3CJ9XqqBVwqtEjQSymQJc5fz5sgS2XZlVze4GvgS6s+Xloa4BLrb269DXzJ/ISzNwFZKnwnThYOyFLhO3dan1jvBnRq4EtGKZsB+BLrJaJpoEyVonBfvrSx/tfoJ4u9b0msT3Izww5AU6W3vfTSCKCJ9Xq+A2iq/DbZfvWVmQBYE/+E483SQJlM5tr4vBl/m4MAmmrcRvKTMZWVl8gbDbiJ9XrYBGuqb0LkNbCmukf283LuIE6sd2BaB2uq74PvdbCmVzZ3UKaaN6YqqqYDN1XezKoC7GBN5v67Nr6y/kKHOrgT5y/X6h30yegvUfs6AFRlP9tbKYFEmSSylECi6h73Rv5E5CQuBe0gUbVurh0nZbZ5OldmOuiT+fXz5quDO9W2zQV+UTTWu+vPDu50UPo5D6t3Flcd0ImVjtNjB24yecpeD9xkSkMtAzpYU+VnxTybs1XeHCQ6cFPlx7ycogZo4sxvkXk6QJOxxyvDbs2QS68OxGTKxMkZcAku/qbluzmDLK16N/xUB1NipZwEO8jSqr8EF+0gS8ZynX/ZLNf5zwpt+yMC5g3W9X5NB1niJNKdr4MsNXpeIdyGTSCmxm+yyK8AYmK91xIAl0zOso0BLuHNaTOH+vpZv9gCmTniZElmpXv40oGVjFLbgDrd79WeckZV5s3NQ1UNgNKa5OI/1oGVWO9wxQ6sxMbcHHo7+JKxXzZF8KVV78+AIEvmM+X4DLJ0MP6UM2qz0JJgf5KYh1Awpcb3pLwybFvmsqkAJTV6Dmy7Xpf5el0HSmo7qHd/AhzJ/IQcwUCTGscOkgs/0KTGEY3kJ4MmNXI49CY7cCTOWbcBQCRjiba8Wkv0GgAQqe1nzaq3giNxEnkzpYMmtU6uR9Ik0KRGMW/1J4Mmsd4rfAx4jQP2nl1TOghSf1abJVvr6KY90JS3u2vSSVMHRFqTXFzBOyBSDxtXORnfrDF6fgE+WvWX+xod+MjkL1c+YEer3g1L28GOetxu4qtxDPiIwyDorgp81POP9mjgSJ2Dulzwe4d8TZL3u5yF75J30CROopscaFKnw1bniKoDIhmlrq9hLdErWxAkzt8JmNzBjtZIC5d4Rx3giPV6BwR8ZCI5eJbkzRLZbECNOnvRW0+YzO+MdOCjXrdmr5oNCFLny1ZyqARBMno5hoAjzdp9+4bdAEda9RentQGaxHqHGwxwJLZEIvcBmjToGPT2btEATVqTXG5aDdAko1eNc4AmDTojvgGuAaDESW4h/QeYkvkVbdWwX+F4VQ1wpMHbEJkzONLYh/1TztEqtc2ASOP9hmgAJbFerkgHgJKx/LyVGwBKCLJmsI94znKAKa1JLocvA2TJ6GXLB1la9ZeYhAN8ifVeAwBfGvkF6xggS6vS3XANMKVRthHAtzaz3n2LfAAosfIWiG+ALA06l5TD6QBWGnTOqKsGcGnUVwU4rNJxbxjASquyXp8WGiBLJokiGwN8adCjG3J+H+BLq/7CFQf40mjb2bpZ/ET6hGJN0j0aiMnovfJs1hi5rBogS4MfcdaWDNbfD/UGyBL/hNztDvClQdepnAv1A2TJKOWUB7I0xlY4p5zzppRtJpcvBFtcj5hlm8FDN8+zeZCeLGmsvI0wuf/QksH6yyOMozw2fycixyjBWu5sVEeJtjQk3xh44+KhHZwktAOeMk/ceqhqtHhpwcS4uICCUVCnfCVBlnxpVq8HAfgjrHr3vfWBqPxGKcunok7zesXAOV8YNbCyeOc+o0ZWVu/8ayCyOCv1kFUz6/0Zvxabs/td1ea53T/NfP90VFRfISgnO07trL/c7xt1sP7WnBC1l/MP1nfiexf3+xNasD/hTegtsrJ4NGY01CbtNCVdGS2zvrpTWys2Z91OWrU5x8utpdFQp43Y78WDerRuk9z4/wCT4wAgeieCALGr/hKRZvTA+uIOvD2y8sL9Rkfl0lGaXnr1zPqLB8JA2EvWX0qmst4Nlzf6rNnwbI1HVVPvnOQCZsfc35dA0ap1NSHOX9ifuzoYPzdzRrm5RVWOOzdG5CS3PebcQpmf0DU7t0fWeGcQnpsYhBi2z8Sokp+re0rixngco9nMbyf1Y6Ba92n6lPlgpT5ojg+WMKteL6WmPrDei/I0ldHarBZ1U582vejXU583S/RQOZOgWikoyrbrabTrmUkqJ9FxV6a+bT/hlU/fchbjxtQP1nvLmPiEh5XJWe5OZbDWnrvzVEZrrVoJTD1qs1Jtyq8LmfXF2VxMZbE5qzXM1NdNf+w7U4m6Y7cfz4ZulWrBMPWoO9qB6raNyBmBw7pqn8kpC1sSpypjZKWGilOTrP7yavn8u7z9xHEwnP9aNqWYsKD5KpG2fmqOmJrG+ivomH/XOUl0CPn818HKW1NMz6Z3BocU7Gdedn8zSdwyP7LfqZwVGsN2vuabPWsz0pGfWiRMfbF6hTimvrLeH9lS25Ta8m71Z5eYqRzWZsXD45NRlektbJn6YPVqZzT1kfVJIpSpR53S7OCNcjlvSlmGwEQxb2hLNUWQoljWVeilcBrr/YEXpGhVRnnaOPXD5qyLHaTI5K8RykwSbBJvxgcy4mLRxgMZRfKF1v0UyCiy17HWF6vXbR6wKO5HmacvbVapGwAwUWzbOd0p52GVCrvFB5jokLOvD9ZyPdYBGZn8bw0G7Ci+PkGeelQrxyiW1QqCFPncVi5ZwZFWvQ7VNfWN9V7M+ansVqk2aFM/WB8vkzvw0aq/BoWbSYL9WG+oAT5KFOrBm5WAjxLHnZBtDPjI6GWxACKt+nDpTYBIrL8uHgCR1iT62vjUd9aX25HKTDIrNy33gMKl54IgJb4k5SzDwI5WZdrDaSYKpzmTRE4SHTY4lajcuJ1pnpTZKr3hEcjIKL08UZVphUWXgPMzCaoyb9GAT5l3Vupg6VM/rF6vHACLjCVyLAUyMvnLdg5eZPKX/Qi8yOTvrAZBitKLd6insrDSu6o2ldXmqUkLMFHaZ/NTzn3LWZfD2PTnFhJAh9J+S9cPLjSTBE7iLkQDAFF6faV36tOmV/NmACBKfIarZpMAOvQjPSqUQ8ade3EAFMoPVaWqoAA0xPrzadFUji1nNagGoKHMp4qqywcAokw3MRVsn/q46eWXAhPlRO6+uzfpsw7dAaSIk8jlUwAvYv35sGYqKyuzngQDeJHJ+TxDBfCinOm2uOr7Abwo540/u3rs+1e9fphs6oPNX44YAcho1YfdIzeacQDUKBf6BDWYByCjVe/FIZnKwkrtmzH11easex+QEeev2zx4Uaa3z+SWIYAaHUrm8KXgRWy5rlZQo8xeRnIEAzJivbYc4CjvXkwnyzMr874ky7wkC6BGnMSZSQN4Ua73Q6ipbNZgueYM4EW5rWeFl3gpM8ngJOm6AQxgR5n3jM64AWrE9ngFDl6U328qA8YtY7bsnuj9Jk6Uzr+w/rKpDEBGmZ9F1p66M0njJFfngZmkcxIdNWXqh7XKa2kAR6z06hS8qNDWydmBBvAiXHVbur/szuBFq/7W/cGLWH+5WDSTlC3JBQYGUKNCz0BcoizOJI2T6KumU9+tXoKyAIhUONCrU63ARyWvbUxbAnxU8obsTjlHVl4QWQA1Yr2exUCN2HJn+xDAiwrfanEGGZCiVZm+j7G4xwXqcYBFJgKS0y8AiwpPLk6/ACbi2Efeig6AiKMSeX0NXKjs3q0nZbRKvQ0BHSrkmnu+wj+VeVPK/gsuZGz2vq6yMu4VF03FgQgVdsi5sLUAKGSSyG4IIsR6b3YDCyrsfeQsmcCCSt8GKNcGgKDSNxZ3yhn1OGjZdnh7lMoQRKjQZUY9LoELmZ+QfRx0yOidpgUoNMey1c9HF0tnfb6FHJxJBifRflAxgA7xT+g9COiQ0ctPAB1ie/RcDzpU44bZD4UJOlT5bE6OAGBERq8vps0klZNc0FkALKr8BrcuzG5NOl+zncphc5YfG4GM6ovQvlMZWKmjrU49KjQTQFYNLIIXrXqX8UaQoro7+ZyUqEqOSahtrqzXnu1T31ivL25Pfbf2bGvgzGvgCGRUyR/m5jcVQY1MEjUxRVAjo1drmwhqVOm6+uUliJkkcZILDIygRqveC443lYWV4VLFoEYmZ104qOJOHURb3lnvLikjqBHnLN1RIqgR56w7IKgR651ZOIIX1bHtRFSFghdxksu1vpkkcxJ3JxWBjIw9TgcHLOI85YI/Ahax/lKG/fiZvn7WaaMoB1oPZNQICG8DQjUDAqhRo+cRb9AjAhytSe6n3hHsiH9FAoEIgsR6Z48WAY7mInu99y1HG+CjVe+e6EXgo8Z7rguUiCBInORSX8PqdZ8FO2r0ZocenUCQGr+FrQhYBEfiSDJeHwdBWpUXD6UIgtT4pExO3yBIjZ+r9iypm1JOmgBHjV4FclhNBC8ySl3aw+q9WQa8aFXqKJpTH2zO3mIG1MjYrHNOR5t9PeqRH/uWpQ1kxHrdAsGLWC+PkCJgEUeMuXxvt3pJySI2WIfYNX6spDmHPDaJAygieFF7s4OL4EWs1N0HvMiE6JGfCV7UeUiXAxGoUQ/U6ZxOBGrUyddic8FNFGhlJmmcxD1/j6BGbMYlytxMMmwSPV8AInHEG7kXi0BJfXc69fVxy98pSaCkVanfVp561CntxeRJWQRQ6vn9bgVYqec3czQGGM75Uoao1vJ+EEBLZ72edgGUet3O4FSzAVniJBLYRpAlDvzidRCQpd7e3iCb+mz1ugEDK/XdR9HX12P+hnTFtcOCL3U6qHIcrSPIkikWOc4AK3U6qNJtHlip01ULXU3ASn0PDnCwHECJ4+F4/RQo6X3knKnPm95ZkQIlGRv019VN78wvIEiDIoDpHgeCNDg2mlPjIEgmtIsaDxMIkslZzVwJHGnwtfdzDSYQJKM8l3MCOxocgVyVcwJBGun1NjCBIw16C8OZ4BII0iBXjU+9iJEqASKtSfLuVPON2v/qvwkciX9FLuoSIJKxXw1ZCQRp0EO0EnokEKTB47ksTxCkQSdTsscl4KPB8eKclgBwNDjS2rkHJYAjVjoblgRkxNY668MEWDRevzw+9Z317nFbAiwyOTs2ABMNfjr8wgcSSJFJcl4YJJAiVl5eT5hJUHdtdW+WiCYBE636y5iZAIsGb1hk2wYyYr2zZU6ARYMOvHQvACzinOWaPwEWcf7hgnYTeJExSU3HCbDIFI4cnEGKBk9AsmMCE419kvX1mfU6HtTUF6vXAzVgkcnfmVzwHOgTaIhzul7qrCz7hqjSs24zyeAk9/uAKT+cxF2SpRymMhF+lx0kR9b/2tGfck42Z0npEx4/5Jy9QSkXm7Nut/ACM5bICS6jNvNGq4xj6nrpNcHd6dmvXfs/MexP6HGmPJtJctwrgfWXg4aEF9hY782JBdXK707qnLPVXywvrK96H5rg4sH6a+8o7ZjE/wlULt8I0J+AyuUNkTMp4Iz6adutCv/51Jkk2My1MTXan/BqFu/GGLNvcz1eg3na5t/lG4PK3fneyZjKygvrTjiFe/aLcubsg0uyb0nk3qQOa5K3vmqo1rESDwcFpxZYefe0SS1yEjfCQ2rJKnVXbZn1+ln2qZ+1GZ7Xbmyp1U2/j6tr0KqZpHESlzSmNmsz0JvI3gq8zXoMkZqW2u2m/rC+epw29bDlLPtmjzZnb/XY06bUOWdriV4n98J69+ZO6qhEfmFKdvnerF56p6Terd4bPME2Qv6J93Uaj02iVwIDFUoBx7yqH9EqdYGPxPqLR1NCeNdAAc28kRNBWAPfHbucvydEJ+Ukl6DrM0njJJcjhjS6/YlL+Ywt//MQmh/UaXvR8fMTrFKet+YnWr1cJ2SsMU3+Wp9Z70LF/JQt5/OYnx9UJU9Sqpzz01hf/dLrr5XD2iD3FDk8W86qLWXE8QrsO3rulTlEa4mzD8oYcsK+3T4pUWv8gOZ5QZVDYWXan0tI9FzCTFJtkptbfp7tokZ6a+lSerMeY3gx6eRpSI3xdZ/N0wrSX0BonlaQXofOnvpo7ZFjTo7J6uVon2O29lzsL/Z7HXSf46zWyDHc9Jc2q5eboBz7MX/VbBAIIb4PFpfTY/XO6jensOWsVggZt+EjIWvdzFJi/QUr5YRq5TuD+kuL1TtO+zmhWivtrZxhGYAo0otI21CQzVAAUhTr61tdGZjI6GUxghGx3vtMMCI23iEzGXQoLrg1XWYfMKK4eyGeckYl8qN41hOjsItgBiZKz8bDfWMq6/0pAIDI5Hw5Qc4ARJzECdGWgYZY+ThKQKHEAT8dg4GDzK/rR4FnklmVKZDLvVPpIEKJQ3HK/ggixDnLfTceXSf9hYR/niJne7yiBghKkXweLjfa8Mh2TWlzHvCNGZvemSPAghLfbZfNFSCIc9bjA0CQ0TtrIYAgVnorBPAfE1XjVoBAQCbwyOVKIB6bNUmcIzM8r1pNVJBLzIrPa6KpbBDDJEmUZGxJnKkQICjVzX3opAys1I9+RjwOWRMdbOlJDSxo1fujCigQ5+wclOPVQVLez5rxKqDJ3CFjnyfsjFJ/YD9+oK9HJfIbtbIjgwIlfqlWdk+woPT6ZduId9WMPU7cjwwWZJSHy2irTx1eVDNJdGECB6X9QeGTMXX7zDOXwENYNXHALllBAEGJT9/k+AYcxPlLGolXmEz+etoCC0ocPczp9WBBebl9Fr0TcDwERMpwKRNQoMxX82SjAgvK+70500PXE/bPSzWZbgt6iwogoLk0XF5K0gtOIKBVHy7bMSCgVZ90BeFFDpO/XCfgRQ7SX44+8bwG6d3lFt6yMDnLwRwvOZDe9QHDmwY1x9ejHN4TqDm9gBV4E8AoJZBEGH6bsxpSEPa+ZnqjyvtG4KBVeTnW/4R1z/n1SI7468aSyyuWEbHGay60BFVNHdGySX/ZBxWQolzJYVvr66a/YCKErDZJnEUUglWT0nXARvBmUl5W/ghRbGzQNQtAxPk70xDC99a8vyAsNjiIsFtxx+PlhI44uDUT93PO3RC31Sid8R8RWKuJHHI5ckX00Fr261e+2f2oPxkzWHnZZyEGpNFLboOYiz/Lf9Zp4bsDckQCF1r1FzcPhAMk/a2TggsVDkopSx50qLwPhY34dkavaxbLrkJ3DW7x0xCyziTRRYqFgNHLoRWkqOzXJVR7BjLieCw3/w3EXaMkVdNRRC8j/eViNcJukT5dd7WfQFPGJNm2MVaV3Wf40CsBjlalfr8yIhCRKU95PotwRLW88UZG7B9SXnA6ovJY/f52QFzdqBCYxxijuwBQEuu9YgREKvvrV6pOwZFMkltjBlAqfF6s7e9W7/ABhPogZblGUvoEwCj7g1wySbC/cnkzNyJsRi28FNEv/0YEfqiFzz3lwAjKZPS3/gjKtCZxX8RArAJSukFcPxf9TZ7nDSAuypPytnMBUGK9bvbASqXTTkQuXQCXCt9zkT0XcMnkr+1JVi8v4eISs7XHtplm2gxYkzHJWb4CMbFSXjnB/dda9ms1qnWBNXESPdqDNRm9nEbBmsrYVrOHjwVl4pwdnoa7g7XymYXsdKBMlT2vblsMUKbK21i5OQVlqrRNvi5ggJtMEq9kmjXGLcNulXodC9BU43s9QBPrJXzD/SejdxwtcEup1j36gYkQTjtZEKdK23ZvugdrMkpZm2BNlUIr3MJG4fJHrfzepS6ZZvW6DYM4Gb0cJ0GcWC/pSgVxqhTNdWvAjQE4vPIpyQXgVEAn/gk5V3783Dl/SRTh9G30kprCb5r0l6kKftP2ey9zNxyKzU84rm7wxq2Vwko4zBxurUa5hUYpHBoFbqc2yXkAgdupUd4eRICvJSW5BKf9eEQaYy5OffBzND9xW/7BwbDWsQ3IvlXV6uX2EC5spK/eIRRcsaxS9Vz4TFlLZLMHiWpEuR2/YrhKGaUcveEQRPoLE4OnDOkvDnvwfLGWO2UIDMWW3Lax8PKgJJcBE74exhg5gMPXo7awoUVfP1jvRp2Cd0NtkRznpCWAUazfgGFmYAhPgdoS1ZQ0Hjxq1d96B3gU63XvA49ie7bHfzM9/htxwmxNOq+icZRaG78Upj+2W708DvicpLW8uV64epCoxuEmbqMZYFTj2LbyE0CiWC93STj9IL3rL/Q5bWh7hAppfOEkxSMDAOQmc91ngZ7a+wtcYOTWEutTUTmCJZB2bZXGKGcGB31alRdfIPBXm7P8WDCoVe+upcHMSBkuxQj0xJbr1gIAterjHkoocighYJXa2ovNHeABKV1veeyMbZ7abFRl37airh7Qqb13k8DGy+qdEQmgaVUmD79gF1LbeD8Fgy81JgBezrMS+/6iqOrI4EucRJ55VVAm8xOyR4A1dYqw4ZzwYn1klU6vxJRulBdYilm6dp5/7Xya+CYjpl9Kclv5YOLq75/pxHRh85cDHRBT35cE8qtRufsULJM0TpLuK3m0evMr+kMG6y/uB2huRn/9CnAnTuI4w6BEjXJ7xazyK2Yfef/BQgvciQNMySOPCu7U+TL15Q5+BXfiJHqeAn0yetnrwaA63x93hkHQJ467pRdOoE/mY+XOCPSJLdEDOBhUL9sR9sFyoCejdL4R6KnzA+L6GwvrL8HnK7gT6zWEAXcy+cuVPLgT26/XBuBOq94NRN9AnFblr0nQrPnXYbaBOHWO8ehljqrkGL9qDd/AmoxeFWMDa1r1+aYvrL+sVRpYE+sdz9UGxGSUasRoAE38pTe22UCc+vtQzw24qQ/afZz7UQNuMkppPFgT64NtM4UxewNuMj8hWwJYk9GrQaMBNPXx+kS+ATSx3ok60oCYWOm4DDUgpvH85OCygTKZJLJYQJlYf9u0NuCmNcll6GjATay/nWs3ECdO4o02YE2r0nW8b2BNRnneCzcgphE2ZisNbpwk6fVMA2Ua5Dh022o1gCa2ynEkaABNY49oelKiKpf15CWiZgNfGuxsI/s1+NJg/yKdf2Z90oimgS8NehIx7E9XxBWRNfClNYmL7hv40uB7MXIuAF8a/N6il/PYzJbFArI09hs9h5wBlNgGCfQagNIaKC94xxMNKGlVJi8seQNKMvH91FKngSNxcD9ne9jAkTisnzykbuBIh0iDvh41yCdZl0P/Bo406msI2UCTfqQPVu+cETdwpEHYxKtKcKRVGb1jowaCxEqH5Dewo1WZ9gEtmQEN7MhkLmsTBMmYLQcHcCQ2SZ5LNnCkQQ/s6nkNHGnsLiuHwgFBGnwf/zYDAiUNvpjvLBJq+sKa+21I/1Yz6y8vHbRaWO9GUm21bsoLQ261fWH1vwIQ6x5Q+Gpbq52TJM91udXBytvs0x7Wuy8vtBZsznKv3Vrc9M4A3tJWIJdoS62hQuP2IOwp87Ipb+2wVU5yWza3tunlCqH1zSRdR4P1l31364/NX9vTUbPkIrJNAfVPusTdeuQk9bKI6mn7Cdlhe7b5O4GPWi9WqVehHZXLSEeOwL2x/hKavvXOen+E7GNTymoaz88sH8HqpTtcG6jT3ZfV1yfWZ3dKHdkqnSO5NlCb7LYq29WorK8a6LXRWH+P7NdG35I449gYVumsRvrzWLOdPPsTrFJ6tfUHldhoPlIF2J/E+ktwuf5kq3dmov6ULefLqN6fykmK107601h5iTnTn77lrMaf/qAqO53cqQVDDw/ro0aRPQTW34+ee4ibSfuygYh9D2n7FaeyQraZO/NpD8UqHfjQA2pzbKcwJ2VjpdvFeuisjHqz3MNgfdJjbI+zHgO/UCnrMQbWZ7fLx8jKX9sK897rus/qMVlj5Kq1x8z6C5jtsViTbmdePc46DeH1nNVjY717OtxjtznL2afHwfrLaVRPz2a5rNmEmo3bsO/rUb+JZkOntafEykuQ4Z4y69P1YZSeiv0Jr+Onuin1ZzbWX1zFekK10uuZusOmwXo3mmvPqFCaGeXWtefA+vuLlj3HLYmcTHOyJsmTlJ4z6/N9FsjFmnS7FtEzqpgm4ts9nZ4bJ7nsr3vu9ie8oT4Pq5R7n15Qy/ub174+sP5yKN9L3PROeyvJKiVa6SWzvno0o5div9GBqL1Um6celErbbHAm6zJrcE5+9s0dP+fB+he9qc6qjHSBQq/ZamC960LTa2TlrVEBH0UegWWjAj5ive7XwEeR5gLn0LADH0UeTtX+pYMdxUzrGW15Z/31S1Gtu7vdukoJH0L0e5UCgsRJnJOXDoK0Ku/HtR0QiZM41wA7IJIxQ3YNEKRIjn93Y4o1xtv7gCDF9vpuUQdBMnqnqYMdxf0hsJNy2Dy9RgheZH5dNhLwIqOXjRawKI43WwZgIlbeHnbsIEWRL/FpY8r2E7fZEMiIk3iLfMAiNsZrrsBEc0n6g9dDOnjRmqRetgPgRUa/x3UnR/QOZHSw6mA/YNGqvDDSDli06ou7EQAsSuE17exARqs+X1/j6qBGa5K0R7xPHPG+AxylPQjtyf7OynRZgYAaJQ6He7mPP4CPUn69DBiASKyX3sIDEIn1DrofwEdGeW7wA+Ao0SvGTicaAEeJtwBq8BygRom2GHJ2HmBHqW6XmE6WdKu8lDOqstEe0/lG8KJVeX+tewAZmcwvBxkDyMj8yh6S7llD0g0gI5PkPAIMICNW6moCOGK9dC4awEfme3X+qNa+jl1ODx2ASKsy3CwZNme5vByASIlX6U4ZAh+ZnJ2OBny0Ki/xRgbYEYfFkwBzgB1l9ok671YGqFGmR6xuB2oD1CiH9+MPqFGmA6+Lvm96RVQG2FFeVt3xUjhgR5kIjITqA+wopxfnHQPUiJVyKTXAjnJ6vU0bYEc/yr+w/lcnVZULgsSFI6njAEHKefW/cgjPADsySmdyATValZejqwF2xHo5Rw+wo1XvOgINICNWyuXoADJaQ9LdXxoaoEYm6p3TVQGLOHNvPgIjMmbIHgFAxDbIfeUAIDI2ewWIqqxbXz4ogYbyDgBPysDKCysegEImKJ8zLAMKcSi8225igAu9iuM3wIXYDG/JBC5kIv45PQVEKLetg/tF0Vn/a4EnP3BsSdTWYIALsV6vssCFWK9Hb9Ch2f6iqU1fn1h/QdYDdGjVXzb7A3SI89djMhhRJi9ueQQ8wIhY78DYATrEytt2ewAQZXb5dtY24EKsvAWdGwBExp7bYAhAZOyRjQGYaNUnd/YBICq0fXbOUAa4UKG9rW5goEOslzfsBugQW3KLeDaAicxPOG0AmIjDM+q1E2CRCecoPxawyOR/cS4a4EUmoqNT8uBFnLmexwGLOBCinp0Bi0zgRDlxgBQZvdM7QIoOUSjNrp+2ZkBGJok2fmx6pw2AFB1CXKoGBlJU2AFMNhvwosIOYE7JgBQZpZw+wItYr5cu4EVsue59gEVlD83k61GziwP25V31AV5UyGFbt0nwokJO6efr5+kBJmKlynnqA+t/3bYw0XgW56iZJHISj+pMJaqVn4MXxTj1mfVZXvyf+rLptVftTFJtkkv5NPsJajSY+s567zbuVKJO6wZqDkqAo7L7xrs2gBqVurk9+F17JkGdUkBFr4EBFpkAiWIumPq85SwGjakvNv+Lvm56p8ABi8r+JuBJiUrs7zsRYBHr1WowPYBFqz7fInHNJLNOK8WO1l0D7KhShOezo+ZUzgqt/Ay6rFBQo8pgR4ylUz8rtLIn8x60JIy1k4IdVXauPu7FprKx0jtimMpuzVAwbeqHteHy/F96gIzYGN1sgIxYr+sU4GhuVKxjla9PVq/2fVOfWR8uXQ/gaNV7J19TWVnpXRqdysbK6CxgphIVyjxHtlvwItbr0gYvWvW3gQu8yOSv49rNJHH7CaedAxmtyupswaYy2zz1hAVeVHnC0npUZXvrLTn1jfXXW7EzSbdJ3I8dm9Lp/gBHbPb5HH8qUY/0GIH+QICjOra27evTD/WzQtuzri11uwVBanwN2VlXgCC1F7d1prKx0otMPpWdlZ5L5FQO++tb6I9GEVPTA2pkzNCb4pkk2F/xuhiQUdtvRbnlDGTU4rZnMfMarZxBjTiJ7mugRi1uvd7XV9brYNFTj2rd79HI8kT9ZuIezroC1GhVegci6QE1Mkqxm5t61Okew81cX61ryQMZmchst5YDamSSyPYAdmSCs2l9sXq9aARBYnuui0ZAJP4J5VYx9ajc5eW7KDf4Uz9Yr90e0gOO1PimqjM0gSA1OiTVLRn4qLGjptYn1usrNlOfbf7eLgP4qPHrqE4HAThalf6mHuCIld56GLyIlQqNTv1gvXdFOj3gRasyXNbPgEX9WT06Ln7OM0nkJPViPKjRqk/79YpE1ytmkmx/wmuBQEZsv7dbBCzqYW3VeqAALFr1+r7b1HfW39oqYBHrz2cBKQAWrUp9KjH1qNO4uer5+rjpVckE8KJVrzHd1Geb/+V61ExS7E/I5XEALzLR1c7rxgBS1GmJvq0HGoUym0n6lkQtNQOQkdHr6HApgB31vK1SZJKw/YpsFWBHh5/w9ahlniidIgU76jvfOykLK3WIp6mv1gY5mgWwo15ps3ke/wPYkVHuL7GuT9rNJIOTpNt5awogSL1uLedgD8BR55dhL8uGAHZkkqhlQABB6vTeq6LxU59Zf+vmIEicvyROAfio82GubMCASJ0Oi+UOKwAl9d3P6lT4g5V39hUAkUzm5xk5AB8d4lOdlJGV+sLv1KdNL3sHwBGHnHJWEQHIyAS8uhZI3T5TG9Os3tmrBhCkQTu+SzjlmWRwEh12LAVApPEi0OtUojaZZJ5XgwHUaPCDZbchHfjIJLkNSuBInMQ55QkgSIPfBL+NMIBII7+9TTD1zeq9TgF2xMbIxVIAQVr12e1EIEics57mwJGMzc4yDARp7O+w+zmjNsu2aOd170O1CYg0ylZH/k8U1ntxHqay2pz1mhAoaexPufn6bj/W6xcASoM8t/U0AZq06m/TClDS4Oid+8OmaxyJmSRyEu9S2FQmVuoLwlOft5zlnAuUNPiYTI6iQEms91ovINLg+4aWxnyX1FIsnZNcztcCUNLgy0TOagcoadDdfz2VAyUNvrwjixEcafDsLIsREMnk7/Qj4CPzjbIfAR+xXi/SWv3qJnzWhYCF1jhJuoylrduf8PZKbbBSh8VOYW7Ejd7BL2FuZ0kZv9utYQLUSed2ECFXrDuub0z6QsiV1UXZ/kSkm0QzSeYkyTspC3NTQsp6War1anN2TtZCb6y8nO6F3ll/WwR21OkeXfxgyXhYeXELCSPYnHWZjMh67fw59ahQnsLkcDSy1euJYxTW63BSU19t/pf3/mYSVC5fs5WVOzrrLwwqjGH1clyNz2P1TmOIT7CWK9/CqY+sr7fIGDMJ6pfvz6rFT3wy6y/TU3wK63WUgKmvVu+A3/igWvvrvU98+qZXk0h8Buu9m8UphsfmrKspBKu/VlOI20+cB/kYUKH8JNk182yTyBknhrLp9fdW1l+OxWNo2yfImgp9y192wDA2+y/TfYyzijmukVwLxRhYf3GNizGy/uKBE+Os5RA22unrZxWH/VLtof3EwsrLhivGanO+6GflhkLTvRxwYmf9ZaqNcbDepQoxoU75AqYcmlJgfXauX00lapNDk8kyScnqn/25hLji8ZgyJ7l4PsRUNpNkMabK+lsfT4313kuFU9mt0muKCVXJ8W/lXJMf1sfb4+MzSeAkLieMedZpfNZNn26HObHeda6IeVZlpDW2s52MeVZijKSUfSfXTe9Mprkdcz4p+w9tGFbvrXbKrL64u8y5OZfAei9U71TGLWdpc0lW7zhyxJKt0puXS9mUckYodbPhfMYaC+oubzRSNfvSOcnlGCuWsf2ELMD62Py9Pl7DZonOOW45y25Yk9XrQb6iQitNN063rcUqJayLtbL+sg2JtbG+3sKUzSR9SyJ7UB3bxzrtvD1bznZf3/g4ILZgk+jyaahZ2lk4HCC2xErvxvRUZlZWJ2TWVJbt151BGLDooDRPsjYqimbN0I0QsCj2Den4+mH1eqIEMmK94xkegYyM0hm9QYoOcYdOymSVEilEAKL00JbQOg9ndh6OIEXp2SiB/xN10zttD6RoVcZbzp31yYOcEYzI2CBHQpCixCd0cjwBKUp8POeMbGBEafc+VSMPMJFJYvl/Y7QYQYrWJNHt72BEiaP9yzIHIzLGXFw3IxhReu+NE8GIWK9Xg2BEib13zj0ugQ6ZnM/QMoEOJUaFyoYEOpRoEr+5uyTQIZNETSgJdIj1kqMm0CEObbR5qWX2UksARImGX+f0LQEQpbaREN+Yzvq8D+yF57gERpT2SHEHY8CIOHNdWWBErJfjTAIgWvXhUlPARInolvQnTGBEqz7uHunft9F+Fw4wURrb1TzjQjAoyazcvLtA+FY1q5fr2ARSlNkZwzrFVT4dToBFJomauxNI0cGkQ5MAI8p8xckeDhaKNjCTzFrOdLdXlw8wkdHLVgdMxHqvPQMTrUrX/SwBEJk893f91hCaM0nbkshhBIzIfOZ5KkmgQ2y2pwQd4pA4ummBDq36WwcEI8p5m6R8fWJ91DNUAiDi/OWaMwEQsf1e1QMNmS+93FpKoENszOXp3pkEdVpo4XT9lcFJ9E3zWUIP611Ek4CJWLl5QzUzlIEXZT6oOm8oEkiRMcNpkyBFmQ7LvNYLUsRBdfTwDlKUycXC2REkkKJMnh43V94EZMRJLk9fzSSoSn4B4bxxS6BGmc76vfEWvIjzdEhUAi/KvJfZry8Rj01ARpy5ww0SkBFnrlcCAEemKOTAAnBkjL+s3hMIUgkbrpFJOie5EKEEgsQ/4S1rwY6MMTf7AZFM5tckcfsVpyuBIBml02zAjrhMvKYIdlTYf0BOcGBHRu9Z21jpxSOays5KHUFx6ofV69EVyMjondIAKeKvkzvZBFJU9hdCTzmj7hLVnc45s/6yDUygRoUcQfXiEOyI87+UYbP560UIwBF/r17vARyZ75XTBMBRyXQqdMGACQSpcMR1ZyQHQTLKMzROIEis1MUIgvQjfbF6eaCfgI9MscghGhCplA1L+npUa10vc0kemICSOCiKbsZASas+X+wBSmJ7vJoCSuKcdcmDI61xSMLewCLD1QSOtCa5ELkEmmSCtDjjEjjSD8KtJECksvuRnnLurLyNeMBH5hvPq4sMfGQCuZy7WwY+KhymTzWqDHzEemdmyaBGZdDRlWdDfq0sVinPiTIwUWH4cF5vZGAio7w4zGSQImO2Lrqx6VUvyIBF9dmO5w7GAxOx0qFhGYDI5KltSMecVbGAEdUXQfamsrBSR8uf+rrpVR/P4EI1vEajGVyospvrefuTgYOMUs34GTiI9bf7axlciJOkPUo5obYMLsTRcpyj8AwitCovcW8yiJAJIqT1ZdPr8qlW7xwbZUAhtvzm3ZHBhUwQIS/zwcrL7d0MOlQ51IMzIIMLsVIXILhQza+XZBlcyFhy2ftkoKHKZ+hOawEUWpXJgxgZUIjNljgrgwjV9x4IGTho7oLs8HWyZByVbs6gQKveZZ4ZFMjkfHG0yKBALzNPm1K2QLAg1ut2BSJUxzZ9+/rKev3S+tQ3m79ut4BCrNcDBYiQscdptCBC5kudRgsitCrdOAYZRKiR99fNGSODCDV+QeDMDTKIEEcl0n0HRMjo7cGBifGSAYWMMbK7gQg1JiqyNoGDWC/dBTNwkNHL1gUo1PZAfGZOXA9uMqCQ+YnbwAgo1DigweXgOIMONbpP4Y1LoEONj2vPm6YMOtTy5gnjF05l/eUwOoMRsd5r9mBEjR6p0S0TjMjonQkXdKjxO5jSZjAik7PTm0CHGvlZ6YELjKixH5fWox6JZsuDlQxG1HhHZs8Ovlvz76YLTHT4CdUOQYo4ieN/m8GIjPK23wEm4k/QvRuYyOhlkYIRsUl6MQBS1Pg2xP6SF90yy0BGjcOKOuUDWNT6tuI9KQsrb2tpYKK2bAPDdxs2cCOR2Y2TRHcuAyPizL0tAOhQp6uIDj7N4EKs1NsocKFVryPzT31kfbkP0QBEnESirQw6ZD5BxxWfSWa1dt5oOGt7ACJWuiXZrNIJi5GBhmZjXR0t5JALNMR6p4UUoKFVefFALgBEq/7i4FoAiHrelse+PrG+XN20CngRJ5GgsoAa9d012tdX1id986iAHbH+8mL4TNJtKck+VcCOOr8sc25jBdSo8+s253ZbQI0Oebo2gB0ZvcKVBezooPdfWpxJsk3irKMK2JH5TLU0LWBHP/pY1Gl9cUxcQI06Xbe8BU4swEecRJck8JHRyz4LdmRMcooRyKgTgtZdCeCovw+qUACOOsHw20XdAnZkTDqvHguoUW8vwE4BNeocmEJ/Zrd652ijABl1DoQuqwbIqNO6QlsCcNT7NlwfLAEyYqUzuRTAok6roIsNebNZjp/gRf39ndwCarQGdHI9+Qt4UeeQDk6NgxSZGEe3MRnIyMRoUji6ABmZSE1qPVwAjjh/hxYW8CIT0MmpSvCiEV7cUSogRYN83uTquoAUjT1Yt6+vrK/XmEsFsGjQq3DuZ/ZNqY0fVu8NgMBEbLYEVgWwaJT10FMPgEBGgwPGyvEBvGhQpDvdCEGNBu1bL/agWimynDxzKUBGgyPXyb4MZLTqvTcBp7LbnF3lYGXUB20FmIht0DaDEa364J1pFqAhLj09cYMLzaX5271hAR1a9ZdgO6WWLzx7vDIfpwfVapW6ndfG+nvkt1K7TXIp9vGFN5ita5Crbw/r06XwW/gaHPhle0I60RPSM0nkJNGdbVtipfvET2mZleHSeluxZusNVEPNJnKu0HrUbH7fElpnvX74b+oH629tvj+sv9wQLD1s9jt11KPNWTeYnmzOukF21Oz+toKvL6y/7Vl6ZX28lQxqttPc5JVM35SyTvs45uzqx8P62+JhoE5p3NNfOmbNhmejc2qxMdc+ePl73XHL1dpcFODZ77sfWpnLAaO8uY6UOWNTklvLnHMOXhaPpuWcjOmsjJfeOmcb0l/8f+oc4E3+zgq8zqGalO7rBvWJVik3ofVJx5zFFa36ZGu2dLWqD+qU3wVQraU+lfXuzb76NJuzwxXr061SYqv6DKu/3bSqAbXJ76CdsVINgZWXCGA1RJvzRZ+2/M9jVw2Zle5ZWw3F5in3oTVUq5dr9RraVnqXjl8D6rRtN+hPxg+rvDnA1/jYJM4Gs8awmXG5vlFj3JJchtwa0/YJlwsFNeajYadPKJtSDXQ1onL5DrscZGKzejlE19hZf7VnsD56W9SaUK2DGvytmaXASeo14HBN0SaRU3ZNifX3U5uaZuXGh+5PxVuSWcuRTvx1l0zV6i9vts4kzSaRa4+aOutdL9yaxpazM1fmWcUxvt5l1xxYf1m/1RxZn6/+hzWn7SfkwiDn7Scul7hrLjbJtQnlapM4zqU1o1oT0ba4LRIo6G7NnZNcVmU1D6vXQ0p5Nr0s0hJY7z6pU0u0SrmzqAWVm6nznnevtWRWBr1srqWw/sLHakGFlg2K+vrGejc+TC2dlZdj6FqGzdlxLasV9VhfeKHUGqxSl16NrL9NUjWxPt8XCTVvP+HMO4BLbLzuDkBMJuf9vI9ubVRQpkjkzZvuAZciMT1nb1uBleL+nMdBCaDEed58YCqYUmQA6BgMlGSUTjkDJRkznE8DSor8zIdsTkBJc11i0cop58rKSxiZCojEOV8s6ZveKw1UH4XxdPbdFeAo8RGPHGoAjhJ5P15XsCBIJon+icT6cNlxgCCl/SVKX19YHy/jCQjSj4qo/dD+Wa2JH+qSMxo4Unr/nFYFR2K9Ln9wpBRen/JXcKSUN29MX4/6Leva72JPZv0lZH0FSkr8HLzOv7Le306CILEl18YPlJT2F6NOmaNa6zp13rYbDRwpURhVh2g1cKREAVollW2gSZzz9ghF5kcoGoASJ5FuqA00KXFY1HOxN3CkxGFOVQNo4EiJArRuoWkKOwc2AKU1ybV8uv0JZ2JqAEpsvBwNGmhS5thlu/GRjAdWyrQllANCA1ZivbNgaABKmX3Xdc6Z9cXbjzdgpcwk2al9ACVW6qoBUMq0DXS/rm82XF5aaQBKJnO1lW6gSfwTcvnXwJRY75yINaCkzGhd54yqZBfBC9hs4EicRGLtBppkfkI2ddCkTP57kks00CTWy4m7gSYd9KfCRLUW2rSqKaOBJmXacN38LRtoUuanEy6uHQ00aU3iBtJs4EhGqbZpDRDJGONMHGBHuW4DnZ8z6pSO83QHATjKdJyn2wDAUaa3feVirwEfZTr+0/kDIhm9hbqR49U0cCTzybeaBUpak4RLzwJHYqu8lgyClAcRWjlaAh8ZvS6fyvp4fRu0ASLl/XrayfjOylszBjtivbM1a6BGma6n6YkM1MjkLJccYEeFptRL/on1F3+ABoLE+btfWjblZT/egI8KBVbV4yrwUWE3GFlNgEj8sXp9AojEem8GB0Qq/O7hGVM0QKRCIVv1CA+ItOrDpSkCIhUOlCrLEASpcCBWOa6CI7E9W4TDwBEOG1DSbJdrsctBBhxp1df7DAWgtCa5bO0bsFJhN5vbT4AvlbTRPJkEdc3rlsuRWQNoKnnbA8okaUsiR05wp7Lf6TBXTdfrMw3oiZM457kN6KnwnXFZEUBPXESO3yCeozc2SP8cPN4+SnlNY/D4OekvUQ7wkLjJ/3YhAg9xU5LsjidAT8Z4Z10E6MRmOz7DeP95lLoq9WgJ3LTq3Sh8eKzYKG93bPH+MCV50c6Bm9h+vQIEbuKf0MMOcJP5Xlk+wE2lrWO+t3MEaCqdiIRTkkBMRmlD8mZ+uBaPhZokeoUAylTIm0tSPryKafR6UgZo+pE9w+bvbAHwzuGo78P24pFD0t/vCeIBwFEDIb5zTeHBPVJW745eB1/iPG8UCK/hmczlJI4H4sxPXPSzTiu/jaimDDxTRvrLk5F4iYv0lzsjeCbL5H+bW/FSFiXJV0qJJ61G5fjGl7tdHdyJk2wxCr4n9d91B/TESeQwhYetSH/BSh0YivVOlEs8bDXq+8jteMFpVArPu205E2858c4SJbm8yorXk0jvhtPE60nGmEvOqFyi1je/GjzFQ0l+heU3Tg4ricKzMyaJMy93MKjKE9zFdwUvq9gksuUAQ5lPlr0SGMp8rxr58aDHqOzxJVsmYFSlCVFubfCeA+lvoxYw1CF/0xnXI2m8pTAqPyN4ufiAtw5OSXyrCutdqtCBpNqbOK6I+k/KeCvJWbMtkV7X1Nj0dliLzPYR/56SVI15O2BUo/jtjmsH4uWTMl0+Fgyq5fcVBBLV+EqC1her180SJKrx64eXpSwiZ1OSO/DvQFKN3kyUZ/oIF036yzKvA0yxSY7fAsIhG0scRzgE9B1t3xf4NiTWX/gM4rOa/HWbBJLi/K9zBJBU46DrsjEASZlII/oTOusvRwkIOWny9wofSKrz86YyZ4Cpuaddm73aLyO0Huld5NWBpOaG9i2TRAy5Mbe1byOpdiCpVe9exUVwNVKmS22CRHHO6bbIBIkyxutiHFYvd6mI+EV69xwfgbKsJc7EBOjE4RS2u3WV79Yh6hUliV5EHUSlIuUF6iIilDFGr59BnDrHevIsaax0KRYiAI3OL/VcPPEQp4eSlKv7GWLYUBLXVayDNZnMb1MMWFPnZ4ycYgFrMko5/4I4cZAEPcSBOx0CCJwsqaz8FQ9QfmbjJP4oBOJ0iO0gM0edctRB+aUgTqzXC3gQJ5O/HCtAnFjv1SmI08HykzJveSpcg+vyNmc5XgE3Gb1sXcBN46FzWDlcADfNcrSBE09fOliZ9UCE289jxG2dueeMe8ykTB7XxVVgq1Q1jqvApL9c78WFV5v/ZeAaYE2DT1t0sVT7E7IB4M7rGHRuIqkdbpqSPnszC+6YmpxvlwJwzdRmLssTlOlgjK+P1iTHbQYXRk3OznUA3HQ8faaqUzCl8eZGAG68kfJyVxeXtIz+UiB9s8QC7cp303APaYzyvo7AlAaFkby97IN7PPYnbt0EfOnwK75VafsJtffBNQvSuy+G41qDVcoqA1YalZi2mpXgk0561x8SPuCkjJfGAKDE+v9f2bkdWozCyDaXG8E2b4KZ/NO4prpn2iVZJZ9/FcYGg1gIEaDLE7Zs6ix3pU+YsClZD2IHJe35YQ27D0F6Wobpsk/oMVmGebpOHC5ZljSd0QnItYUnLvqJgd17Pd9RzrwnOJTskyx2+0Ckp32N/LoT42lrkuxqneBNU3iwuXaiFMkya/qDjzZH1MhOe/DR3o7VxPad7fNDiyeu7X5zDoSNPuU0pmFk627LmWaRlifUyGqiCaz/XKX1uNIvJwjg+QnluE39PpzpMU9AhtgM0iRnHE8wgX2Inmh6d0/I4jnOhrLTZLN3n0YTplzGxunvdiq/nuTffRtB5gWPnxNIGnP2IW2VgrXH2b+7TXmvLPjLRzWm1ccdVY47OntfViPXV2e/6Rb4/GFv9RnGNNlMORsXLAhTee6xXNna6x/7j5WZP/eiGbPe8/IPSc4Enz0M+xwZXnj2AW4BbyjqN2lGkER5HHL9R8EwgjCx3Z7TmIb5VA7DZdNwJ3TP7Sqgf9mF1qUTLQFYOgCXTcOQpL1OW14UThFNDasa06pP6x5MyYLmN6Qab0gdRmg1+i9ZwwjigWlNbxp4qms508hdXtvXOPiC+zThRVhDv9xJG2kEUTV2MaY1mbh3NYISOmO7GdPknDYWMr/LZ9GOBcMIsoXYnkbwr8dk3CBaH240aqVlcbZA3Gjd5ryDoGLtuEJWoN6kHZeABVHC+4b515T97lG2M0GyaXTfWDsjuTX9vVxj1f/7lO0MXLbSyae8NWhjOjnpPNdGnuutmUYzsqjhdga+WzMobFj4NrdgG0G6cd7OD39r5tcFRzu/DwsiH7ydbs2mem3f0KetQHbSq7nKKKbdThOwIE0t1M4XtbV6BwPtWLn66OXVrUEz8yHJrGtc22hGsKnYfuVnTHV8+y24XH3eT9HcpsWY6jPit6D6svUa5dagjSmERXeK0o0gzbVwa4bRpDF+t2YaTfvwnOVfJtWcxj7NaNYh4QeoPyPoPuXWPyT1v3GgnlYvj6nx8lc8/XMo7KEpRqOzxt2CagRRnr7btBlTHSB/C06r3x3yuU0s1pq3YBiBjkG5BfOvT1hOkFxefGu2r5Uc0drPP0S+RrvcExRJuwXFPSGa2BsamNMOyX+1oZn5KEHQI1o3ps2fDOl0MuTWDFf8u1N9m05fvK76MoIiE2PdAjQtoWv9u4BhsSC5dejWXEajA2tuQTGCnjiGIFlluj3Ql28KhsWmSWW6EUSI4zYdvhrZVAJ0ZYqXfzAAVllud+utPtuYDnmEtv2ArgodRdAfB+iqMOuVfzoAVvmwz36bVl924NWBWxVCyJE7BGJlTH32VO7AQFeV71sK1gaAVmz6vgd+my5jOrL4iluznUb/r+BW9SKHQHYvQKt6OW/g5QXAqioFtL2jkNu0GlMdeX0LmhMkRw9uTXf10ctDgKrKGbKDbgNQVSmG9j2S5DZd76ZxNbYTaG8SuIoFyR2stwbt6m8ljB9SvCD4/UCv6qDWzZYLAFhPzb/erYEMNHUCYNXhOvNblYYx1TjoFkxftvRogbH4BZJ9iluz3UPUTnT7gWpVTqOWPQRgq364g+I2LcY0Cga7TdHGnBBWflCArbq+kuxb0I1A3/1xC4YRRFd43qbTV0bj+1uz3BtHVAEkq9KWqhzeLpCsut2qIxZcRqBjCG9BMQJ9S9wtqL5KyaByAW+Zh9hVXadIklvT3XPk8HiBbVXKjh900gtI6159WN4Xl728ICp7O1Ndb2Csdj3R1/uGxW16GVN9t8ctKL5sLTit2wqN5ur3vYCxWCCXZBcwFgskWbvAsEyV9AedXhB90GVMkzn4Ar1igf4+YFituZ2rWHAZQUrVb00xmhY5YxcwVuNDOPKNwbD4BQLgfYFeNdoBlF7nBXTV/F5dLEDT8kET2XkArYwg+HHBqhrPoe8LuAuUypjKcRyIqvkbkeKcBremeE0CZC9QKqORrQtWxYLo+4BSGdP3JcsFPtUWRY0lWxMXENVTE/qRF+DU01RvUN6C7QTv4RDtApPiqqu4zVuApuWURnIuAZPiTEVy8XyBTPUfOTzB3w0m9TS9gliI27S7UqWPeQFIdVo2hdWY3jRrfzAp1iS31t+abTSJK3gBS3WeGuS3B5N6CmpEDC7QqKepDtq8BWhXIo56uAST6pS/XLstYFKdsrsnWexuzTCakvRnkCl+DT0Ygkw9BTWZEsGnWKBbDXyqN+LEwVAFMvU0zfwXkCkuW7ca+BQ/IfonwaeepuEmwwU+1elmX+25AE49BeEe9wU4xaZRpwec6nxcTTqYIFOdTqEFq6ULTOpbNUCjOp2F044EmBQL9K8EMtXHl0EYTKrTcTj9BwFIdX9+zsDy5678BSbV+UbLoIuDSXHVAxxygUkZ02zgBpbimlyZnwIy1em+T7kBcQFLdcbx8q8DlnoK0utgbk01miht7m3aXH3eUw7cpt3XxLZu55iLC1iKiw+Y9gUg9bHSy5nq5SM4VN/P2U9dUtgucKjxo20fOZoCQj0F0bHr27Q4UwmKLqAoFkQeJSAU11sPB4BQ5kXlpwSEGky2s78ENOqpuXzPKbwJe4FGDeLy0dQHGjWuD6y6gENx7YMFZgGBMhV4/zMK2NMgOqFOGNyC6mqcLYkK2NPgS4Pe/48C5DQ4EfX79FsAm9g0/CDzvQLxWy5fDfXXFSAnfkKSsqkVUCejee8nBdTJ1Md65pNyNd0aNG2lvVz50gBPRqDWdAXg6SmI7hK8TbsxTTOu3xo0MPuFshFAnZ6CokeEAvZknqDGswL2NOgahqjJQJ0GOakBtCngTWwahDEUYCaugG4jwCZ+xWzQK+BNozvC9laf7kzl9FTAmwbtVcldzgLeZASyjcCbWBD4rAW8yZQdDCHgTeMR6FBlvpdbgEadeeaO27QY02S9V8CYnoIEERcwJhbIybWANHHtJYMp4E38hCvZtingTaZW+jXQtMuxx/jE7a3ZRjPCXxbgiU0Dh74AOXFNdL8HcrpXXl8DoguQ01OQELYC8PQUJP55AX4ygqzJQKC4VtHQAAJlXsAC18bhGwUEir9SsMQrAE/mgyo/twA8TQqETDK53prLa+Q3BYE6S+GPaKKAQD0FH/4bQCjWRFML8NPTNMSuBdTpafrvlUGyJqeNJx+gC8ZaIKdZXITTm+n2pvJfAWyanL86GxdAnWb9sEVVwJu4eO0kgzdNn8goFqBFP+cFuAVoV46B0J9oGIHOznELphHEgyEIFJetB0MQKK59QKAKCNTkmHg5/YNDGYFsLHCoOR3GiQXVPUG/LmjUnC48LhagdRcFn0hHFihqfr7l7hZM9wS5S1WApSbd7Zucc781p5mfadqSgMkCJrUoQU46BAFLmYcE/RRAik0lJi+gUVyfLHCoAEuZd5CNDTjFtdL/PsjUxzc+zbzofJj2tsGnnoIoMfptuo1pElBaQKa4bO1Cg0zxE4Lt4AIyxab6BwCZ4i8jcXUBn1qVmimhmQWIatH9UdobAKLih2SBpgWIajXnDcQPWUaQ+fagVItXVKrhKljV4gXku1tQwarY1IH3zuC9AlqZ+qieVwGtWBDWpzlTuSapIFYvAtFkFehqUdR8sOVfga4WrzuTWK8KesXFZ8eEKgDW4vw19gR8oSQsrQJgcd3kP1SBsV4qFguKEQw9EVYwLE74l9zcfmua00hfqgJmmRSK2fcFzDJpDt8H1gqMxaZyBqnAWFyfJOfOrdn+Ie8rrQqSxaZZHH4F0lqLWvp9iVKBtNg0OLVRAbOepv8GG3CijHpRTZrXRMV3Y1qS/gyYxWXrwQIwa1GETcD7KzDWovOBYb23MQ0PRFdgLDaVxLMCYz0FJUsndmtOi+6fW9PGD6lOEKwNK0jWphV5sCypYFhcqnSsKhiWqXcwTQBdmWoo/7kCXT0FOWypQFf8kKgLAF1txghyZAXAMoJgPAK6YtNgtVYBrTaFx8jVWgW0YkHAJypw1TPdXriHXkGpjKnsgGBVT0G+uqlgVSb9nxwtQKw2pSHX/RHEalOecz1dAlcZQTAQAFRtznQe/EdAVKbecn4En+JquFthBij+f18ToIofIjF/Ba4ytYreFa07iN8oD7mCVW0OLZD9B8TKCGTtQaw2XbGZhYVVEKtNIZTS0a/gVnt9JsIV3GrT9KQ7HLgVPyEIyq8gVlx2ci/ArRn+BQInBbiKTfWcA2hlypa/L6DV9okBQgHQ1eYT/nLZBHTFT9A/GtCVeYJ8aaCrzRd6JLuBFfTK1Er2bdArrlXk5IBb7e284rjsu5nPkZyv+y71cCsSZIPugVbmCdk6vx5uZR6SLggOtzKaLOKsHoBlNJIn1AOwzoGkD57hAQLWVDbFWfOSIOveh1uRoIdz/ZrONDtyWNcymswFWtu9QDS6bDQwX28T+B77MqZ5rFndxWmieXtXbyrHiN2MIIGwdXcjCOOt6x7OVP9cG+36cPeuZCbeywhKMsLtbQRNz8Tt93NPcKvbwqvb9ruMJkl71H7FP+Td22o/NDDtHckhsf2aESSL0PbrRpCc4Gm/4QRh7dHAnDJDf5llBMl2TfttL5C1v35OUF8Sez3HknZdRlOjoaFdxRUfbFm3q7pSs73edjX3QbOcR+1CA/OJ6veBtl1oWn9Phywebfz9uHC7lhPIaatdaOPHZlNJveNWfkaj8zLegtPGF0MHNbS0A6qMwI3sk0f2dogVaULS2w6osvV5H3fbAVW2VDX1tgOqrCAqezrT5Due1r0u90O+lb2dqZy82sFVF6dzlJNXq5cRZMN/LV4Q/L61GtPi279ylEGr7V2jenLtRhOGVbaKdqX4C+mDtTqNoOglYavLC+TsUtHGlPe4+kRLPNw2NDMdno26Z7ucqX7jhgam3ImBO9NaNab5dm9rzWiSzJitdS/QLzB8rYIhpKF1+ahtNlm05TVBb2vbmCYZGVv/ubLdLcWdbim+NWjg+d0h6Ghgml2iubpXY5qEc7XeXNnRr9i7M9XjZh+uMi4RaOc8e61Pr0l2A1tfRpNQoNa3E0R/zEAD78+HiNphWNcfEvO1w7DO4XrrDqs3PhjrnLJ/3kGRfaVDskjTk3Hl8CwSVJ8vtnK+2HZ4FmmSrfp2qBYJkpCJdqiWfXX9hNPYhWPP5ZR8qBYJRhQB2ublTWXvmMVVRn+fWb0gGBtnc6aSHLXZ/ZeRI/sc77V/qwza9ZF14Up+A2Cswrnj7UjazEgKklUoF0R2krCBZBXOx55sJTeQrOKvs355bwAsfg25n98AsMogpzjJytxAsgrhfu2ygGQVir9P11iAWWW6ddnbS6OxKd2u27WenE6kAWaxRi/qAbMKJerV/xqQlnmCdK0BtswTtACNvR00iwXVCErivINtlc+XEt6C7p+gBaeZK62GsnNdDZCr8kJOP2QZQcu+7Gnse6ljEzhHgg7IxQLpVHUQrqcgzEzWwbaepslmWQfhegrC3HAdbItN5fqvg21VDkpMdpk68FblNP1qCuyAXE9Bcs6sA3JVinzMnJgOzsUaOVR2cC4jSLpqB+cyb/Lu33Zwrlop1iVoNXCuSgcJkxuObk0zmhCjdeAtY/oej9CBt15Kld9k+tq/084OsFUbbX+qAasDbBmBjTPoHGfQAbYqXXcQhF90IK3KWYjfPfcOmGVMZacHyaoMIuUQAp7FgsA36+BZ9TvT7eBZdTyphLses9D1mLdmGk1IejqQ1kElxq2M67OdQIZVdYCtSpOpnBs7wFb1efVjQTGCcOnaAbZM2UG3Ac8ypcovA5j1FCShOB1Iq3IufS047dp4utVfZhlBzz7lfheIeJYOpMUa3aUBtvg1Mie0g22xJvrfwbb+8tIAW83j6FhwWrpRqoTIZQDSal/SHnQgrcZJjt/97A6SZRIDZoM9kJbJnRgMroBZL0kQ30wvX2pQadCrRntr0agEetV4Z/B9fdnBrdhUcoMOemWqkU1MAFhGI6cQ0CvzAsHMCmj1Up83UzQhR47JIQnQqnF4mvw4gFb8BOmfd0CrNmjlE3QVsCo2DfBrB6JqlKNIIqoORNXGh538DjLVOIOQWm92kCkuWy5QO8iU+SZJBogOOGVeIPg7gaUanyWXvQBwqjFnDjojsBSb6ncFlnoKso8DOGWeEFWm+7LlQA4s1XiRrL/M9AI58gNOGYH8P0CmWBA5+wBSxjRb1QBINb44IIFYHWSKNenqCXDqr5rT0p3n4WBqAJZ6mtYoXVwHjepEEELT6UuVfRMoisvOzvF30CijkUMVaFS/aGEkawUa1emC2+QJxT0hEVT/hKCTgkOZ2mdjG1BUL27DQXUe0KhOa/Bs+6eDRnVO0qO/LNq7uTC9WLCNIIz3HOBQXHawKBkgUJ22PSWvH+BQnbGvckcGOBQL5Hw6QKM6wWhJ0QZo1EuVRHsN0Cijib7mdPUJAioHCJQxTXrbAIEymncfbIA9dVr/uk3/wfmpBtjTU5MsJQcIFAuC/ZUBAvU0TTLqDOAnLlv3BUAofoLcaBtAUZ23YbVgGkECAAdolBGoP32ARnXe3ZYCoCgjePfHBlAUm+rKAEh1vzf/Vnb11bD0Z9B92bcGDbzdPvJb8d2YJhFQAzSKBUF85ACE4mpEfzcgFJsmrXOac/xc2F8oAIQygmx4AocyGuXrDXCopyAbx0GjWCC3TwaY1FPQ8lEWWGrwtb+yjYGlBl8srF9juidIL3oAS43LdY1YsN0TpM80wKQG39IYzL6gUc+Eg8mW1ACKMikW5esCSHFKQ929AaTME+T3AZAyT5D/A7DUnwRoY75K+d1FHIBTT9Pk8NYAmTKCoGyQqdEc+ArLBp8aD9/qSqZHUKqnILk1Z4BV8RMiRw+salD2IIeeKqOnAVw1OP1RgvoGcNXgHDmyBYCrOMNY8pWWE2gnAujqKfjglYFemQxs8kcDveKH6B8N9Mo8Qf5oYFjz557w0thgWGwq6cUAw5qcQfidYQ0wLGMa/DGgV5MPrgSuJLjV9Gdz4hpvIxj+LtwJ5+O//gx6ZTSy54BeTQpX08MtGNakcLXI8QC9mt9D4Qbo1fRHVt7K7sY0PFgxwK3YNHIIQayMqexVIFZPQZLpYYBYmXpLfwHc6uUJ6tcGt2KNXlMAWk2+vCfoxmBVnKNNbjgOgKrpL82LBd0IkhvzBqDVU3D5gzmFI8UH6JV5iBzMQK9M3rtgjQxoNb9fKTQAreb8MuAAV3GCtgDwDoCqp2nm/wJU3R3UZjFWyyEQq6emhfMzQNX60bIyqvpp0UXZL7VHCji1ytOvkFBuAE6xIJ0xwaeemjA+cYJPGdP3Fp3gU4t8v5qwuAlE9dQkIXQTiOpF8Faf5uoje+8EnLr/8ucOjho0J8jUUxDuNk+Qqadpvp04gaiMRnnfE3yKBVFjgU8tCjCRo98EnFoUHhOk0J/AUuv71d8TcMoIono3Yxp/cgCp5c8hxtUYrmz5700AKSNQM8IEkFrj83AwAaQWE0fleU4AqUVpNGT0+gSWWnyrhxpcJ7AUPyHYWZnAUlx21FigUWsTypR9HUxq0elGuTSdYFJPQbgjNMGkTNnvA/wEkzKmybprAkuZmsiOCSxlBEkkzASW2o9J6t9zbbyIJKd7gkxtvn5Ndk+QKfMQ2QggU5unTtk9gaU2XzQedCEAKa69/lcApPZFqzT5vwNIvQjeKrONaXjPywSEYtPscs0JGrWL214Iqw4atSnxpvRFJ2gUC6LfBRxqU45OPdCCQxmBbClwqKegRbm5JggUm4b1RnM2h2SeH/7i5HkTEGo311gvxQNCPU0z/wMQalNcazQNAj9x1aORFeDJlJqsuyYIFL9lUnW0KB/JfAceE9SJTSWumaBORvC+UJ/gTXt8JloTvOkpKGl2zAnetGkBpWd98KZNyzoX/X1x9PcEctrzOZhJRjWBnDal1A4irCaQ09P0SlnhBHV6ahI+MMGe+CF6wAGB2px1XAvQ2N8P+ExwqM0HfORsBQjFAsn9JiCUeULwBwM/mbKDgQT4yZjK8RX4yVRD17u/C94qg3bdrpneTKcxzY/6T3CozdFNwRQLAsWm+rOAQHF9tKt7Fu7l56NyY0FxgvTPOivUwkmX5P7hPBzqtnQn4V4+0SFQxvTyhwXL87DgPKsN0oQRKfOwJ1N80gLL10e/6/YCOREdAnWuZHsCwODj7MubZt1zF6eJuueuxjS80mFutCgfC9Zv2Y2ghYPHHt5UDqt7+srImWejUYeD3bEAjUrXRQQ9bP1+zjRw/9fvMqZNLwjXrziB9KHXr/onvI/u69eM6fjHCxV9a/2608il+/oNV58g2mn90Kj7uV5wA0HngWD9ltEkm7/rt/1D1IS8rp9/QtC61+XLfv+v18FP5yrBp18gv+PBTySoel5YB0LZJyQjxzo0ijQhuFqHQ53LCp+39iUe+zooijRJStp1UJR5iBxz1kFR50bEZ3h40NsOhCLTcLm2Dn6yprIapRjBSK9xX6U6jUssMjmxyCrNa2TvL91X7N2HWmW4l07KRuvSUlL30LKMIPsHClq3k7se/F/1Z0yL386tfAPsqpfRJNEzqxYjSDjmqtUJ5JJ11WYEyR1Eq3Yn0K1W0cw0MUbzXJ3GNAlYWXUZQY32QVbdxjSJj1gNDcxrzyQr32qX0YTbA6sVY5qsDFervuzgz2rNmerv2Lp7V7nEW214geyYbRpBkgZpNTQtx8UG3aZtZxrEGaz+86bB/NMvY5q49asXJ8j2IFevRpMse1Zv7iHau+jd10o5squjaWkLWHL51acRhCux1ZczLfY2mQkf8b9Bs2+jyQbx8XMvoD22cbla6XnlYKlzO2/7w2scMmU172umdcjUudHXnh+K69ONYCSj/sFSVqCfML0g+MUOkPpbZbYXBP/kQVHnGuJnlLGs90FRJEgyoa9ZjKCm58rWrL5W+iFoYNoAjZZQsxvTMAX0msOZZleyrDmNJgkCXHM5gaO4gynumttrggFioYEpdCYI7lrAUoUuDggQ3AKQKnRDgh40QaP+JGhGEAaILNCosr9/cqCoQos+l190GE8TTIo1kkYsMKn6cwuKWLC9QP7mYFKVE+gHQwiYlDENxkqgKGMqZwcAKVNv+bMCSz0FsU8HIMVla58OWOp28u0hiLeyT4tWWnhmeSAWmFT1x/3fit/GNAkT2WBSLAiqvsGkKiWCC1ZVGzSqdhf7J95yA0ix5mf/jwtv83//xwaZ4ioFcXcbQKrSAfWAYG6gKDaVa4wNIFWH8+ZEiN4GkGJNlsx1g0mxJpi+N2iUeYegXUGjKh+Oe2chGzSKTeWqcYNGceac6KuDQ5lqvK8UNvCTSeCjBq0NCGUE7+P6BnuqHJ+ZbKJu4KcXjcn1Su0PAlXXZ29jg0MZQfD7gUOxaTBTbxAoNo36CcCTMQ1+NvCmSjE+WYrWDeT0ook/yPACNddtgKfKM7ByOzfAU/3CaTeQ09O06nw6G+CJax99TfAmU2+7Thkc/bSBnBod5HNn1gefWd+gTu3ndgjfqtSMaRIVucGbnoIS9jOQpqdpGNC7QZrYVC7uN0iTqYau92lXTlAk/aMN3sR5kvQMDNjEAj3bADk1vthG+UobyMkkWZJDDcBT+x63vQGejED5qRvgyQhkOwA8NTqxKJejG+Cp+VDyWLCNoEZLtA381Cq5HfJ1AaEaxzLL1wWEMgLZxiBQjaK3dbcDgeInBDsgG+zpaZqcGNtgT627hXEsmEYw/IVQE+3332gFCNXoBIv00jcIVON4qsAJAHtiU/0CYE9cGf2LgT214YiGmiHBntp0E97bCzRnqgcVsKfmPaRYMNwT9D8A9tTYd5Q/JAiUqZIPJaULOTYgVPMZ/cOHAEW171kVNlBUY/Qc9CJAKFO2bAQQKCOQnwgEqu3vwyg4VNsOX8aCYQQ93aHcoFFcq2gkBYfqFBEdzfXAT50O0EelAj+xqf59AaFM2UE1AKFM2fILAkKxIAtZ3eBQnS5+SReHAFK9fHFWgaJM8dngAxTFxWsHFyiKBTJ8dQNFmReQTwCK4teIFpdAUZ0jxuWPAiDFguhrAkV1Tmaoy25OoOdTAKl7FraXG7xVZhjTkdLjDSb11NSw9wNFPU3DHBMbKKrz/CymxP4Diuo86b6WfZtermx1iPIWFCdQa8VbUP0TXr/Jbdr8i77OCLdp99UQA9MtQHNOGuBtVP8/Gd7+dw68NdNoooNKt+kypnoj5hZsJ1CjQP+BQ3Fl1E99Cy4veGVct2lxpu/07zatxjQ6J3ybojk/xDLfpt2bChf0Fgwj0H/+LZjuCe/D0G26XNnKF7gF29de/qAgUH193VK+BWhLuo/4fUvwNi3eNPjq4FCdU0jr22NvTTMavWa+Bd3VR+G5WzC8IBgFwKH4BZKylxcEHR0cavh4wRdTEKhBQXy6OcGhxoeov9u0eFPZGcGeTGXkNwGBGld+kOY2PW05Cm2KBH0L7GnQZRHJN5lOEE1aYE+j5DF1t+k2pmlSzv4DeDIa+ckBnv7yrgBPo37vMABPw5/Te3ljICcu+92Xu027K1X5W7dgeIGcgwCbXp5geP6kz7+cJmpdkCZjqiOM+g/IaVBwgv72QE6DcnG++4y3aXFlR1MuMBOXqucMYCYuO8mjcGvQwByDHwylIE1sqidUkKbxOb7/Fiz/BLu3w/l+bs1+f4HwIeBNYzoXMhZcXhDMCCBNT1O9TXILqhMktW/vlYkF3Qn0YA/YxFXSzQzY9PKEt++DBl4uX4P52cnFBmZ6aroMvOo/YKanQFODW3C5WkXzCjATl619G2Cmp0Bfu3sLmquMXm4BM5knBG4rANPwycLjsqcTRE0LujToeF/y1bcvO6g3GBOXHTlDoEuTj2REpRZj2nxmlUaZVW5NNRodJHQLmquP4pK3oLsnaNcCgOkp0OcxbsE0gmwcB12aHIcZzBHgSpMyfSdptfsPaOmpKUGU0216GVMdq38Liqu6XhIDMHGOuvdoutu0GVPNd29BN4Lo+qnbdDjTpOzpBAk7vjXLaKK7NW7T7U1VfS4AJv6OKnj9FqBpOf2C5qS3pjhN4PNeYEyT/cD3kewCY5qdtj/VH3iBNLEg6MAXGBObBl3gAlqanPLn/a+7gJYmRYu+R4vdptuVmtwj3XGFPWmqdkQvcCVO0SYHPdyKXjhRW+alX8BMT03uS1zgTdMnLpXP6f457+7fBeRkXkPNDheQ03wkpi6S2/cL4Gn63NuxYBtBzU4c9gvsaXISbvnvgj2xQCWm7hcIlHlvG39YabuxX0BR63Jr7pd2AIFalGE6+svAnp6meuek4zZcI1C7nv0CgVqf7+nuFwiUeVEt2P4Jsr1Ao8xLvzu8FzjUolTRciK6QKNW+TzjXqBRLJD46gKNMoJgKAeNMqbBvwsaxaZJlH7HNYVWIwdGYKlV3XZBLNhGkP3vIFOL0wwFfwmY1GouCEcNDcBSrNGNBSzFAj00AE7xCyQ3AfULlOqpKb7timk7gKo/VWz6Lxt0O/CpRQc+tfMDSrXoZGxyDq7jTiDSRCdi+gU+xabB+ukCn+Kqy+XHBUq1+Pis/AdAqRad6I2+I+AUm2qvE4hqcdhRMLABTq3xgdldwFJsqqd1MKnlw6VeygaN4hrrwR40yghK0lWApRZjqeCzAEg9TWt282NHvnyj0VMimNRiiKWjjfoFLMWagPleAFL8unqUBZYyZcv/FUxqfWeIF5jUYm4k3QwwqcWkLHhdMKlFgCwa8kGjuBq6t4FGcdnBtu8FDmXK1q84vED+VqBRnM0y49sXsNTmu2D1G28jiPIA9QtY6mna9F4H8jmToKR05AKl2n7vTezAInex0QR7wRf41C60hJbDN/jUpixPekwGn+InZPtrFxDVpmTNctf2AqJ6CvKtD+RFLZvzFQXLdiCqp2lJnFqAqqcgdhaAqDblWUrKrk6gfUKAqt2/j4cAVU/B8Htyg/fkLhAro3nf+L3Aqjbl2g+40wVEZUqNTNGcw60jRBcooFR7fh6WCyjV/nC76G1anGlAEgvg1NM08XMKEBXXW45qBYiKnxCsmQoQlam3+vcKQNWmuzuDTYJyQFX9/Zx3+Wa6jWl6eLOfLElOkzDEclgVaXQccD+pj24BpeqTS6CTr4cFCcs96XdYEIa3nKwyzlT92iedi61M8EOd1CO2bLlPcFJm3ILyHGd0N77QxtWt5FV7lZ/TyP2xk0CCBVGqk34yKljTYKOjlOpN5V9SmhPolirdv+j7JI5EAZVT9UlP6qQLsALdtGX9VYCm7Y7ohoKKdh3PNbweiutlBMmq4xwaZ0ECX87RcRYkUT7nbDcLsj+moo0f6wh9lqufU8YsqNEqCEdw6xlwH6bJQvGcOGVNiZxfnJE0xUsv5JwEZEGydX5O0bEgnkAbmpb3kpNV6zlTxhp9pqmfU1ksiI4EdRyvMvUJ4lrPuaSrXnSNV8BmcD6HTONJ/BAoMk2CJs4RElu27usHP71Vhrdfnik2+jmZYWulp85Do4wgndAPkLJvItv1AKl6fU7W209MPgvC7bYTf86myTboiZu+BYzP5bjZlxNE01vfxjQJLTgxoq4ycsQc11+fUN5rHwuqf0LwD4zma++Jfn1S4TLQtJXWG4F/P4YxzaaTMb1ADoBjucpoH2NsL5Bfc/6cQHfPiQZmOq+fgAamMzL655rVCDLHYTYniAbQidalpP16VJzDC8r/sxsLz2QTt2YaTbhPebaKb9P5xTWd25gmnKYsNK0/nflS9rqM6YehfBWvke7aqq4+0Z+10KK0nfyenaSfzQE2zaatNVzZSb2nFwTNuZYxzdy/Q6BqoUxM+uc4HMoK5BByOBQJ4q9+OFQtxeHYN9PqTYN10mFPZFqiKJaDedj0inZkDua5TenCNc0oDnIiwdCothzwRIKE8B8Acgv680XlD3qYAwvClfhZhLuyE7p51uGs+Tce02DXR4qnflabrLmiuImzFnTFv/8WZxVoS5Xz3llB3YJBc4YWTCeQfiVWFbXQVWSBJ13BoZ6m/9JW9e3BoZ6arC8AQj0FySxZAaH4BQLmVoGfCt/Tprp+BX4qPHOoIbICQhUOSpKfHxCq8KitqzSdQLqJFSiKqyQdmwoUZZ4Q9GcQqKfppQefCgJVeUUiWxccygj0JQC3phpNuCipQFGVt5TeJ4UKCFUpnleeT6hAUZUTsb6vfCsgVC1u0R6XvYwgCTGvgFBcGS0AhKqVvKzgIwI/PU1DElMBnp6mxWeR/wfO/DcUgz1Von9yFVvBnqrHnKrPAD+xRo+bwE9cq2iCAH4y30e/AFq3UU66d0+hgj1VCpfJsEAFfqoc2CJ/QuCnSoEtyQ1ft6YYzb/rXxNd+9w4q+BQlfPJyrENHKrygC7/G9CoyrOLHNDBpCrNedL5qSBTXKVoRAGZMqa67O0EaccGnKp8mWnmMAFOmeckG04VfKrS2Ru5HK6AU3V9mWaApZ6moedcAaQq5fsOXPcKIFV9OnH5lqd1289hoLfilzH9Nwel2Tl+BmVXYKnmSWL4EYGl2veI2gos1ThmV84DwFL8BD01AUs1nzAnFrT3Kr18UzCpRtHMUZ8BkzKl+kyEP5ppgKUaBXToPgwsZQT642wjSNbFFViKBfrzA0uxQDuUwFLmHWR7AUs1ms5kuGgFlmq8facF3Qj+pR6xYLgqZaH9FXCqkYOjJxsgKq5VtM4DojJlB8ME4FT7vhlagahac2PEW9nFmQbbNBVMypQqfRSQKSPI5iIgqkZX8Mjt/wpE1fxtrrFgulrJENwKUMVV0h4EQFWjjU25s18Bqtpw3mgsuIygRZG7FaCq+X3cN9PqTHV3B65qPlI2FnQjGGFvA7RqHGUqvW1Aq8abvXKQArTi2v98qN31BLkV3OoPtWrgVm0RE1e9rYFePQXRve+3aXFlu9vmCt02d2uqL/7d+WmAVmyaHTNroFeNj38l5xEaAFbjHNXqd2kAWJzFTy7EGgBWp0O/cgBtwFidDzvLJ4BhdT4lrDpfA8Pqv8+cqYFhcZXkCrGBZHGVpJPVQLJM/sD3WaOBYXXK6BKsbBvoVacUN1F/BrfqBMqDgKIGYsWlBrNnA6viUt0qc/AqswFamZqoga0BWnF9ApDTgKs4f58c7BtYVadLFgL03cCq2FTusjYQKyOQ/x6IVec1e7JWbEBXvX9GVw3oigXJ599eEHRdQCs2ldNEA7oytZcjOACW+UQ2M16n++5vDdqYNizlmqsBYHHaOLlF00Cv+oeLb27T4UwDPtHArTgLoB4owa1M2bIvgF6ZessvA3T1h0SADeiqL/fTvLwuiFXnwyPBYAZQ1TlNSjAiAFGZUmWXBKLqFIxV/SmH63nKoYFSsSbYhWzgU2yqRxFQqs4BZYFTAT41Pt9g0xvg1Ph93sxoIFODd33f12ANQIpN5aqzAUiNy12n8lZ286ayUYGlBq/K5Z8BOPUU1HTfowFODTpeop0CIKrh4cLbG6NpebkXzFNgUoMXbfLDg0lx2dr7AZMazQEF9XGApUytZFcDlhrty0AJLMUvEMQnN2ApYyrbCExqdPeLvJW9jGnmIIBGDdpM1x8eNGrQRn1AVxs4lDGVPR4ciisT9TAQqE+Z2hrYk8mjlq1zgJ8GXSTrjml1PqbVQKAGbSxoRwL4yQii113GNMxR0ACeBh9AkRMq8NNTcOnd4Qb8ZBJQyRcFhJo/dy7jpfaAUGwa/XLAT5NuVJGIsIE9TQpt1dMB2BML9KoP7GnSeZJobgJ1YtPkavtbs41GJ93vDeBp0vVwyfVQt+YyGn376S0oRlD1BkQDh3oKsvUCOBQ/QfdQcCh+QrRcA4eazGmTLaAGFDU577r8xYCinoIkE2IDhzKC99+gg0BNmh3krNZBoCYP+cl42IGiJg/lal7p4FBGYLe+KmdW6gBSkyavIDyvg0NNOvefTf8dHGpy4oKo+OmKD1BJB3syNVGjUAd7mj7HwUvZoE7zeyL7Duo0/UUzsQDtSkduguG2gzcZUzX4dPCmycD2fdTv4E3TY1cRKdABnqZPmxDXB43qsw6oPgMONfnEv+z3oFH8kGB7sgNCcdn6gwJCcdkSx3egKPPGQVcDhJq8d+9h+Y9aADTK1Ed+HNCo9SMHXDYZaNSizfDAQ+qAULdnYrfy30xPo67inKm4GtsIRjpXd3Ao8xA1Z3VwKCOQPzs4lKmVmoU6INTye9tmP/wZBNvBoW6n7IkV1OTewaFWe56Ek3N1B41afJOqHLPApJ6CkobAdGCp5a9rjR+yjWCk8U4dZIofElDKDia16ECoS9c3OAiuA04tvrc1e29QqjU+B253sCp+iAtZmYyeOnAVa6KJFZTK1Od9HdNBqZ6mLdot6OBTi0O6ZJ8DpWKBG+0mn/HoAFWLlmBBQH4HolrzM4XpAFWLQqSjcQ6IanGss/whAarWcheyqW4DVvXUxBMHKNXTNNlU7kBUpj6ySwJRGYH8dwGq9gP7XZo+deCqzdDSuh/TTH4gVk9NEtHZQaxYINFMB67afDN58AMAVPELRK4WQNX297S/mY7vpqdRN2f/TY4cd7Aq1uiZAqxq+xTDpplo/gKu+stDAK02R0kHnxK46g95eTqgFQv0vwt09RRUvTnSwa04i0/yusMJslx7HdzKpAqSfzDolXlIMOqDXrGp9ilBr4xANgLo1fY3fsaC4gTaBQLD2nxiJ9mR7oBZe1JyP+mTAmY9BeG+ewfGYlM9gAJjsUCC2w6Y9RSMaPOxg2GZsmUDg2Fx2dGKCujKmMq+AHS1+WbzzKUCvdrLuW5S07wm+8vAsLhuQQqpDob10RRNy7dqyqYFutp8b6f+ptsJssjxAYZlHqKciAGGxYLszMM4DOvEa30dWsZhWCRIgsHGAVgnwOt5kE6/RvcC5SiOw7BOXJhNHxcLphHUyIkYh2SZsrMbIMaBWaRJxsZxkJYVyDc+SMsIgnX9uIoxDYfEcaFp+UIpC8YHg/FxNaNJ4mPH1Y0ggUfjGk6QfM3pn/C+GTeu5WuvfvxxoWkpdCjYyxjl503ffaZRLmOanNkepbiyg42+UaozlfPcKM1VRqKHUbp/UV374askR4SCFuXwJfmDl2UEob86ynZlS+dw1J8vW1amXu4J+nUrWpcChuXsMmr1AgtOJh+pGbU5jfStRu1OECD6UYcxTTI/jDqNIFkDjLqcQK4BRkUzLwfTQ0H7GUHzy9/Oy9/RLqfRk2krf60VWnpTBJzsS60ZQUlGz9bdE4KQqdGGMU0SgY82XWV0vzgM64QZ27tFY8E2gpZC6XEYlnmIHr8OybICu+TunDdhHJhlKhZg0HFgFpmGC8NxMBaZ1jSp2TgYy9ZeDngHZrVnkqQW7RuPg7HaSz6luGw08PdUjaNvI0g2dsf4GUESZzjG5aqke/Uo/gnJiboxqn/vYDAd7b0+b6Zo2vbsDnr8GcML3iH1GGjaTj6KdAvGMoLYRx1oVL8JHZY9f04QOfDzMqZZD5tozklkVc6+sxpBfpJ4zOYeEjlws/v6yDFwolGJU+uWmtMJgkwhY6JRKb96NBbM7U3f8cdYP2Oa/XLrcgI9kaziK5Pw/rGq0WQLj4OrzimKrwlfx8FVJEhO5Y0DrUgQbkGMg6vItCRu/MFVJEgilsaBVkYgz7uOA61IcEUx5+NAq3O+pJjBIy67GEGyfT0OsSJByQTNCJL9q7G7e4doEbLRrv4u6rjsaQRJ0pWxl3uC3GgZe7snyHlz/n5GkMR/zd/lBHIqn2BV5qW1oPp3SLzBCVxVqqOfvtUmQFXxmSBl8cNoenSjwASlKp3mCNVkE6zqKUg/6DaCpNtNgCpTpfeZYgJRcdkZ3Z1gVaY+6p+cIFZcHzniTuCqwt6A/ETAVeW7+zCBq56C5Gj2BK56CsKcdhO4qozP6+oJXMVly79+AlqZLGPyJwa6ehG81B7Qyph6vFieeHGCXrEmS2s3AbA4HZv+SgBYZbmz7m/vMJxpMAFPQKunaXhOYgJXlf3Z/52AVvX3YWtpAlc9TcP1/ASoqr/PYU0ToOopiLsuEBWXLV2dCT5lXtEf96Jz3hOIqvqrhd/qM4xpfo/8BKUyxb87vxN8qhbCLsnCfAJR3d/JJv4JPxEQ1VOQoMsJPvUUxJMPyBSXrbskyBQLMvIyAadYE9anv9fnzXS81+TNFC1KSUJLWmk0baflvpxCwKSegmzOAZCqfFmwnAYBpPgJ2d76BJDi14j+XQApU3xkihalLCDBGfkJDlU5nYfs7uBQlROGBL8fOJQxjWq8XDW0nwsCxa/ogvgHB/FPQCiuj1wqTUCol3eNBWjORXugWU8GhGJN+suCRhlNMJ2ARj1Nw3M/ExyqbjfYx687nUDuXkzQqPrluoUJGmXKlpUBjarbhZK8lA0a1fgiezmsgkY1us4+qjc4VLs+04QJCNVoAabnD6AoFlz+Usbf85D/BI1iTRb5MAGkWnE7im8vvZxp8kG3r4/sOYBTpjLBkAYsZb6PHNKApV5SZ8WC6gTRjAka1TilqC4brUtB6tEwDw71NA3vOJvgUE/T8NTQBIEyptGXRivydbWy64I9Nd6EDWoM9vSnsosRNA1cJ9hT43Wc7LRgT226P/Wt9t2YJjdsTbAnFki+PMGeGt0sp8dHsCcWaH8G7OkpqNHWwQJ1evkyUdkL1MlURn2fBerUHnT8ivYaFnjT0zQ5ULEAmxoFnsnBaAE5sUB+ygXexAK527dAnZ6CFvGvBd7UeP83Mj0t2n8ffPIFxsSmQV9fYEyd0mRI1rIAmFgQDHELaMmY2rmu867eAl0y9ZHtD7rUr8+xTQt0qV+f+cwCXep86Df68MuZBrPuAlfqvH0pqwGu1L9fCr/AlTpnmfCw6Pdc/i8AJn5I1MnAlUx93qeDBZzUORNiVCqak/Mv6M8yjCBZSy5AJRZIJryAljjHUkBsF6CSyVIkOyPQEgvkJsQCYOIsRZLMLQAm84R373cBMJmUScEwDbTEqYeSF+1OIJdvC3TJPMFGiAw+SrVAl/r3u64XGJNJ4ZQwpgXG1L+cxF2gS522PwPUucCV2DRqJnClThuxGRhbQEtPTQmbFkSJi8+2ZBbQkqlSqhnujaOpD4xpECQNa39adHBuZtnPgJbG9zTXC2iJBdK3XUBLLNAeCrjSU5DsWi3QJX5pPTWAMQ1Kdh1NaWBMf6rMaVeT+cmvcCncewE2DdrSk6xmATmN79fCLSCnwRuNcqAFbxpf7qhbIE1cGe1AgzQZgexzwEwsiJwu0KVBsceRrw26NL7HNS8wpvE9THmBMQ2+l05/9eUE6eAD2DToajq5mFqATYPzLGvBZQSZUwrkxILIAQdyYtMgwdcCbBq0potmHmCmMV0viGs8jCD7zQGY+AnRhAXANHiWlcMTANPguV/+UABMY7nav1QGgGlsAgey8QGYnoIRnYVYQEsvpqr3gjEZTeBdgi49Tat3iZpxiYCZTod/jBzylwVsegryLD4L1IkfklHwBfz01FxJpwB+4odEzhTwk6mPnE6An4wgSfuzQKAmn7GK6tOMaXIIc4FAmbKzRgCEmt8PiS1AKE7I9bNpO/7Z/f2vO4FDccaspNW2e4gciDZolHlC8g9tAKmXdGTxQ4oTyIXCBpaalYZetTGwgaVm/TyEbWCp6W+X59age3Q3yNTk88+qNTbI1FNQslotI6hROMAGn+Kys4FjA1Rx8bodgKtm/xxLtIGrnoIWBUxu4CpTdsleoBlNcup4A1fxQ4KlzAao4qoHM+wGojJV199xOUGwCbIBquaDl5Q0kd0Gq3pqWnqoYgNXTSI/ksttsKo5n5EHLptx45QyG9DqqSnRZL4BreZyFFf9kKBXkwKWgnjVDW71Unz8utML9Pc5bbx+T5QetTG41eIFpBzewK3W9xXnBrdal1trvFQGxGoVCrdKUvxtoCujkR8HAOtF8FafbkzDvekNaLUoEUcQEbLBqp6mSdzlBqta7QNb3kBUT9MShQ1sIKqn6ZVUA6Bq0XkX6T9v4KqnoOml+gar4tqX5Az+BrR6apIjShvEavF5WH/e8/c877lBrBbdVRis6jaIFZvq/ghutegO9MCb3CBWxlS+K4iVEcg2BrFatLmqvR0QqzU+LGI2WNWic0ehKRqVb2OX3gpY1Zqf91Q2WNWi2xBk8MAGqDJVUp78BqjiKiXffnuBfGmAqsXUPpufQayWvxxBatDGizbaAs8FuMqYBtMgcNXi29wj09O6++fC4d9MhzFNaMYGqNrX92YCqNp0u2/AYjb41OYLdYN5GGTKJIkKxngwKZO0SvYTMCkjCEYYMCk2jbwkMCmusf4hQKZY8MtGd8CpXWlpEXQSYKmn6b/nN2Xxy2m0MwM+tSnnhXa3wac2pQXJzs5tgCrWZExig1Vtn4zj5UOBVW1K8SEZ9Aao2kyLZUsDV23OgiE/K1gVC6L5FZRqUx5rh8I6p2zboFRcfOQPA05tPqkbTFLAUpvSZOuZHnCKy45+LmCpzed/g+YEjWLT6BcBjdrfjyFv0Ch+Rf1/AEWZJ8iuAhS1h3PfVF8HijIa+RMCRW1OYi1eY/yAorY/hxTX6tZcRqNjoW9Bca/x3itvU7Qx391kF7z/+Jn/2+lvTTOaIr3vW4DGprn7PQLkNh3GtHofulF8z62ZRhMdab9Nl6vJ+7x5m6JpOTQ5qPRBTv3HV/SJce8WXEag3e1bUIxAb0HfguqqFP8u//P/AQ==\", BinaryEncoding.Base64), Compression.Deflate)),",
                " Rows = Table.FromRows(Source, [\"contact_id\", \"account_id\", \"collector_id\", \"contact_date\", \"outcome\", \"promise_due_date\", \"promise_amount\"]),",
                " Typed = Table.TransformColumnTypes(Rows, {{\"contact_id\", Int64.Type}, {\"account_id\", Int64.Type}, {\"collector_id\", Int64.Type}, {\"contact_date\", type date}, {\"outcome\", type text}, {\"promise_due_date\", type date}, {\"promise_amount\", type number}}, \"en-US\")",
                "in Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "Collectors",
        "columns": [
          {
            "name": "collector_id",
            "dataType": "int64",
            "sourceColumn": "collector_id",
            "summarizeBy": "none"
          },
          {
            "name": "collector_name",
            "dataType": "string",
            "sourceColumn": "collector_name",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Collectors",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                " Source = Json.Document(Binary.Decompress(Binary.FromText(\"i4421FFyzEmtUIrViTbSUXJOLE6tBLGNdZS88otSEvNAHBMdJd/8onQIx1RHKSgzB6LKTEcpJLEyJ78IxDHXUQrNSywuzkzPS01Rio0FAA==\", BinaryEncoding.Base64), Compression.Deflate)),",
                " Rows = Table.FromRows(Source, [\"collector_id\", \"collector_name\"]),",
                " Typed = Table.TransformColumnTypes(Rows, {{\"collector_id\", Int64.Type}, {\"collector_name\", type text}}, \"en-US\")",
                "in Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "Dates",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "formatString": "yyyy-MM-dd",
            "isKey": true
          },
          {
            "name": "month_label",
            "dataType": "string",
            "sourceColumn": "month_label",
            "summarizeBy": "none",
            "sortByColumn": "month_number"
          },
          {
            "name": "month_number",
            "dataType": "int64",
            "sourceColumn": "month_number",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Dates",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                " Source = Json.Document(Binary.Decompress(Binary.FromText(\"bdc9ahxBAITRu0w8hq3q+Q2dODD4BEKBDEqFMTjw7b3syqBFDzr6sgdF0/30NPXS7csl1zPN0/eXt2nO8/wh13k4L86r8+a8Ox/OJ3MuzlbGylgZK2NlrIyVsTJW1spaWStrZa2slbWyVtbKWjmsHFL2PuRvrz+nuQ+5zsN5cV6dN+fd+XA+mW9DRrYyVsbKWBkrY2WsjJWxslbWylpZK2tlrayVtbJSjvsGf7z8nubxkOs8nBfn1Xlz3p0P55P5tkFkK2NlrIyVsTJWxspYGStrZa2slbWyVtbKWlkra2WtHFYOKZf7kL/+uublIdd5OC/Oq/PmvDsfzifzbcjIVsbKWBkrY2WsjJWxMlbWylpZK2tlrayVtbJW1spaOaRc/1+9f6d5fch1Hs6L8+q8Oe/Oh/PJ/H71fspWxspYGStjZayMlbEyVtbKWlkra2WtrJW1slbWylo5rBxSbu8fsj/X5+32kOs8nBfn1Xlz3p0P55P5/iH7nK2MlbEyVsbKWBkrY2WsrJW1slbWylpZK2tlrayVtXJ8UD7/Aw==\", BinaryEncoding.Base64), Compression.Deflate)),",
                " Rows = Table.FromRows(Source, [\"Date\", \"month_label\", \"month_number\"]),",
                " Typed = Table.TransformColumnTypes(Rows, {{\"Date\", type date}, {\"month_label\", type text}, {\"month_number\", Int64.Type}}, \"en-US\")",
                "in Typed"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "5e007577-cb23-55e1-a0b5-15a276bd2daa",
        "fromTable": "Accounts",
        "fromColumn": "collector_id",
        "toTable": "Collectors",
        "toColumn": "collector_id",
        "fromCardinality": "many",
        "toCardinality": "one",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "185f027a-8de9-5935-9ba3-9d7002f43c2a",
        "fromTable": "Payments",
        "fromColumn": "account_id",
        "toTable": "Accounts",
        "toColumn": "account_id",
        "fromCardinality": "many",
        "toCardinality": "one",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "431d204b-7d36-5b0e-8b2a-d02f17ba9dfd",
        "fromTable": "Contacts",
        "fromColumn": "account_id",
        "toTable": "Accounts",
        "toColumn": "account_id",
        "fromCardinality": "many",
        "toCardinality": "one",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "64894eef-0c55-5f11-8e72-18f7718c1ab0",
        "fromTable": "Payments",
        "fromColumn": "payment_date",
        "toTable": "Dates",
        "toColumn": "Date",
        "fromCardinality": "many",
        "toCardinality": "one",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "23715cbe-c0ac-5322-b8ac-68ec5e3a9708",
        "fromTable": "Contacts",
        "fromColumn": "contact_date",
        "toTable": "Dates",
        "toColumn": "Date",
        "fromCardinality": "many",
        "toCardinality": "one",
        "crossFilteringBehavior": "oneDirection"
      }
    ]
  }
}
