import fs from 'node:fs';import assert from 'node:assert/strict';import {score,contributions,validateAccount,evaluate,queue,csv} from './dist/ml.mjs';
const data=JSON.parse(fs.readFileSync(new URL('./dist/data.json',import.meta.url))),fixtures=JSON.parse(fs.readFileSync(new URL('./parity-fixtures.json',import.meta.url)));const errors={};
for(const key of ['logistic','forest']){let max=0;fixtures.rows.forEach((row,i)=>{const p=score(data.models[key],row);assert(Number.isFinite(p)&&p>=0&&p<=1);max=Math.max(max,Math.abs(p-fixtures.expected[key][i]));});assert(max<1e-12);errors[key]=max;}
const a=data.accounts.find(a=>a.monthly_income===null);assert(a);validateAccount(a);assert.equal(contributions(data.models.logistic,a).find(r=>r.feature==='monthly_income').value,(data.models.logistic.medians[2]-data.models.logistic.means[2])/data.models.logistic.scales[2]*data.models.logistic.coefficients[2]);
for(const bad of [{...a,credit_score:Infinity},{...a,days_past_due:90},{...a,utilization:1.1},{...a,balance:-1},{...a,portfolio:'Unknown'},{...a,missed_payments_6m:1.5}])assert.throws(()=>validateAccount(bad));
const contributionSum=contributions(data.models.logistic,a).reduce((s,r)=>s+r.value,data.models.logistic.intercept);assert(Math.abs(score(data.models.logistic,a)-1/(1+Math.exp(-contributionSum)))<1e-14);
for(const key of ['logistic','forest']){const lo=evaluate(data.holdout,key,.01),hi=evaluate(data.holdout,key,.99),mid=evaluate(data.holdout,key,.5);assert(lo.flagged>=hi.flagged);assert.equal(mid.tp+mid.fp+mid.tn+mid.fn,995);const original=data.testMetrics.find(r=>r.model===(key==='logistic'?'Logistic Regression':'Random Forest'));for(const v of ['tp','tn','fp','fn'])assert.equal(mid[v],original[v]);const all=queue(data.accounts,data.models,key,.26);assert.equal(all.length,500);assert(all.every((a,i)=>i===0||all[i-1].probability>=a.probability));const flagged=queue(data.accounts,data.models,key,.26,'flagged');assert(flagged.every(a=>a.probability>=.26));assert.equal(csv(flagged,.26,key).split('\n').length,flagged.length+1);}
assert.equal(evaluate([], 'logistic',.5).precision,0);assert.equal(evaluate([{y:1,logistic:.26}],'logistic',.26).tp,1);
const html=fs.readFileSync(new URL('./dist/index.html',import.meta.url),'utf8');for(const file of ['app.mjs','ml.mjs','style.css','data.json'])assert(fs.existsSync(new URL('./dist/'+file,import.meta.url)));for(const id of ['score','lab','queue','method','model','threshold','download'])assert(html.includes(`id="${id}"`));
const result={status:'passed',parityRows:fixtures.rows.length,maximumProbabilityError:errors,checks:['original Python predictions reproduced','browser logistic and forest inference parity','missing income imputation','signed logistic contributions','invalid inputs rejected','holdout confusion matrix reconciliation','threshold boundary and monotonicity','500 account queue sorting and filtering','CSV row count and metadata','static assets and main controls'],limitations:['No native browser rendering test in this environment','WebMCP registration validation unavailable in a supported browser context']};fs.writeFileSync(new URL('./validation.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
